CREATE TABLE [dbo].[DEDCODE] (
    [COMPANY]        SMALLINT        NOT NULL,
    [DED_CODE]       CHAR (4)        NOT NULL,
    [DESCRIPTION]    CHAR (30)       NOT NULL,
    [CHECK_DESC]     CHAR (8)        NOT NULL,
    [CALC_TYPE]      CHAR (1)        NOT NULL,
    [AMOUNT_PERC]    DECIMAL (13, 4) NOT NULL,
    [TAX_STATUS]     CHAR (2)        NOT NULL,
    [ADJUST_PAY]     CHAR (1)        NOT NULL,
    [REQ_CODE]       CHAR (3)        NOT NULL,
    [DED_CLASS]      CHAR (3)        NOT NULL,
    [DED_PRIORITY]   TINYINT         NOT NULL,
    [ARREARS]        CHAR (1)        NOT NULL,
    [EFFECT_DATE]    DATETIME        NOT NULL,
    [END_DATE]       DATETIME        NOT NULL,
    [ACR_DIST_CO]    SMALLINT        NOT NULL,
    [ACR_ACCT_UNIT]  CHAR (15)       NOT NULL,
    [ACR_ACCOUNT]    INT             NOT NULL,
    [ACR_SUB_ACCT]   SMALLINT        NOT NULL,
    [EXP_DIST_CO]    SMALLINT        NOT NULL,
    [EXP_ACCT_UNIT]  CHAR (15)       NOT NULL,
    [EXP_ACCOUNT]    INT             NOT NULL,
    [EXP_SUB_ACCT]   SMALLINT        NOT NULL,
    [CHANGE_FLAG]    CHAR (1)        NOT NULL,
    [USED_FLAG]      CHAR (1)        NOT NULL,
    [MATCHED_DED]    CHAR (4)        NOT NULL,
    [PAY_CLASS]      CHAR (3)        NOT NULL,
    [EXCLUDE_FLAG]   CHAR (1)        NOT NULL,
    [DED_CYCLE_01]   CHAR (1)        NOT NULL,
    [DED_CYCLE_02]   CHAR (1)        NOT NULL,
    [DED_CYCLE_03]   CHAR (1)        NOT NULL,
    [DED_CYCLE_04]   CHAR (1)        NOT NULL,
    [DED_CYCLE_05]   CHAR (1)        NOT NULL,
    [DED_CYCLE_06]   CHAR (1)        NOT NULL,
    [DED_CYCLE_07]   CHAR (1)        NOT NULL,
    [DED_CYCLE_08]   CHAR (1)        NOT NULL,
    [DED_CYCLE_09]   CHAR (1)        NOT NULL,
    [MTD_WAGES_IND]  CHAR (1)        NOT NULL,
    [WC_TABLE_FLAG]  CHAR (1)        NOT NULL,
    [TAX_CATEGORY]   SMALLINT        NOT NULL,
    [TAX_ID_CODE]    CHAR (10)       NOT NULL,
    [MONTHLY_LIMIT]  DECIMAL (11, 2) NOT NULL,
    [PAY_PRD_LIMIT]  DECIMAL (11, 2) NOT NULL,
    [PRINT_FLAG]     CHAR (1)        NOT NULL,
    [FORMULA_NUMBER] TINYINT         NOT NULL,
    [PRIOR_SUI_WAGE] CHAR (1)        NOT NULL,
    [TAX_AUTH_TYPE]  CHAR (2)        NOT NULL,
    [ACTIVITY]       CHAR (15)       NOT NULL,
    [ACCT_CATEGORY]  CHAR (5)        NOT NULL,
    [SELF_ADJ_TAX]   CHAR (1)        NOT NULL,
    [LINKED_DED]     CHAR (4)        NOT NULL,
    [UPDATE_AP]      CHAR (1)        NOT NULL,
    [VENDOR]         CHAR (9)        NOT NULL,
    [CREATE_BY_EMP]  CHAR (1)        NOT NULL,
    [AMOUNT_2]       DECIMAL (13, 4) NOT NULL,
    [GARNISHMENT]    CHAR (1)        NOT NULL,
    [EDI]            CHAR (1)        NOT NULL,
    [COUNTRY_CODE]   CHAR (2)        NOT NULL,
    [CLIENT_CREDIT]  CHAR (1)        NOT NULL,
    [CURRENCY_CODE]  CHAR (5)        NOT NULL,
    [CURR_ND]        TINYINT         NOT NULL,
    [EDM_PROCESS]    CHAR (1)        NOT NULL,
    [OTD_PROCESS]    CHAR (1)        NOT NULL,
    [ACCR_AU_FLAG]   CHAR (1)        NOT NULL,
    [REMIT_TO_CODE]  CHAR (4)        NOT NULL,
    [EXCLUDE_AMT]    DECIMAL (13, 4) NOT NULL,
    [DDCSET3_SS_SW]  CHAR (1)        NOT NULL,
    [DDCSET5_SS_SW]  CHAR (1)        NOT NULL,
    [DDCSET6_SS_SW]  CHAR (1)        NOT NULL,
    [DDCSET7_SS_SW]  CHAR (1)        NOT NULL
);

