CREATE TABLE [dbo].[PAYDEDUCTN] (
    [COMPANY]        SMALLINT        NOT NULL,
    [EMPLOYEE]       INT             NOT NULL,
    [CHECK_ID]       DECIMAL (12)    NOT NULL,
    [DED_CODE]       CHAR (4)        NOT NULL,
    [PROCESS_LEVEL]  CHAR (5)        NOT NULL,
    [WORK_STATE]     CHAR (2)        NOT NULL,
    [PAYROLL_YEAR]   SMALLINT        NOT NULL,
    [QUARTER]        TINYINT         NOT NULL,
    [EDM_SEQ_NBR]    SMALLINT        NOT NULL,
    [DED_AMT]        DECIMAL (13, 2) NOT NULL,
    [TAX_WAGES]      DECIMAL (13, 2) NOT NULL,
    [WAGE_AMOUNT]    DECIMAL (13, 2) NOT NULL,
    [EXCESS]         DECIMAL (13, 2) NOT NULL,
    [GARN_OBJ_ID]    DECIMAL (12)    NOT NULL,
    [REPORT_ENTITY]  CHAR (5)        NOT NULL,
    [BUS_NBR_GRP]    CHAR (4)        NOT NULL,
    [QC_ENT_NBR_GRP] CHAR (4)        NOT NULL,
    [OBJ_ID]         DECIMAL (12)    NOT NULL,
    [CURRENCY_CODE]  CHAR (5)        NOT NULL,
    [CURR_ND]        TINYINT         NOT NULL,
    [CHECK_DATE]     DATETIME        NOT NULL,
    [PER_END_DATE]   DATETIME        NOT NULL,
    [BALANCE_TYPE]   CHAR (1)        NOT NULL,
    [TAX_FLAG]       CHAR (1)        NOT NULL,
    [HM_PROCESS_LEV] CHAR (5)        NOT NULL,
    [COUNTRY_CODE]   CHAR (2)        NOT NULL,
    [NI_CODE]        CHAR (1)        NOT NULL,
    [DIRECTOR]       CHAR (1)        NOT NULL,
    [TAX_CODE]       CHAR (10)       NOT NULL,
    [TAX_BASIS]      CHAR (1)        NOT NULL,
    [PERIOD_NBR]     SMALLINT        NOT NULL,
    [CONTRACTED_OUT] CHAR (1)        NOT NULL,
    [OT_PLAN_CODE]   CHAR (4)        NOT NULL
);

