CREATE TABLE [dbo].[PAYSUMGRP] (
    [COMPANY]        SMALLINT  NOT NULL,
    [PAY_SUM_GRP]    CHAR (3)  NOT NULL,
    [DESCRIPTION]    CHAR (30) NOT NULL,
    [CHECK_DESC]     CHAR (8)  NOT NULL,
    [TIP_PAY_TYPE]   TINYINT   NOT NULL,
    [ELIG_OT_PAY]    CHAR (1)  NOT NULL,
    [ELIG_OT_HRS]    CHAR (1)  NOT NULL,
    [ELIG_PREM_PAY]  CHAR (1)  NOT NULL,
    [ELIG_PREM_CRED] CHAR (1)  NOT NULL,
    [SUPP_TAX_CODE]  CHAR (2)  NOT NULL,
    [CHANGE_FLAG]    CHAR (1)  NOT NULL,
    [COUNTRY_CODE]   CHAR (2)  NOT NULL,
    [PAYMENT_TYPE]   CHAR (2)  NOT NULL,
    [INCOME_TYPE]    CHAR (2)  NOT NULL,
    [REMUN_CODE]     CHAR (4)  NOT NULL,
    [TAX_FORM_TYPE]  TINYINT   NOT NULL,
    [RPTABLE_1099R]  SMALLINT  NOT NULL,
    [PSGSET2_SS_SW]  CHAR (1)  NOT NULL
);

