CREATE TABLE [dbo].[PRPAYCODE] (
    [COMPANY]       SMALLINT        NOT NULL,
    [PROCESS_LEVEL] CHAR (5)        NOT NULL,
    [JOB_CODE]      CHAR (9)        NOT NULL,
    [PAY_CODE]      CHAR (4)        NOT NULL,
    [DESCRIPTION]   CHAR (30)       NOT NULL,
    [NORM_RATE]     DECIMAL (13, 4) NOT NULL,
    [SHIFT1]        DECIMAL (13, 4) NOT NULL,
    [SHIFT2]        DECIMAL (13, 4) NOT NULL,
    [SHIFT3]        DECIMAL (13, 4) NOT NULL,
    [SHIFT4]        DECIMAL (13, 4) NOT NULL,
    [CALC_TYPE]     CHAR (1)        NOT NULL,
    [PAY_SUM_GRP]   CHAR (3)        NOT NULL,
    [WE_DIST_CO]    SMALLINT        NOT NULL,
    [WE_ACCT_UNIT]  CHAR (15)       NOT NULL,
    [WE_ACCOUNT]    INT             NOT NULL,
    [WE_SUB_ACCT]   SMALLINT        NOT NULL,
    [CR_DIST_CO]    SMALLINT        NOT NULL,
    [CR_ACCT_UNIT]  CHAR (15)       NOT NULL,
    [CR_ACCOUNT]    INT             NOT NULL,
    [CR_SUB_ACCT]   SMALLINT        NOT NULL,
    [EXCLUDE_FLAG]  CHAR (1)        NOT NULL,
    [OT_PREM_RATE]  DECIMAL (13, 4) NOT NULL,
    [OT_ACCOUNT]    INT             NOT NULL,
    [OT_SUB_ACCT]   SMALLINT        NOT NULL,
    [SH_ACCOUNT]    INT             NOT NULL,
    [SH_SUB_ACCT]   SMALLINT        NOT NULL,
    [SEQ_NBR]       SMALLINT        NOT NULL,
    [USED_FLAG]     CHAR (1)        NOT NULL,
    [BN_USED_FLAG]  CHAR (1)        NOT NULL,
    [ACTIVITY]      CHAR (15)       NOT NULL,
    [ACCT_CATEGORY] CHAR (5)        NOT NULL,
    [SHIFT_CODE]    CHAR (4)        NOT NULL,
    [CURRENCY_CODE] CHAR (5)        NOT NULL,
    [CURR_ND]       TINYINT         NOT NULL,
    [ATTEND_CODE]   CHAR (2)        NOT NULL,
    [PAY_CLASS]     CHAR (3)        NOT NULL,
    [ACTIVE_FLAG]   CHAR (1)        NOT NULL,
    [ALLOW_HOURS]   TINYINT         NOT NULL,
    [NON_EARNINGS]  TINYINT         NOT NULL,
    [UNIT_MEASURE]  CHAR (12)       NOT NULL,
    [SERVICE_CODE]  CHAR (4)        NOT NULL,
    [PCDSET6_SS_SW] CHAR (1)        NOT NULL
);

