CREATE TABLE [dbo].[PSGRELATE] (
    [COMPANY]     SMALLINT NOT NULL,
    [PAY_CLASS]   CHAR (3) NOT NULL,
    [PAY_SUM_GRP] CHAR (3) NOT NULL,
    [HOURS_FLAG]  CHAR (1) NOT NULL,
    [WAGES_FLAG]  CHAR (1) NOT NULL
);

