CREATE TABLE [dbo].[Ceridian_EEmploy] (
    [EeMagic]              INT          NULL,
    [EeFlxIDEb]            INT          NULL,
    [EeFlxIDP2]            INT          NULL,
    [EeCRC]                INT          NULL,
    [EeSource]             INT          NULL,
    [EeNote]               INT          NULL,
    [EeFlxID]              INT          NOT NULL,
    [EeDateAdd]            DATETIME     NULL,
    [EeDateMod]            DATETIME     NULL,
    [EeDateDel]            DATETIME     NULL,
    [EeDateBeg]            DATETIME     NULL,
    [EeDateEnd]            DATETIME     NULL,
    [EeDateRBeg]           DATETIME     NULL,
    [EeDateREnd]           DATETIME     NULL,
    [EeUserName]           VARCHAR (20) NULL,
    [EeRecType]            VARCHAR (4)  NULL,
    [EeArchive]            VARCHAR (1)  NULL,
    [EeDateOriginalHire]   DATETIME     NULL,
    [EeDateLastHire]       DATETIME     NULL,
    [EeDateSeniorityCalc]  DATETIME     NULL,
    [EeDateBenefitCalc]    DATETIME     NULL,
    [EeTermDate]           DATETIME     NULL,
    [EeTermWhy]            VARCHAR (30) NOT NULL,
    [EeHireBack]           VARCHAR (30) NOT NULL,
    [EeI9Status]           VARCHAR (30) NOT NULL,
    [EeDateI9Expire]       DATETIME     NULL,
    [EeAlienNumber]        VARCHAR (10) NULL,
    [EeSocNumber]          VARCHAR (9)  NULL,
    [EeEmpNumber]          VARCHAR (10) NULL,
    [EeEmpNumber2]         VARCHAR (9)  NULL,
    [EeEmpNumber3]         VARCHAR (9)  NULL,
    [EeSecurityClearance]  VARCHAR (30) NOT NULL,
    [EeFoundSource]        VARCHAR (30) NOT NULL,
    [EeOwnPct]             FLOAT (53)   NULL,
    [EeHighComp]           VARCHAR (1)  NOT NULL,
    [EeOfficer]            VARCHAR (1)  NOT NULL,
    [EeCategory]           VARCHAR (30) NOT NULL,
    [EeDateStatus]         DATETIME     NULL,
    [EeStatus]             VARCHAR (30) NOT NULL,
    [EeWorkCompElg]        VARCHAR (1)  NULL,
    [EeRegTemp]            VARCHAR (1)  NULL,
    [EeFindCost]           MONEY        NULL,
    [EeReferName]          VARCHAR (20) NULL,
    [EeHolidayCal]         VARCHAR (30) NULL,
    [EeUnion]              VARCHAR (30) NOT NULL,
    [EeShares]             FLOAT (53)   NULL,
    [EeStockId]            VARCHAR (10) NULL,
    [EeKeyEmp]             VARCHAR (1)  NOT NULL,
    [EeEnrollmentCal]      VARCHAR (30) NULL,
    [EeBenefitType]        VARCHAR (30) NULL,
    [EeI9Document1]        VARCHAR (30) NULL,
    [EeI9Document1Exp]     DATETIME     NULL,
    [EeI9Document1ID]      VARCHAR (20) NULL,
    [EeI9Document2]        VARCHAR (30) NULL,
    [EeI9Document2Exp]     DATETIME     NULL,
    [EeI9Document2ID]      VARCHAR (20) NULL,
    [EePassportNumber]     VARCHAR (20) NULL,
    [EePPExpirationDate]   DATETIME     NULL,
    [EePPIssuingCountry]   VARCHAR (20) NULL,
    [EeVisaExpirationDate] DATETIME     NULL,
    [EeVisaNumber]         VARCHAR (20) NULL,
    [EeVisaType]           VARCHAR (30) NULL,
    [EeNoticeLen]          INT          NULL,
    [EeNoticeUnit]         VARCHAR (1)  NULL,
    [EeExitInterviewBy]    INT          NULL,
    [EeUpsize_ts]          ROWVERSION   NULL
);


GO
CREATE CLUSTERED INDEX [CE_FlxID_idx]
    ON [dbo].[Ceridian_EEmploy]([EeFlxIDEb] ASC) WITH (FILLFACTOR = 90);

