CREATE TABLE [dbo].[Ceridian_PayrollSchedule] (
    [PrpMagic]                   INT          NULL,
    [PrpFlxIDPrs]                INT          NULL,
    [PrpFlxIDPrp]                INT          NULL,
    [PrpCRC]                     INT          NULL,
    [PrpSource]                  INT          NULL,
    [PrpNote]                    INT          NULL,
    [PrpFlxID]                   INT          NOT NULL,
    [PrpDateAdd]                 DATETIME     NULL,
    [PrpDateMod]                 DATETIME     NULL,
    [PrpDateDel]                 DATETIME     NULL,
    [PrpDateBeg]                 DATETIME     NULL,
    [PrpDateEnd]                 DATETIME     NULL,
    [PrpDateRBeg]                DATETIME     NULL,
    [PrpDateREnd]                DATETIME     NULL,
    [PrpUserName]                VARCHAR (20) NULL,
    [PrpRecType]                 VARCHAR (4)  NULL,
    [PrpArchive]                 VARCHAR (1)  NULL,
    [PrpPSID]                    VARCHAR (8)  NULL,
    [PrpPayPeriod]               VARCHAR (10) NOT NULL,
    [PrpDueInDate]               DATETIME     NULL,
    [PrpDueOutDate]              DATETIME     NULL,
    [PrpReportDate]              DATETIME     NULL,
    [PrpSpecialTaxCode]          VARCHAR (2)  NULL,
    [PrpComment]                 VARCHAR (20) NULL,
    [PrpStatus]                  VARCHAR (10) NULL,
    [PrpOffScheduleAddFlag]      VARCHAR (1)  NULL,
    [PrpOffScheduleOverrideFlag] VARCHAR (1)  NULL,
    [PrpFrequencies]             VARCHAR (10) NULL,
    [PrpEOMFlag]                 VARCHAR (1)  NULL,
    [PrpEOQFlag]                 VARCHAR (1)  NULL,
    [PrpEOYFlag]                 VARCHAR (1)  NULL,
    [PrpSentFlag]                VARCHAR (1)  NULL,
    [PrpFinalProcessingFlag]     VARCHAR (1)  NULL,
    [PrpTotalBaseRates]          FLOAT (53)   NULL,
    [PrpTotalHours]              FLOAT (53)   NULL,
    [PrpTotalEarnings]           FLOAT (53)   NULL,
    [PrpTotalDedAndAdj]          FLOAT (53)   NULL,
    [PrpTotalLaborHours]         FLOAT (53)   NULL,
    [PrpTotalPayrollHours]       FLOAT (53)   NULL,
    [PrpTotalVMA]                INT          NULL,
    [PrpUpsize_ts]               BINARY (8)   NULL
);

