CREATE TABLE [dbo].[Ceridian_PayType] (
    [PytMagic]              INT          NULL,
    [PytFlxIDP1]            INT          NULL,
    [PytFlxIDP2]            INT          NULL,
    [PytCRC]                INT          NULL,
    [PytSource]             INT          NULL,
    [PytNote]               INT          NULL,
    [PytFlxID]              INT          NOT NULL,
    [PytDateAdd]            DATETIME     NULL,
    [PytDateMod]            DATETIME     NULL,
    [PytDateDel]            DATETIME     NULL,
    [PytDateBeg]            DATETIME     NULL,
    [PytDateEnd]            DATETIME     NULL,
    [PytDateRBeg]           DATETIME     NULL,
    [PytDateREnd]           DATETIME     NULL,
    [PytUserName]           VARCHAR (20) NULL,
    [PytRecType]            VARCHAR (4)  NULL,
    [PytArchive]            VARCHAR (1)  NULL,
    [PytCode]               VARCHAR (2)  NULL,
    [PytShort]              VARCHAR (5)  NULL,
    [PytDescrip]            VARCHAR (13) NULL,
    [PytPSID]               VARCHAR (8)  NOT NULL,
    [PytPayToEmpFlag]       VARCHAR (1)  NOT NULL,
    [PytPayrollOnlyFlag]    VARCHAR (1)  NOT NULL,
    [PytLaborOnlyFlag]      VARCHAR (1)  NOT NULL,
    [PytSDIFlag]            VARCHAR (1)  NOT NULL,
    [PytLocalFlag]          VARCHAR (1)  NOT NULL,
    [PytFUTAFlag]           VARCHAR (1)  NOT NULL,
    [PytValidFlag]          VARCHAR (1)  NOT NULL,
    [PytFitFlag]            VARCHAR (1)  NOT NULL,
    [PytSitFlag]            VARCHAR (1)  NOT NULL,
    [PytFICAFlag]           VARCHAR (1)  NOT NULL,
    [PytDefaultRateCode]    VARCHAR (1)  NULL,
    [PytDefaultRate]        FLOAT (53)   NULL,
    [PytEffectivePayPeriod] VARCHAR (10) NOT NULL,
    [PytAttendanceCode]     VARCHAR (2)  NULL,
    [PytAddCompCode]        VARCHAR (2)  NULL,
    [PytPayPeriod]          VARCHAR (10) NOT NULL,
    [PytInfo1]              VARCHAR (30) NULL,
    [PytUpsize_ts]          BINARY (8)   NULL
);

