CREATE TABLE [dbo].[Ceridian_CardFile] (
    [CfMagic]        INT           NULL,
    [CfFlxIDFt]      INT           NULL,
    [CfFlxIDP2]      INT           NULL,
    [CfCRC]          INT           NULL,
    [CfSource]       INT           NULL,
    [CfNote]         INT           NULL,
    [CfFlxID]        INT           NOT NULL,
    [CfDateAdd]      DATETIME      NULL,
    [CfDateMod]      DATETIME      NULL,
    [CfDateDel]      DATETIME      NULL,
    [CfDateBeg]      DATETIME      NULL,
    [CfDateEnd]      DATETIME      NULL,
    [CfDateRBeg]     DATETIME      NULL,
    [CfDateREnd]     DATETIME      NULL,
    [CfUserName]     VARCHAR (20)  NULL,
    [CfRecType]      VARCHAR (4)   NULL,
    [CfArchive]      VARCHAR (1)   NULL,
    [CfShort]        VARCHAR (10)  NULL,
    [CfCardType]     VARCHAR (10)  NOT NULL,
    [CfAttach]       VARCHAR (30)  NULL,
    [CfCompany]      VARCHAR (30)  NULL,
    [CfZip]          VARCHAR (10)  NULL,
    [CfGenPhone]     VARCHAR (14)  NULL,
    [CfFax]          VARCHAR (14)  NULL,
    [CfContact]      VARCHAR (30)  NULL,
    [CfContactPhone] VARCHAR (14)  NULL,
    [CfAccount]      VARCHAR (30)  NULL,
    [CfURL]          VARCHAR (255) NULL,
    [CfInfo1]        VARCHAR (30)  NULL,
    [CfFlxIDRow]     INT           NULL,
    [CfFlxIDCf]      INT           NULL,
    [CfFlxIDEb]      INT           NULL,
    [CfDataSource]   VARCHAR (10)  NOT NULL,
    [CfFirst]        VARCHAR (30)  NULL,
    [CfLast]         VARCHAR (30)  NULL,
    [CfMiddle]       VARCHAR (30)  NULL,
    [CfPayPeriod]    VARCHAR (10)  NOT NULL,
    [CfSuffix]       VARCHAR (4)   NULL,
    [CfContactExt]   VARCHAR (6)   NULL,
    [CfInfo2]        VARCHAR (30)  NULL,
    [CfStreet1]      VARCHAR (35)  NULL,
    [CfStreet2]      VARCHAR (35)  NULL,
    [CfCity]         VARCHAR (35)  NULL,
    [CfState]        VARCHAR (35)  NOT NULL,
    [CfCountry]      VARCHAR (35)  NOT NULL,
    [CfGenExt]       VARCHAR (6)   NULL,
    [CffaxExt]       VARCHAR (6)   NULL,
    [CfEmail]        VARCHAR (255) NULL,
    [CfUpsize_ts]    ROWVERSION    NOT NULL
);

