CREATE TABLE [dbo].[Ceridian_CalItem] (
    [CdMagic]             INT          NULL,
    [CdFlxIDCb]           INT          NULL,
    [CdFlxIDPrp]          INT          NULL,
    [CdCRC]               INT          NULL,
    [CdSource]            INT          NULL,
    [CdNote]              INT          NULL,
    [CdFlxID]             INT          NOT NULL,
    [CdDateAdd]           DATETIME     NULL,
    [CdDateMod]           DATETIME     NULL,
    [CdDateDel]           DATETIME     NULL,
    [CdDateBeg]           DATETIME     NULL,
    [CdDateEnd]           DATETIME     NULL,
    [CdDateRBeg]          DATETIME     NULL,
    [CdDateREnd]          DATETIME     NULL,
    [CdUserName]          VARCHAR (20) NULL,
    [CdRecType]           VARCHAR (4)  NULL,
    [CdArchive]           VARCHAR (1)  NULL,
    [CdDate]              DATETIME     NULL,
    [CdIndex]             VARCHAR (20) NULL,
    [CdDescrip]           VARCHAR (30) NULL,
    [CdStatus]            VARCHAR (10) NULL,
    [CdDeductionSchedule] VARCHAR (1)  NULL,
    [CdCheckDate]         DATETIME     NULL,
    [CdAccountingMonth]   INT          NULL,
    [CdAccrualMonth]      INT          NULL,
    [CdAccrualPercent]    FLOAT (53)   NULL,
    [CdNumberOfHolidays]  INT          NULL,
    [CdUpsize_ts]         BINARY (8)   NULL
);

