CREATE TABLE [dbo].[Ceridian_MACust_elabor] (
    [Lbrcustcode]      VARCHAR (10)    NULL,
    [Lbrcustpaycode]   VARCHAR (3)     NULL,
    [LbrMagic]         INT             NULL,
    [LbrFlxIDEb]       INT             NOT NULL,
    [LbrFlxIDP2]       INT             NULL,
    [LbrCRC]           INT             NULL,
    [LbrSource]        INT             NULL,
    [LbrNote]          INT             NULL,
    [LbrFlxID]         INT             NOT NULL,
    [LbrDateAdd]       DATETIME        NULL,
    [LbrDateMod]       DATETIME        NULL,
    [LbrDateDel]       DATETIME        NULL,
    [LbrDateBeg]       DATETIME        NULL,
    [LbrDateEnd]       DATETIME        NULL,
    [LbrDateRBeg]      DATETIME        NULL,
    [LbrDateREnd]      DATETIME        NULL,
    [LbrUserName]      VARCHAR (20)    NULL,
    [LbrRecType]       VARCHAR (4)     NULL,
    [LbrArchive]       VARCHAR (1)     NULL,
    [LbrPayPeriod]     VARCHAR (10)    NOT NULL,
    [LbrPSID]          VARCHAR (8)     NULL,
    [LbrDivDept]       VARCHAR (6)     NULL,
    [LbrDistCode]      VARCHAR (1)     NULL,
    [LbrPayClass]      VARCHAR (1)     NULL,
    [LbrRateCode]      VARCHAR (1)     NULL,
    [LbrTotalHours]    DECIMAL (10, 2) NULL,
    [LbrTotalEarnings] MONEY           NULL,
    [LbrRatePaid]      DECIMAL (16, 4) NULL,
    [LbrChrgDivDept]   VARCHAR (6)     NULL,
    [LbrDistData]      VARCHAR (19)    NULL,
    [LbrAdjCode]       VARCHAR (1)     NULL,
    [LbrPayFreq]       VARCHAR (1)     NULL,
    [LbrSocNumber]     VARCHAR (9)     NULL,
    [LbrEmpName]       VARCHAR (23)    NULL,
    [LbrMiscData]      VARCHAR (20)    NULL,
    [LbrMaritalStatus] VARCHAR (1)     NULL,
    [LbrSex]           VARCHAR (1)     NULL,
    [LbrUCState]       VARCHAR (2)     NULL,
    [LbrSecPayCode]    VARCHAR (2)     NULL,
    [LbrVoidManCode]   VARCHAR (1)     NULL,
    [LbrVacCode]       VARCHAR (1)     NULL,
    [LbrSickCode]      VARCHAR (1)     NULL,
    [LbrBaseRateDec]   VARCHAR (1)     NULL,
    [LbrBaseRate]      DECIMAL (16, 4) NULL,
    [LbrDiv]           VARCHAR (6)     NULL,
    [LbrChrgDiv]       VARCHAR (6)     NULL,
    [LbrDept]          VARCHAR (6)     NULL,
    [LbrChrgDept]      VARCHAR (6)     NULL,
    [LbrUpsize_ts]     BINARY (8)      NULL
);

