CREATE TABLE [dbo].[Echo_pgroups_Current] (
    [tax_id]    CHAR (15)  NULL,
    [pgroup_nm] CHAR (60)  NULL,
    [addr]      CHAR (30)  NULL,
    [addr2]     CHAR (30)  NULL,
    [city]      CHAR (20)  NULL,
    [state]     CHAR (2)   NULL,
    [zip]       CHAR (10)  NULL,
    [phone]     CHAR (14)  NULL,
    [contact]   CHAR (40)  NULL,
    [chairman]  CHAR (40)  NULL,
    [fax]       CHAR (14)  NULL,
    [cmt]       CHAR (40)  NULL,
    [l_p_type]  CHAR (5)   NULL,
    [b_addr]    CHAR (30)  NULL,
    [b_addr2]   CHAR (30)  NULL,
    [b_city]    CHAR (15)  NULL,
    [b_state]   CHAR (2)   NULL,
    [b_zip]     CHAR (10)  NULL,
    [b_phone]   CHAR (14)  NULL,
    [b_fax]     CHAR (14)  NULL,
    [clia]      CHAR (15)  NULL,
    [nation]    CHAR (20)  NULL,
    [b_country] CHAR (20)  NULL,
    [email]     CHAR (100) NULL,
    [note]      TEXT       NULL,
    [homehtml]  CHAR (100) NULL,
    [lap]       CHAR (12)  NULL,
    [link]      INT        NULL,
    [dr_id]     CHAR (12)  NULL
);

