CREATE TABLE [dbo].[EWageTax] (
    [WtxMagic]            INT             NULL,
    [WtxFlxIDEb]          INT             NULL,
    [WtxFlxIDP2]          INT             NULL,
    [WtxCRC]              INT             NULL,
    [WtxSource]           INT             NULL,
    [WtxNote]             INT             NULL,
    [WtxFlxID]            INT             NOT NULL,
    [WtxDateAdd]          DATETIME        NULL,
    [WtxDateMod]          DATETIME        NULL,
    [WtxDateDel]          DATETIME        NULL,
    [WtxDateBeg]          DATETIME        NULL,
    [WtxDateEnd]          DATETIME        NULL,
    [WtxDateRBeg]         DATETIME        NULL,
    [WtxDateREnd]         DATETIME        NULL,
    [WtxUserName]         VARCHAR (20)    NULL,
    [WtxRecType]          VARCHAR (4)     NULL,
    [WtxArchive]          VARCHAR (1)     NULL,
    [WtxCalculatedAddl]   DECIMAL (19, 2) NULL,
    [WtxCurrFicaTaxes]    DECIMAL (19, 2) NULL,
    [WtxCurrFicaWages]    DECIMAL (19, 2) NULL,
    [WtxCurrFitTaxes]     DECIMAL (19, 2) NULL,
    [WtxCurrFitWages]     DECIMAL (19, 2) NULL,
    [WtxCurrGrossWages]   DECIMAL (19, 2) NULL,
    [WtxCurrLocalTaxes]   DECIMAL (19, 2) NULL,
    [WtxCurrLocalWages]   DECIMAL (19, 2) NULL,
    [WtxCurrMedTaxes]     DECIMAL (19, 2) NULL,
    [WtxCurrMedWages]     DECIMAL (19, 2) NULL,
    [WtxCurrNetPay]       DECIMAL (19, 2) NULL,
    [WtxCurrSdiTaxes]     DECIMAL (19, 2) NULL,
    [WtxCurrSdiWages]     DECIMAL (19, 2) NULL,
    [WtxCurrSocTaxes]     DECIMAL (19, 2) NULL,
    [WtxCurrSocWages]     DECIMAL (19, 2) NULL,
    [WtxCurrStateTaxes]   DECIMAL (19, 2) NULL,
    [WtxCurrStateWages]   DECIMAL (19, 2) NULL,
    [WtxCurrVolDeds]      DECIMAL (19, 2) NULL,
    [WtxManualCounter]    INT             NULL,
    [WtxMpFin11]          DECIMAL (19, 2) NULL,
    [WtxNetPay]           DECIMAL (19, 2) NULL,
    [WtxPayEnding]        DATETIME        NULL,
    [WtxPeriodDataTransl] VARCHAR (5)     NULL,
    [WtxPSID]             VARCHAR (8)     NULL,
    [WtxFica]             DECIMAL (19, 2) NULL,
    [WtxQtdFicaTaxes]     DECIMAL (19, 2) NULL,
    [WtxQtdFicaWages]     DECIMAL (19, 2) NULL,
    [WtxQtdFitTaxes]      DECIMAL (19, 2) NULL,
    [WtxQtdFitWages]      DECIMAL (19, 2) NULL,
    [WtxQtdGrossWages]    DECIMAL (19, 2) NULL,
    [WtxQtdLocalTaxes]    DECIMAL (19, 2) NULL,
    [WtxQtdLocalWages]    DECIMAL (19, 2) NULL,
    [WtxQtdMedTaxes]      DECIMAL (19, 2) NULL,
    [WtxQtdMedWages]      DECIMAL (19, 2) NULL,
    [WtxQtdNetPay]        DECIMAL (19, 2) NULL,
    [WtxQtdSdiTaxes]      DECIMAL (19, 2) NULL,
    [WtxQtdSdiWages]      DECIMAL (19, 2) NULL,
    [WtxQtdSocTAxes]      DECIMAL (19, 2) NULL,
    [WtxQtdSocWages]      DECIMAL (19, 2) NULL,
    [WtxQtdStateTaxes]    DECIMAL (19, 2) NULL,
    [WtxQtdStateWages]    DECIMAL (19, 2) NULL,
    [WtxQtdVolDeds]       DECIMAL (19, 2) NULL,
    [WtxVoidCounter]      INT             NULL,
    [WtxYtdFicaTaxes]     DECIMAL (19, 2) NULL,
    [WtxYtdFicaWages]     DECIMAL (19, 2) NULL,
    [WtxYtdFitTaxes]      DECIMAL (19, 2) NULL,
    [WtxYtdFitWages]      DECIMAL (19, 2) NULL,
    [WtxYtdFutaWages]     DECIMAL (19, 2) NULL,
    [WtxYtdGrossWages]    DECIMAL (19, 2) NULL,
    [WtxYtdLocalTaxes]    DECIMAL (19, 2) NULL,
    [WtxYtdLocalWages]    DECIMAL (19, 2) NULL,
    [WtxYtdMedTaxes]      DECIMAL (10, 2) NULL,
    [WtxYtdMedWages]      DECIMAL (19, 2) NULL,
    [WtxYtdNetPay]        DECIMAL (19, 2) NULL,
    [WtxYtdSdiTaxes]      DECIMAL (19, 2) NULL,
    [WtxYtdSdiWages]      DECIMAL (19, 2) NULL,
    [WtxYtdSocTAxes]      DECIMAL (19, 2) NULL,
    [WtxYtdSocWages]      DECIMAL (19, 2) NULL,
    [WtxYtdStateTaxes]    DECIMAL (19, 2) NULL,
    [WtxYtdStateWages]    DECIMAL (19, 2) NULL,
    [WtxYtdVolDeds]       DECIMAL (19, 2) NULL,
    [WtxUpsize_ts]        BINARY (8)      NULL
);

