CREATE TABLE [dbo].[LawsonEMPCODES] (
    [COMPANY]       SMALLINT        NOT NULL,
    [TYPE]          CHAR (2)        NOT NULL,
    [EMP_APP]       TINYINT         NOT NULL,
    [EMPLOYEE]      INT             NOT NULL,
    [CODE]          CHAR (10)       NOT NULL,
    [SUBJECT]       CHAR (10)       NOT NULL,
    [SEQ_NBR]       SMALLINT        NOT NULL,
    [DATE_ACQUIRED] DATETIME        NOT NULL,
    [RENEW_DATE]    DATETIME        NOT NULL,
    [PER_RATING]    DECIMAL (5, 2)  NOT NULL,
    [INSTRUCTOR]    CHAR (10)       NOT NULL,
    [CO_SPONSORED]  CHAR (1)        NOT NULL,
    [IN_PRO_FLAG]   CHAR (1)        NOT NULL,
    [LIC_NUMBER]    CHAR (20)       NOT NULL,
    [COST]          DECIMAL (11, 2) NOT NULL,
    [RENEWAL_CODE]  CHAR (2)        NOT NULL,
    [COMPONENT]     SMALLINT        NOT NULL,
    [PROP_VALUE]    DECIMAL (15, 2) NOT NULL,
    [PA_ASSET_NBR]  CHAR (9)        NOT NULL,
    [DATE_RETURNED] DATETIME        NOT NULL,
    [VERIFIED_FLAG] CHAR (1)        NOT NULL,
    [PRIORITY_CODE] TINYINT         NOT NULL,
    [SKILL_SOURCE]  CHAR (10)       NOT NULL,
    [PROFIC_LEVEL]  CHAR (10)       NOT NULL,
    [OBJ_ID]        DECIMAL (12)    NOT NULL,
    [CURRENCY_CODE] CHAR (5)        NOT NULL,
    [CURR_ND]       TINYINT         NOT NULL,
    [BASE_AMOUNT]   DECIMAL (15, 2) NOT NULL,
    [BASE_CURRENCY] CHAR (5)        NOT NULL,
    [BASE_ND]       TINYINT         NOT NULL,
    [DATE_STAMP]    DATETIME        NOT NULL,
    [TIME_STAMP]    DECIMAL (6)     NOT NULL,
    [USER_ID]       CHAR (10)       NOT NULL,
    [STATE]         CHAR (2)        NOT NULL,
    [DESCRIPTION]   CHAR (30)       NOT NULL,
    [L_INDEX]       CHAR (4)        NOT NULL,
    [EPCSET3_SS_SW] CHAR (1)        NOT NULL,
    [EPCSET4_SS_SW] CHAR (1)        NOT NULL,
    [EPCSET5_SS_SW] CHAR (1)        NOT NULL,
    [EPCSET6_SS_SW] CHAR (1)        NOT NULL,
    [EPCSET7_SS_SW] CHAR (1)        NOT NULL,
    [L_ATEPC_SS_SW] CHAR (1)        NOT NULL
);

