CREATE TABLE [dbo].[LawsonDEPTCODE] (
    [COMPANY]       SMALLINT    NOT NULL,
    [PROCESS_LEVEL] CHAR (5)    NOT NULL,
    [DEPARTMENT]    CHAR (5)    NOT NULL,
    [NAME]          CHAR (30)   NOT NULL,
    [DEP_DIST_CO]   SMALLINT    NOT NULL,
    [DEP_ACCT_UNIT] CHAR (15)   NOT NULL,
    [DEP_ACCOUNT]   INT         NOT NULL,
    [DEP_SUB_ACCT]  SMALLINT    NOT NULL,
    [SEC_LVL]       TINYINT     NOT NULL,
    [SEC_LOCATION]  CHAR (10)   NOT NULL,
    [SEGMENT_FLAG]  CHAR (1)    NOT NULL,
    [ACTIVE_FLAG]   CHAR (1)    NOT NULL,
    [USER_ID]       CHAR (10)   NOT NULL,
    [DATE_STAMP]    DATETIME    NOT NULL,
    [TIME_STAMP]    DECIMAL (6) NOT NULL
);

