CREATE TABLE [dbo].[LawsonPAEMPLOYEE] (
    [COMPANY]          SMALLINT        NOT NULL,
    [EMPLOYEE]         INT             NOT NULL,
    [SUPP_ADDR1]       CHAR (30)       NOT NULL,
    [SUPP_ADDR2]       CHAR (30)       NOT NULL,
    [SUPP_ADDR3]       CHAR (30)       NOT NULL,
    [SUPP_ADDR4]       CHAR (30)       NOT NULL,
    [SUPP_CITY]        CHAR (18)       NOT NULL,
    [SUPP_STATE]       CHAR (2)        NOT NULL,
    [SUPP_ZIP]         CHAR (10)       NOT NULL,
    [SUPP_CNTRY_CD]    CHAR (2)        NOT NULL,
    [HM_PHONE_CNTRY]   CHAR (6)        NOT NULL,
    [HM_PHONE_NBR]     CHAR (15)       NOT NULL,
    [WK_PHONE_CNTRY]   CHAR (6)        NOT NULL,
    [WK_PHONE_NBR]     CHAR (15)       NOT NULL,
    [WK_PHONE_EXT]     CHAR (5)        NOT NULL,
    [EEO_CLASS]        CHAR (4)        NOT NULL,
    [SEX]              CHAR (1)        NOT NULL,
    [HANDICAP_ID]      CHAR (1)        NOT NULL,
    [COMP_CODE]        CHAR (4)        NOT NULL,
    [COMP_NBR]         CHAR (10)       NOT NULL,
    [VETERAN]          CHAR (4)        NOT NULL,
    [BIRTHDATE]        DATETIME        NOT NULL,
    [BIRTH_CITY]       CHAR (18)       NOT NULL,
    [BIRTH_STATE]      CHAR (2)        NOT NULL,
    [BIRTH_CNTRY_CD]   CHAR (2)        NOT NULL,
    [SENIOR_DATE]      DATETIME        NOT NULL,
    [MAIDEN_LST_NM]    CHAR (30)       NOT NULL,
    [MAIDEN_FST_NM]    CHAR (15)       NOT NULL,
    [MAIDEN_MI]        CHAR (1)        NOT NULL,
    [FORMER_LST_NM]    CHAR (30)       NOT NULL,
    [FORMER_FST_NM]    CHAR (15)       NOT NULL,
    [FORMER_MI]        CHAR (1)        NOT NULL,
    [LOCAT_CODE]       CHAR (10)       NOT NULL,
    [HIRE_SOURCE]      CHAR (10)       NOT NULL,
    [SECURITY_CODE]    CHAR (10)       NOT NULL,
    [SECURITY_NBR]     CHAR (10)       NOT NULL,
    [BARGAIN_UNIT]     CHAR (10)       NOT NULL,
    [CLOCK_NBR]        CHAR (10)       NOT NULL,
    [MAIL_GROUP]       CHAR (10)       NOT NULL,
    [MB_NBR]           CHAR (10)       NOT NULL,
    [DRAFT_STATUS]     CHAR (3)        NOT NULL,
    [FINAL_RANK]       CHAR (3)        NOT NULL,
    [CUR_STATUS]       CHAR (2)        NOT NULL,
    [LAST_PHYSICAL]    DATETIME        NOT NULL,
    [PHY_SCHD]         CHAR (2)        NOT NULL,
    [NEXT_PHYSICAL]    DATETIME        NOT NULL,
    [HEIGHT_FT]        SMALLINT        NOT NULL,
    [HEIGHT_IN]        SMALLINT        NOT NULL,
    [WGHT]             DECIMAL (5, 2)  NOT NULL,
    [BLOOD_TYPE]       CHAR (3)        NOT NULL,
    [PARKING_LOT]      CHAR (10)       NOT NULL,
    [PARKING_SPACE]    CHAR (10)       NOT NULL,
    [DR_LICENSE]       CHAR (20)       NOT NULL,
    [DR_LIC_ST]        CHAR (2)        NOT NULL,
    [EXP_DATE]         DATETIME        NOT NULL,
    [DR_LIC_CLASS]     CHAR (3)        NOT NULL,
    [REV_SCHEDULE]     CHAR (2)        NOT NULL,
    [NEXT_REVIEW]      DATETIME        NOT NULL,
    [NEXT_REV_CODE]    CHAR (10)       NOT NULL,
    [LAST_REVIEW]      DATETIME        NOT NULL,
    [LAST_MIL_SEQ]     SMALLINT        NOT NULL,
    [LAST_REV_SEQ]     SMALLINT        NOT NULL,
    [LAST_COM_SEQ]     SMALLINT        NOT NULL,
    [LAST_INT_SEQ]     SMALLINT        NOT NULL,
    [LAST_BNF_SEQ]     SMALLINT        NOT NULL,
    [LAST_INV_NBR]     SMALLINT        NOT NULL,
    [LAST_EPC_SEQ]     SMALLINT        NOT NULL,
    [FNCTN_GROUP]      SMALLINT        NOT NULL,
    [EXCLUDE_FLAG]     CHAR (1)        NOT NULL,
    [NBR_HL_DEP]       SMALLINT        NOT NULL,
    [NBR_DN_DEP]       SMALLINT        NOT NULL,
    [LIFE_STYLE_CR]    SMALLINT        NOT NULL,
    [HL_COV_PROOF]     CHAR (1)        NOT NULL,
    [DN_COV_PROOF]     CHAR (1)        NOT NULL,
    [HL_VERIFY_DT]     DATETIME        NOT NULL,
    [DN_VERIFY_DT]     DATETIME        NOT NULL,
    [SPOUSE_EMP]       CHAR (30)       NOT NULL,
    [SP_EMP_ADDR1]     CHAR (30)       NOT NULL,
    [SP_EMP_ADDR2]     CHAR (30)       NOT NULL,
    [SP_EMP_ADDR3]     CHAR (30)       NOT NULL,
    [SP_EMP_ADDR4]     CHAR (30)       NOT NULL,
    [SP_EMP_CITY]      CHAR (18)       NOT NULL,
    [SP_EMP_STATE]     CHAR (2)        NOT NULL,
    [SP_EMP_ZIP]       CHAR (10)       NOT NULL,
    [SP_EMP_COUNTRY]   CHAR (2)        NOT NULL,
    [SP_EMP_PH_CNTR]   CHAR (6)        NOT NULL,
    [SP_EMP_PH_NBR]    CHAR (15)       NOT NULL,
    [OWNER_FLAG]       CHAR (1)        NOT NULL,
    [KEY_EMP_FLAG]     CHAR (1)        NOT NULL,
    [OFFICER]          CHAR (1)        NOT NULL,
    [HIGH_COMP]        CHAR (1)        NOT NULL,
    [SMOKER]           CHAR (1)        NOT NULL,
    [I9_STATUS]        CHAR (10)       NOT NULL,
    [I9_ALIEN_NBR]     CHAR (11)       NOT NULL,
    [I9_ADMIT_NBR]     CHAR (13)       NOT NULL,
    [I9_STA_EXP_DT]    DATETIME        NOT NULL,
    [I9_DOC_NBR_01]    CHAR (20)       NOT NULL,
    [I9_DOC_NBR_02]    CHAR (20)       NOT NULL,
    [I9_DOC_TYPE_01]   CHAR (10)       NOT NULL,
    [I9_DOC_TYPE_02]   CHAR (10)       NOT NULL,
    [I9_DOC_EXP_DT_01] DATETIME        NOT NULL,
    [I9_DOC_EXP_DT_02] DATETIME        NOT NULL,
    [I9_AUTHORIZE]     CHAR (30)       NOT NULL,
    [TRUE_MAR_STAT]    CHAR (1)        NOT NULL,
    [LAST_PAE_SEQ]     SMALLINT        NOT NULL,
    [PRIMARY_CARE]     CHAR (10)       NOT NULL,
    [FAMILY_AGG]       INT             NOT NULL,
    [BEN_SALARY_1]     DECIMAL (11, 2) NOT NULL,
    [BEN_SALARY_2]     DECIMAL (11, 2) NOT NULL,
    [BEN_SALARY_3]     DECIMAL (11, 2) NOT NULL,
    [BEN_SALARY_4]     DECIMAL (11, 2) NOT NULL,
    [BEN_SALARY_5]     DECIMAL (11, 2) NOT NULL,
    [BEN_DATE_1]       DATETIME        NOT NULL,
    [BEN_DATE_2]       DATETIME        NOT NULL,
    [BEN_DATE_3]       DATETIME        NOT NULL,
    [BEN_DATE_4]       DATETIME        NOT NULL,
    [BEN_DATE_5]       DATETIME        NOT NULL,
    [SEC_LVL]          TINYINT         NOT NULL,
    [SEC_LOCATION]     CHAR (10)       NOT NULL,
    [WORK_ZIP]         CHAR (10)       NOT NULL,
    [HEIGHT_UNIT]      CHAR (1)        NOT NULL,
    [WGHT_UNIT]        CHAR (1)        NOT NULL,
    [LANGUAGE_CODE]    CHAR (10)       NOT NULL,
    [RELIGION]         CHAR (10)       NOT NULL,
    [DISABILITY]       CHAR (10)       NOT NULL,
    [SUPP_PHONE_CNT]   CHAR (6)        NOT NULL,
    [SUPP_PHONE_NBR]   CHAR (15)       NOT NULL,
    [CONSENT]          CHAR (1)        NOT NULL,
    [ABORIGINAL]       CHAR (1)        NOT NULL,
    [VISIBLE_MIN]      CHAR (1)        NOT NULL,
    [RELATED_EMP]      CHAR (1)        NOT NULL,
    [I9_DOC_DESCR_01]  CHAR (10)       NOT NULL,
    [I9_DOC_DESCR_02]  CHAR (10)       NOT NULL,
    [BILINGUAL]        CHAR (1)        NOT NULL,
    [SUPP_COUNTY]      CHAR (25)       NOT NULL,
    [STOCK_TRADE]      CHAR (1)        NOT NULL,
    [DATE_ASSIGN]      DATETIME        NOT NULL,
    [USER_AMOUNT]      DECIMAL (13, 4) NOT NULL,
    [ESTAB_PATIENT]    TINYINT         NOT NULL,
    [PRIOR_COV_MO]     SMALLINT        NOT NULL,
    [MEDICARE_IND]     CHAR (1)        NOT NULL,
    [L_INDEX]          CHAR (4)        NOT NULL,
    [L_ATPEM_SS_SW]    CHAR (1)        NOT NULL
);

