CREATE TABLE [dbo].[LawsonMbsiTurnover] (
    [yrmth]                  VARCHAR (61)    NULL,
    [employee]               INT             NOT NULL,
    [emp_name]               VARCHAR (47)    NULL,
    [locat_code]             CHAR (10)       NOT NULL,
    [location]               CHAR (30)       NULL,
    [department]             CHAR (5)        NOT NULL,
    [dept_name]              CHAR (30)       NOT NULL,
    [job_code]               CHAR (9)        NOT NULL,
    [R_Position]             CHAR (12)       NOT NULL,
    [supervisor]             CHAR (10)       NOT NULL,
    [date_hired]             VARCHAR (30)    NULL,
    [salary_class]           CHAR (1)        NOT NULL,
    [exempt_emp]             CHAR (1)        NOT NULL,
    [term_date]              VARCHAR (30)    NULL,
    [reason_01]              CHAR (10)       NULL,
    [reason_02]              CHAR (10)       NULL,
    [fte_total]              DECIMAL (11, 6) NOT NULL,
    [emp_status]             CHAR (2)        NOT NULL,
    [sex]                    CHAR (1)        NOT NULL,
    [eeo_class]              CHAR (8)        NOT NULL,
    [birthdate]              VARCHAR (30)    NULL,
    [LOS_current_months]     INT             NULL,
    [LOS_current_years]      INT             NULL,
    [LOS_group]              VARCHAR (7)     NOT NULL,
    [LOS_term_months]        INT             NULL,
    [LOS_term_years]         INT             NULL,
    [Age_current]            INT             NULL,
    [LOS_AgeGroup]           VARCHAR (7)     NOT NULL,
    [Age_hired]              INT             NULL,
    [Age_termed]             INT             NULL,
    [newHire_flag]           VARCHAR (1)     NOT NULL,
    [active_nonNewHire_flag] VARCHAR (1)     NOT NULL,
    [termed_flag]            VARCHAR (1)     NOT NULL,
    [CreDate]                DATETIME        NOT NULL
);

