CREATE TABLE [dbo].[LawsonPGEMPLOYEE] (
    [COMPANY]     SMALLINT  NOT NULL,
    [GROUP_NAME]  CHAR (10) NOT NULL,
    [EMPLOYEE]    INT       NOT NULL,
    [LAST_NAME]   CHAR (30) NOT NULL,
    [FIRST_NAME]  CHAR (15) NOT NULL,
    [MIDDLE_INIT] CHAR (1)  NOT NULL
);

