CREATE TABLE [dbo].[LawsonPERSACTION] (
    [COMPANY]        SMALLINT        NOT NULL,
    [ACTION_TYPE]    CHAR (1)        NOT NULL,
    [EFFECT_DATE]    DATETIME        NOT NULL,
    [ACTION_CODE]    CHAR (10)       NOT NULL,
    [EMPLOYEE]       INT             NOT NULL,
    [ANT_END_DATE]   DATETIME        NOT NULL,
    [ACTION_NBR]     SMALLINT        NOT NULL,
    [PROCESS_LEVEL]  CHAR (5)        NOT NULL,
    [DEPARTMENT]     CHAR (5)        NOT NULL,
    [USER_LEVEL]     CHAR (10)       NOT NULL,
    [LOCAT_CODE]     CHAR (10)       NOT NULL,
    [SUPERVISOR]     CHAR (10)       NOT NULL,
    [UNION_CODE]     CHAR (10)       NOT NULL,
    [PERS_GROUP]     CHAR (10)       NOT NULL,
    [REASON_01]      CHAR (10)       NOT NULL,
    [REASON_02]      CHAR (10)       NOT NULL,
    [FLD_NBR_01]     SMALLINT        NOT NULL,
    [FLD_NBR_02]     SMALLINT        NOT NULL,
    [FLD_NBR_03]     SMALLINT        NOT NULL,
    [FLD_NBR_04]     SMALLINT        NOT NULL,
    [FLD_NBR_05]     SMALLINT        NOT NULL,
    [FLD_NBR_06]     SMALLINT        NOT NULL,
    [FLD_NBR_07]     SMALLINT        NOT NULL,
    [FLD_NBR_08]     SMALLINT        NOT NULL,
    [FLD_NBR_09]     SMALLINT        NOT NULL,
    [FLD_NBR_10]     SMALLINT        NOT NULL,
    [FLD_NBR_11]     SMALLINT        NOT NULL,
    [FLD_NBR_12]     SMALLINT        NOT NULL,
    [FLD_NBR_13]     SMALLINT        NOT NULL,
    [FLD_NBR_14]     SMALLINT        NOT NULL,
    [FLD_NBR_15]     SMALLINT        NOT NULL,
    [FLD_NBR_16]     SMALLINT        NOT NULL,
    [FLD_NBR_17]     SMALLINT        NOT NULL,
    [FLD_NBR_18]     SMALLINT        NOT NULL,
    [FLD_NBR_19]     SMALLINT        NOT NULL,
    [FLD_NBR_20]     SMALLINT        NOT NULL,
    [FLD_NBR_21]     SMALLINT        NOT NULL,
    [FLD_NBR_22]     SMALLINT        NOT NULL,
    [FLD_NBR_23]     SMALLINT        NOT NULL,
    [FLD_NBR_24]     SMALLINT        NOT NULL,
    [FLD_NBR_25]     SMALLINT        NOT NULL,
    [FLD_NBR_26]     SMALLINT        NOT NULL,
    [FLD_NBR_27]     SMALLINT        NOT NULL,
    [FLD_NBR_28]     SMALLINT        NOT NULL,
    [FLD_NBR_29]     SMALLINT        NOT NULL,
    [FLD_NBR_30]     SMALLINT        NOT NULL,
    [FLD_NBR_31]     SMALLINT        NOT NULL,
    [FLD_NBR_32]     SMALLINT        NOT NULL,
    [FLD_NBR_33]     SMALLINT        NOT NULL,
    [FLD_NBR_34]     SMALLINT        NOT NULL,
    [FLD_NBR_35]     SMALLINT        NOT NULL,
    [FLD_NBR_36]     SMALLINT        NOT NULL,
    [NEW_VALUE_01]   CHAR (30)       NOT NULL,
    [NEW_VALUE_02]   CHAR (30)       NOT NULL,
    [NEW_VALUE_03]   CHAR (30)       NOT NULL,
    [NEW_VALUE_04]   CHAR (30)       NOT NULL,
    [NEW_VALUE_05]   CHAR (30)       NOT NULL,
    [NEW_VALUE_06]   CHAR (30)       NOT NULL,
    [NEW_VALUE_07]   CHAR (30)       NOT NULL,
    [NEW_VALUE_08]   CHAR (30)       NOT NULL,
    [NEW_VALUE_09]   CHAR (30)       NOT NULL,
    [NEW_VALUE_10]   CHAR (30)       NOT NULL,
    [NEW_VALUE_11]   CHAR (30)       NOT NULL,
    [NEW_VALUE_12]   CHAR (30)       NOT NULL,
    [NEW_VALUE_13]   CHAR (30)       NOT NULL,
    [NEW_VALUE_14]   CHAR (30)       NOT NULL,
    [NEW_VALUE_15]   CHAR (30)       NOT NULL,
    [NEW_VALUE_16]   CHAR (30)       NOT NULL,
    [NEW_VALUE_17]   CHAR (30)       NOT NULL,
    [NEW_VALUE_18]   CHAR (30)       NOT NULL,
    [NEW_VALUE_19]   CHAR (30)       NOT NULL,
    [NEW_VALUE_20]   CHAR (30)       NOT NULL,
    [NEW_VALUE_21]   CHAR (30)       NOT NULL,
    [NEW_VALUE_22]   CHAR (30)       NOT NULL,
    [NEW_VALUE_23]   CHAR (30)       NOT NULL,
    [NEW_VALUE_24]   CHAR (30)       NOT NULL,
    [NEW_VALUE_25]   CHAR (30)       NOT NULL,
    [NEW_VALUE_26]   CHAR (30)       NOT NULL,
    [NEW_VALUE_27]   CHAR (30)       NOT NULL,
    [NEW_VALUE_28]   CHAR (30)       NOT NULL,
    [NEW_VALUE_29]   CHAR (30)       NOT NULL,
    [NEW_VALUE_30]   CHAR (30)       NOT NULL,
    [NEW_VALUE_31]   CHAR (30)       NOT NULL,
    [NEW_VALUE_32]   CHAR (30)       NOT NULL,
    [NEW_VALUE_33]   CHAR (30)       NOT NULL,
    [NEW_VALUE_34]   CHAR (30)       NOT NULL,
    [NEW_VALUE_35]   CHAR (30)       NOT NULL,
    [NEW_VALUE_36]   CHAR (30)       NOT NULL,
    [SALARY_CLASS]   CHAR (1)        NOT NULL,
    [PCT_PAY_INC]    DECIMAL (7, 3)  NOT NULL,
    [ROUND_EVEN]     DECIMAL (9, 4)  NOT NULL,
    [PCT_PAY_DEC]    DECIMAL (7, 3)  NOT NULL,
    [ROUND_OPT]      CHAR (1)        NOT NULL,
    [FLAT_INC]       DECIMAL (13, 4) NOT NULL,
    [FLAT_DEC]       DECIMAL (13, 4) NOT NULL,
    [NEW_RATE]       DECIMAL (13, 4) NOT NULL,
    [USER_ID]        CHAR (10)       NOT NULL,
    [PARTICIPNT]     INT             NOT NULL,
    [OCCUR_TYPE]     CHAR (2)        NOT NULL,
    [UPDATE_BENEFIT] CHAR (1)        NOT NULL,
    [POS_LEVEL]      SMALLINT        NOT NULL,
    [POS_EFF_DT]     DATETIME        NOT NULL,
    [R_POSITION]     CHAR (12)       NOT NULL,
    [REQUISITION]    INT             NOT NULL,
    [JOB_CODE]       CHAR (9)        NOT NULL,
    [PAY_POSITION]   CHAR (12)       NOT NULL,
    [UPDATE_REQ_DED] CHAR (1)        NOT NULL,
    [EDM_EFFECT_DT]  DATETIME        NOT NULL,
    [EDM_END_DATE]   DATETIME        NOT NULL,
    [APPROVAL_FLAG]  CHAR (1)        NOT NULL,
    [BASE_CURRENCY]  CHAR (5)        NOT NULL,
    [BASE_ND]        TINYINT         NOT NULL,
    [BASE_PAY_RATE]  DECIMAL (13, 4) NOT NULL,
    [MERGE_ACTN_NBR] SMALLINT        NOT NULL,
    [HIST_CORR_FLAG] CHAR (2)        NOT NULL,
    [PROCESS_TYPE]   CHAR (2)        NOT NULL,
    [POS_LEVEL_MOVE] SMALLINT        NOT NULL,
    [UPD_ABS_MGMT]   CHAR (1)        NOT NULL,
    [L_INDEX]        CHAR (4)        NOT NULL,
    [L_ATPCT_SS_SW]  CHAR (1)        NOT NULL
);

