CREATE TABLE [dbo].[LawsonPAhrhChanges] (
    [DATE_STAMP]      DATETIME        NULL,
    [Beg_date]        DATETIME        NULL,
    [LAST_NAME]       CHAR (30)       NOT NULL,
    [FIRST_NAME]      CHAR (15)       NOT NULL,
    [DESCRIPTION]     CHAR (30)       NOT NULL,
    [job_description] CHAR (30)       NOT NULL,
    [site_name]       CHAR (30)       NOT NULL,
    [ACTION_CODE]     CHAR (10)       NULL,
    [ITEM_NAME]       CHAR (20)       NULL,
    [PERS_ACTION]     CHAR (1)        NULL,
    [FLD_NBR]         SMALLINT        NULL,
    [SEQ_NBR]         SMALLINT        NULL,
    [N_VALUE]         DECIMAL (15, 6) NULL,
    [A_VALUE]         CHAR (30)       NULL,
    [D_VALUE]         DATETIME        NULL,
    [PAY_RATE]        DECIMAL (13, 4) NOT NULL,
    [FTE]             DECIMAL (11, 6) NOT NULL,
    [job_code]        CHAR (9)        NOT NULL,
    [r_position]      CHAR (12)       NOT NULL,
    [EMPLOYEE]        INT             NOT NULL,
    [OBJ_ID]          DECIMAL (12)    NULL,
    [ACTION_NBR]      SMALLINT        NULL,
    [process_level]   CHAR (5)        NOT NULL,
    [POS_LEVEL]       SMALLINT        NOT NULL,
    [department]      CHAR (5)        NOT NULL,
    [REASON_01]       CHAR (10)       NULL,
    [REASON_02]       CHAR (10)       NULL,
    [EMP_STATUS]      CHAR (2)        NOT NULL,
    [DATE_HIRED]      DATETIME        NOT NULL,
    [TERM_DATE]       DATETIME        NOT NULL,
    [EFFECT_DATE]     DATETIME        NOT NULL,
    [END_DATE]        DATETIME        NOT NULL,
    [POS_EFF_DT]      DATETIME        NOT NULL,
    [ANT_END_DATE]    DATETIME        NULL,
    [BEN_DATE_1]      DATETIME        NULL,
    [BEN_DATE_2]      DATETIME        NULL,
    [lastRunDate]     DATETIME        NOT NULL
);

