CREATE TABLE [dbo].[LawsonMedAmericaTurnover] (
    [yrmth]                  VARCHAR (61)    NOT NULL,
    [employee]               INT             NOT NULL,
    [emp_name]               VARCHAR (47)    NULL,
    [department]             VARCHAR (10)    NULL,
    [dept_name]              VARCHAR (50)    NULL,
    [job_code]               VARCHAR (15)    NULL,
    [R_Position]             VARCHAR (15)    NULL,
    [supervisor]             VARCHAR (12)    NULL,
    [date_hired]             VARCHAR (30)    NULL,
    [salary_class]           CHAR (1)        NOT NULL,
    [exempt_emp]             CHAR (1)        NOT NULL,
    [term_date]              VARCHAR (30)    NULL,
    [reason_01]              VARCHAR (20)    NULL,
    [reason_02]              VARCHAR (20)    NULL,
    [fte_total]              DECIMAL (11, 6) NOT NULL,
    [emp_status]             CHAR (2)        NOT NULL,
    [emp_name_status]        VARCHAR (255)   NULL,
    [sex]                    CHAR (1)        NULL,
    [eeo_class]              VARCHAR (15)    NULL,
    [birthdate]              VARCHAR (30)    NULL,
    [LOS_current_months]     INT             NULL,
    [LOS_current_years]      INT             NULL,
    [LOS_group]              VARCHAR (15)    NULL,
    [LOS_term_months]        INT             NULL,
    [LOS_term_years]         INT             NULL,
    [Age_current]            INT             NULL,
    [LOS_AgeGroup]           VARCHAR (10)    NULL,
    [Age_hired]              INT             NULL,
    [Age_termed]             INT             NULL,
    [newHire_flag]           VARCHAR (1)     NOT NULL,
    [active_nonNewHire_flag] VARCHAR (1)     NOT NULL,
    [termed_flag]            VARCHAR (1)     NOT NULL,
    [CreDate]                DATETIME        NOT NULL
);

