CREATE TABLE [dbo].[SFDCMalPracStaging] (
    [Address__c]           NVARCHAR (1300) NULL,
    [Carrier__c]           NCHAR (18)      NULL,
    [Comments__c]          NVARCHAR (255)  NULL,
    [ConnectionReceivedId] NCHAR (18)      NULL,
    [ConnectionSentId]     NCHAR (18)      NULL,
    [Contact__c]           NCHAR (18)      NULL,
    [Coverage_Range2__c]   NVARCHAR (255)  NULL,
    [Coverage_Range__c]    NVARCHAR (255)  NULL,
    [CreatedById]          NCHAR (18)      NULL,
    [CreatedDate]          DATETIME2 (7)   NOT NULL,
    [Enrolled_Date__c]     DATETIME2 (7)   NULL,
    [Expiration_Date__c]   DATETIME2 (7)   NULL,
    [Fax__c]               NVARCHAR (40)   NULL,
    [Id]                   NCHAR (18)      NOT NULL,
    [IsDeleted]            VARCHAR (5)     NOT NULL,
    [LastActivityDate]     DATETIME2 (7)   NULL,
    [LastModifiedById]     NCHAR (18)      NULL,
    [LastModifiedDate]     DATETIME2 (7)   NOT NULL,
    [LastReferencedDate]   DATETIME2 (7)   NULL,
    [LastViewedDate]       DATETIME2 (7)   NULL,
    [Malpract_Address__c]  NVARCHAR (1300) NULL,
    [Malpract_City__c]     NVARCHAR (1300) NULL,
    [Malpract_Fax__c]      NVARCHAR (1300) NULL,
    [Malpract_Phone__c]    NVARCHAR (1300) NULL,
    [Malpract_State__c]    NVARCHAR (1300) NULL,
    [Malpract_Suite__c]    NVARCHAR (1300) NULL,
    [Malpract_Zip__c]      NVARCHAR (1300) NULL,
    [Malpractice_Type__c]  NVARCHAR (255)  NULL,
    [Name]                 NVARCHAR (80)   NULL,
    [Policy_Number__c]     NVARCHAR (255)  NULL,
    [Private__c]           VARCHAR (5)     NULL,
    [Site__c]              NCHAR (18)      NULL,
    [SystemModstamp]       DATETIME2 (7)   NOT NULL,
    [Tail__c]              VARCHAR (5)     NULL,
    [Telephone__c]         NVARCHAR (40)   NULL
);

