CREATE TABLE [dbo].[SFDCPartHistoryStaging] (
    [Board_Approval_Date__c]           DATETIME2 (7)   NULL,
    [Case_Information__c]              NTEXT           NULL,
    [Comments__c]                      NTEXT           NULL,
    [Completed_Date__c]                DATETIME2 (7)   NULL,
    [ConnectionReceivedId]             NCHAR (18)      NULL,
    [ConnectionSentId]                 NCHAR (18)      NULL,
    [Contact__c]                       NCHAR (18)      NULL,
    [CPAC_Approval_Date__c]            DATETIME2 (7)   NULL,
    [CreatedById]                      NCHAR (18)      NULL,
    [CreatedDate]                      DATETIME2 (7)   NOT NULL,
    [Entity__c]                        NVARCHAR (255)  NULL,
    [Flagged_by__c]                    NVARCHAR (1300) NULL,
    [From__c]                          DATETIME2 (7)   NULL,
    [Hired_Date__c]                    DATETIME2 (7)   NULL,
    [Id]                               NCHAR (18)      NOT NULL,
    [Intervention_Description__c]      NVARCHAR (255)  NULL,
    [Intervention_Due_Date__c]         DATETIME2 (7)   NULL,
    [Interventions_Completed__c]       NVARCHAR (255)  NULL,
    [IsDeleted]                        VARCHAR (5)     NOT NULL,
    [LastActivityDate]                 DATETIME2 (7)   NULL,
    [LastModifiedById]                 NCHAR (18)      NULL,
    [LastModifiedDate]                 DATETIME2 (7)   NOT NULL,
    [LastReferencedDate]               DATETIME2 (7)   NULL,
    [LastViewedDate]                   DATETIME2 (7)   NULL,
    [Letter_Sent__c]                   DATETIME2 (7)   NULL,
    [Name]                             NVARCHAR (80)   NULL,
    [OwnerId]                          NCHAR (18)      NOT NULL,
    [Partnership__c]                   NVARCHAR (255)  NULL,
    [Partnership_History__c]           NVARCHAR (255)  NULL,
    [Partnership_History_Details_1__c] NVARCHAR (255)  NULL,
    [Physician_File_Flag__c]           VARCHAR (5)     NULL,
    [Rehire_Date__c]                   DATETIME2 (7)   NULL,
    [Reviewer__c]                      NCHAR (18)      NULL,
    [Risk_Rating__c]                   NVARCHAR (255)  NULL,
    [SystemModstamp]                   DATETIME2 (7)   NOT NULL,
    [Term_Date__c]                     DATETIME2 (7)   NULL,
    [Tickler_Date__c]                  DATETIME2 (7)   NULL,
    [To__c]                            DATETIME2 (7)   NULL
);

