CREATE TABLE [dbo].[SFDCWorkHistoryStaging] (
    [Active__c]                              VARCHAR (5)     NULL,
    [CEPA_Contracted_Site__c]                VARCHAR (5)     NULL,
    [City__c]                                NVARCHAR (1300) NULL,
    [Comment__c]                             NVARCHAR (255)  NULL,
    [Comments__c]                            NTEXT           NULL,
    [ConnectionReceivedId]                   NCHAR (18)      NULL,
    [ConnectionSentId]                       NCHAR (18)      NULL,
    [Contact__c]                             NCHAR (18)      NULL,
    [Contract_Holder__c]                     NCHAR (18)      NULL,
    [CreatedById]                            NCHAR (18)      NULL,
    [CreatedDate]                            DATETIME2 (7)   NOT NULL,
    [Cred_WH_Address__c]                     NVARCHAR (1300) NULL,
    [Employer__c]                            NCHAR (18)      NULL,
    [Employer_Name__c]                       NVARCHAR (160)  NULL,
    [Fax_1__c]                               NVARCHAR (1300) NULL,
    [From__c]                                DATETIME2 (7)   NULL,
    [Galen_Contracted_Site__c]               VARCHAR (5)     NULL,
    [Health_Care_Facility__c]                NCHAR (18)      NULL,
    [Healthcare_Facility_Name__c]            NVARCHAR (1300) NULL,
    [Id]                                     NCHAR (18)      NOT NULL,
    [IsDeleted]                              VARCHAR (5)     NOT NULL,
    [LastActivityDate]                       DATETIME2 (7)   NULL,
    [LastModifiedById]                       NCHAR (18)      NULL,
    [LastModifiedDate]                       DATETIME2 (7)   NOT NULL,
    [LastReferencedDate]                     DATETIME2 (7)   NULL,
    [LastViewedDate]                         DATETIME2 (7)   NULL,
    [Medical_Director_Supervisor__c]         NVARCHAR (255)  NULL,
    [Medical_Director_Supervisor_Formula__c] NVARCHAR (1300) NULL,
    [MSO_ID__c]                              NVARCHAR (1300) NULL,
    [MSO_Password__c]                        NVARCHAR (1300) NULL,
    [MSO_Website__c]                         NVARCHAR (1300) NULL,
    [Name]                                   NVARCHAR (80)   NULL,
    [Other_City__c]                          NVARCHAR (50)   NULL,
    [Other_Contracted_Site__c]               VARCHAR (5)     NULL,
    [Other_Facility__c]                      NVARCHAR (150)  NULL,
    [Other_Fax__c]                           NVARCHAR (40)   NULL,
    [Other_Phone__c]                         NVARCHAR (40)   NULL,
    [Other_State__c]                         NVARCHAR (255)  NULL,
    [Other_Street_1__c]                      NVARCHAR (150)  NULL,
    [Other_Street_2__c]                      NVARCHAR (100)  NULL,
    [Other_Zip__c]                           NVARCHAR (10)   NULL,
    [OwnerId]                                NCHAR (18)      NOT NULL,
    [Phone_1__c]                             NVARCHAR (1300) NULL,
    [Placement__c]                           NCHAR (18)      NULL,
    [Position__c]                            NVARCHAR (255)  NULL,
    [Practice_Location__c]                   NVARCHAR (255)  NULL,
    [Reason_for_Leaving__c]                  NVARCHAR (255)  NULL,
    [Related_Id__c]                          NVARCHAR (255)  NULL,
    [Responsibilities__c]                    NTEXT           NULL,
    [State__c]                               NVARCHAR (1300) NULL,
    [Status__c]                              NVARCHAR (255)  NULL,
    [Street_1__c]                            NVARCHAR (1300) NULL,
    [SystemModstamp]                         DATETIME2 (7)   NOT NULL,
    [Title__c]                               NVARCHAR (1300) NULL,
    [To__c]                                  DATETIME2 (7)   NULL,
    [TriggeredByAnotherTrigger__c]           VARCHAR (5)     NULL,
    [Verifications__c]                       NCHAR (18)      NULL,
    [Website__c]                             VARCHAR (5)     NULL,
    [Work_History_Type__c]                   NVARCHAR (255)  NULL,
    [Zip__c]                                 NVARCHAR (1300) NULL
);

