CREATE TABLE [dbo].[SFDCAdverseActionStaging] (
    [Action__c]                             NVARCHAR (255) NULL,
    [Action_Date__c]                        DATETIME2 (7)  NULL,
    [Action_Type__c]                        NVARCHAR (255) NULL,
    [ConnectionReceivedId]                  NCHAR (18)     NULL,
    [ConnectionSentId]                      NCHAR (18)     NULL,
    [Contact__c]                            NCHAR (18)     NULL,
    [CreatedById]                           NCHAR (18)     NULL,
    [CreatedDate]                           DATETIME2 (7)  NOT NULL,
    [Current_Credentials_Committee_Date__c] DATETIME2 (7)  NULL,
    [Current_Red_Flags__c]                  NTEXT          NULL,
    [Date_Reported_to_CPAC__c]              DATETIME2 (7)  NULL,
    [End_Date__c]                           DATETIME2 (7)  NULL,
    [Hours__c]                              NVARCHAR (100) NULL,
    [Id]                                    NCHAR (18)     NOT NULL,
    [IsDeleted]                             VARCHAR (5)    NOT NULL,
    [LastActivityDate]                      DATETIME2 (7)  NULL,
    [LastModifiedById]                      NCHAR (18)     NULL,
    [LastModifiedDate]                      DATETIME2 (7)  NOT NULL,
    [LastReferencedDate]                    DATETIME2 (7)  NULL,
    [LastViewedDate]                        DATETIME2 (7)  NULL,
    [Location_Address__c]                   NVARCHAR (255) NULL,
    [Location_Name__c]                      NVARCHAR (255) NULL,
    [Name]                                  NVARCHAR (80)  NULL,
    [Notes__c]                              NVARCHAR (255) NULL,
    [Outside_Activites_Date__c]             DATETIME2 (7)  NULL,
    [Outside_Activities_Notes__c]           NTEXT          NULL,
    [OwnerId]                               NCHAR (18)     NOT NULL,
    [Previous_Red_Flags__c]                 NTEXT          NULL,
    [Reported_Date__c]                      DATETIME2 (7)  NULL,
    [Reported_to_CPAC__c]                   VARCHAR (5)    NULL,
    [Source__c]                             NVARCHAR (255) NULL,
    [SystemModstamp]                        DATETIME2 (7)  NOT NULL,
    [Type__c]                               NVARCHAR (255) NULL
);

