CREATE TABLE [dbo].[SFDCEducationStaging] (
    [City__c]                      NVARCHAR (1300) NULL,
    [Comments_2__c]                NTEXT           NULL,
    [Completed__c]                 VARCHAR (5)     NULL,
    [ConnectionReceivedId]         NCHAR (18)      NULL,
    [ConnectionSentId]             NCHAR (18)      NULL,
    [Contact__c]                   NCHAR (18)      NULL,
    [Country__c]                   NVARCHAR (1300) NULL,
    [CreatedById]                  NCHAR (18)      NULL,
    [CreatedDate]                  DATETIME2 (7)   NOT NULL,
    [Cred_ET_Address__c]           NVARCHAR (1300) NULL,
    [Degree__c]                    NVARCHAR (255)  NULL,
    [Director__c]                  NVARCHAR (255)  NULL,
    [ECFMG_Date__c]                DATETIME2 (7)   NULL,
    [ECFMG_Number__c]              NVARCHAR (255)  NULL,
    [Education_Type__c]            NVARCHAR (255)  NULL,
    [Fax__c]                       NVARCHAR (1300) NULL,
    [From__c]                      DATETIME2 (7)   NULL,
    [Graduation_Date__c]           DATETIME2 (7)   NULL,
    [Id]                           NCHAR (18)      NOT NULL,
    [Institution_1__c]             NCHAR (18)      NULL,
    [IsDeleted]                    VARCHAR (5)     NOT NULL,
    [LastActivityDate]             DATETIME2 (7)   NULL,
    [LastModifiedById]             NCHAR (18)      NULL,
    [LastModifiedDate]             DATETIME2 (7)   NOT NULL,
    [LastReferencedDate]           DATETIME2 (7)   NULL,
    [LastViewedDate]               DATETIME2 (7)   NULL,
    [Name]                         NVARCHAR (80)   NULL,
    [OwnerId]                      NCHAR (18)      NOT NULL,
    [Phone__c]                     NVARCHAR (1300) NULL,
    [Related_Id__c]                NVARCHAR (255)  NULL,
    [Specialty__c]                 NVARCHAR (255)  NULL,
    [State__c]                     NVARCHAR (1300) NULL,
    [Street_1__c]                  NVARCHAR (1300) NULL,
    [Street_2__c]                  NVARCHAR (1300) NULL,
    [Sub_Name__c]                  NVARCHAR (1300) NULL,
    [SystemModstamp]               DATETIME2 (7)   NOT NULL,
    [To__c]                        DATETIME2 (7)   NULL,
    [TriggeredByAnotherTrigger__c] VARCHAR (5)     NULL,
    [Zip__c]                       NVARCHAR (1300) NULL
);

