CREATE TABLE [dbo].[SFDCAddressStagingNoHome] (
    [Address_Line_1__c]          NVARCHAR (255) NULL,
    [Address_Line_2__c]          NVARCHAR (255) NULL,
    [City__c]                    NVARCHAR (100) NULL,
    [Company__c]                 NCHAR (18)     NULL,
    [Company_Name__c]            NVARCHAR (255) NULL,
    [ConnectionReceivedId]       NCHAR (18)     NULL,
    [ConnectionSentId]           NCHAR (18)     NULL,
    [Contact__c]                 NCHAR (18)     NULL,
    [CreatedById]                NCHAR (18)     NULL,
    [CreatedDate]                DATETIME2 (7)  NOT NULL,
    [Effective_Date_for_Site__c] DATETIME2 (7)  NULL,
    [Fax__c]                     NVARCHAR (40)  NULL,
    [Id]                         NCHAR (18)     NOT NULL,
    [IsDeleted]                  VARCHAR (5)    NOT NULL,
    [LastActivityDate]           DATETIME2 (7)  NULL,
    [LastModifiedById]           NCHAR (18)     NULL,
    [LastModifiedDate]           DATETIME2 (7)  NOT NULL,
    [LastReferencedDate]         DATETIME2 (7)  NULL,
    [LastViewedDate]             DATETIME2 (7)  NULL,
    [Name]                       NVARCHAR (80)  NULL,
    [OwnerId]                    NCHAR (18)     NOT NULL,
    [Phone_2__c]                 NVARCHAR (40)  NULL,
    [Phone__c]                   NVARCHAR (40)  NULL,
    [Primary__c]                 VARCHAR (5)    NULL,
    [State__c]                   NVARCHAR (2)   NULL,
    [SystemModstamp]             DATETIME2 (7)  NOT NULL,
    [Type__c]                    NVARCHAR (255) NULL,
    [Zip__c]                     NVARCHAR (11)  NULL
);

