CREATE TABLE [dbo].[SFDCContractStaging] (
    [Account_Billing_County__c]       NVARCHAR (255)   NULL,
    [AccountId]                       NCHAR (18)       NOT NULL,
    [AccountPracticeLoc__c]           NVARCHAR (1300)  NULL,
    [ActivatedById]                   NCHAR (18)       NULL,
    [ActivatedDate]                   DATETIME2 (7)    NULL,
    [Biling_Co_Name__c]               NCHAR (18)       NULL,
    [Billing_Co_Address__c]           NVARCHAR (1300)  NULL,
    [Billing_Co_City__c]              NVARCHAR (1300)  NULL,
    [Billing_Co_Contact__c]           NVARCHAR (80)    NULL,
    [Billing_Co_County__c]            NVARCHAR (255)   NULL,
    [Billing_Co_Fax__c]               NVARCHAR (1300)  NULL,
    [Billing_Co_Phone__c]             NVARCHAR (1300)  NULL,
    [Billing_Co_State__c]             NVARCHAR (1300)  NULL,
    [Billing_Co_Zip__c]               NVARCHAR (1300)  NULL,
    [Billing_Number__c]               NVARCHAR (25)    NULL,
    [BillingCity]                     NVARCHAR (40)    NULL,
    [BillingCountry]                  NVARCHAR (80)    NULL,
    [BillingGeocodeAccuracy]          NVARCHAR (40)    NULL,
    [BillingLatitude]                 DECIMAL (18, 15) NULL,
    [BillingLongitude]                DECIMAL (18, 15) NULL,
    [BillingPostalCode]               NVARCHAR (20)    NULL,
    [BillingState]                    NVARCHAR (80)    NULL,
    [BillingStreet]                   NVARCHAR (255)   NULL,
    [Blue_Cross_Blue_Shield__c]       NVARCHAR (50)    NULL,
    [Cases__c]                        DECIMAL (18)     NULL,
    [CEP_Division__c]                 NVARCHAR (255)   NULL,
    [CEP_Region__c]                   NVARCHAR (255)   NULL,
    [CompanySignedDate]               DATETIME2 (7)    NULL,
    [CompanySignedId]                 NCHAR (18)       NULL,
    [Contract_Holder__c]              NCHAR (18)       NULL,
    [Contract_Location__c]            NCHAR (18)       NULL,
    [ContractNumber]                  NVARCHAR (30)    NULL,
    [ContractTerm]                    INT              NULL,
    [CreatedById]                     NCHAR (18)       NULL,
    [CreatedDate]                     DATETIME2 (7)    NOT NULL,
    [Cred_Billing_Address_Full__c]    NVARCHAR (1300)  NULL,
    [Cred_Billing_Co_Address_Full__c] NVARCHAR (1300)  NULL,
    [CustomerSignedDate]              DATETIME2 (7)    NULL,
    [CustomerSignedId]                NCHAR (18)       NULL,
    [CustomerSignedTitle]             NVARCHAR (40)    NULL,
    [Department_Phone__c]             NVARCHAR (40)    NULL,
    [Description]                     NTEXT            NULL,
    [Display_on_Public_Website__c]    VARCHAR (5)      NULL,
    [Effective_Date__c]               DATETIME2 (7)    NULL,
    [EndDate]                         DATETIME2 (7)    NULL,
    [Entity__c]                       NVARCHAR (255)   NULL,
    [Expiration_Date__c]              DATETIME2 (7)    NULL,
    [Fax__c]                          NVARCHAR (1300)  NULL,
    [Group_NPI__c]                    NVARCHAR (50)    NULL,
    [Group_Password__c]               NVARCHAR (50)    NULL,
    [Group_Taxonomy__c]               NVARCHAR (255)   NULL,
    [Group_User_ID__c]                NVARCHAR (80)    NULL,
    [Hospital_NPI__c]                 NVARCHAR (50)    NULL,
    [Id]                              NCHAR (18)       NOT NULL,
    [IsDeleted]                       VARCHAR (5)      NOT NULL,
    [LastActivityDate]                DATETIME2 (7)    NULL,
    [LastApprovedDate]                DATETIME2 (7)    NULL,
    [LastModifiedById]                NCHAR (18)       NULL,
    [LastModifiedDate]                DATETIME2 (7)    NOT NULL,
    [LastReferencedDate]              DATETIME2 (7)    NULL,
    [LastViewedDate]                  DATETIME2 (7)    NULL,
    [Malpractice_Carrier__c]          NCHAR (18)       NULL,
    [Malpractice_Carrier_Address__c]  NVARCHAR (1300)  NULL,
    [Malpractice_Carrier_City__c]     NVARCHAR (1300)  NULL,
    [Malpractice_Carrier_Contact__c]  NVARCHAR (80)    NULL,
    [Malpractice_Carrier_Fax__c]      NVARCHAR (1300)  NULL,
    [Malpractice_Carrier_Phone__c]    NVARCHAR (1300)  NULL,
    [Malpractice_Carrier_State__c]    NVARCHAR (1300)  NULL,
    [Malpractice_Carrier_Suite__c]    NVARCHAR (1300)  NULL,
    [Malpractice_Carrier_Zip__c]      NVARCHAR (1300)  NULL,
    [Medicaid__c]                     NVARCHAR (50)    NULL,
    [Medical_Director__c]             NCHAR (18)       NULL,
    [Medicare__c]                     NVARCHAR (50)    NULL,
    [Name]                            NVARCHAR (80)    NULL,
    [Notes__c]                        NTEXT            NULL,
    [Original_Group_Start_Date__c]    DATETIME2 (7)    NULL,
    [Other_1__c]                      NVARCHAR (50)    NULL,
    [Other_2__c]                      NVARCHAR (50)    NULL,
    [Other_3__c]                      NVARCHAR (50)    NULL,
    [OwnerExpirationNotice]           NVARCHAR (40)    NULL,
    [OwnerId]                         NCHAR (18)       NOT NULL,
    [Phone__c]                        NVARCHAR (1300)  NULL,
    [Policy_Number__c]                NVARCHAR (50)    NULL,
    [Practice_Location__c]            NVARCHAR (255)   NULL,
    [Practice_Location_Code__c]       NVARCHAR (255)   NULL,
    [Process_Level__c]                DECIMAL (18)     NULL,
    [ShippingCity]                    NVARCHAR (40)    NULL,
    [ShippingCountry]                 NVARCHAR (80)    NULL,
    [ShippingGeocodeAccuracy]         NVARCHAR (40)    NULL,
    [ShippingLatitude]                DECIMAL (18, 15) NULL,
    [ShippingLongitude]               DECIMAL (18, 15) NULL,
    [ShippingPostalCode]              NVARCHAR (20)    NULL,
    [ShippingState]                   NVARCHAR (80)    NULL,
    [ShippingStreet]                  NVARCHAR (255)   NULL,
    [SpecialTerms]                    NTEXT            NULL,
    [StartDate]                       DATETIME2 (7)    NULL,
    [Status]                          NVARCHAR (40)    NOT NULL,
    [StatusCode]                      NVARCHAR (40)    NOT NULL,
    [SystemModstamp]                  DATETIME2 (7)    NOT NULL,
    [Tax_ID__c]                       NVARCHAR (50)    NULL,
    [Visit_Count__c]                  DECIMAL (18)     NULL
);

