CREATE TABLE [dbo].[SFDCContactStaging] (
    [AccountId]                                        NCHAR (18)       NULL,
    [Active_Credentials__c]                            NVARCHAR (255)   NULL,
    [Active_DEA__c]                                    NVARCHAR (255)   NULL,
    [Active_license_s__c]                              NTEXT            NULL,
    [Active_State_License_1__c]                        NVARCHAR (255)   NULL,
    [Active_State_License_2__c]                        NVARCHAR (255)   NULL,
    [Active_State_License_3__c]                        NVARCHAR (255)   NULL,
    [Active_State_License_4__c]                        NVARCHAR (255)   NULL,
    [Active_State_License_Date_1__c]                   DATETIME2 (7)    NULL,
    [Active_State_License_Date_2__c]                   DATETIME2 (7)    NULL,
    [Active_State_License_Date_3__c]                   DATETIME2 (7)    NULL,
    [Active_State_License_Date_4__c]                   DATETIME2 (7)    NULL,
    [Additional_Comments__c]                           NVARCHAR (1500)  NULL,
    [Are_you_board_certified__c]                       NVARCHAR (255)   NULL,
    [Are_you_Board_Eligible__c]                        NVARCHAR (255)   NULL,
    [Are_you_comfortable_with_single_coverage__c]      NVARCHAR (255)   NULL,
    [Are_you_willing_to_work_variable_shifts__c]       NVARCHAR (255)   NULL,
    [Asking_the_patient__c]                            NVARCHAR (255)   NULL,
    [AssistantName]                                    NVARCHAR (40)    NULL,
    [AssistantPhone]                                   NVARCHAR (40)    NULL,
    [avg_pats_hr_shift__c]                             NVARCHAR (255)   NULL,
    [Background_issues__c]                             NVARCHAR (255)   NULL,
    [Behavior_Score__c]                                DECIMAL (18)     NULL,
    [Benefits__c]                                      NVARCHAR (1000)  NULL,
    [Best_Contact_info__c]                             NVARCHAR (255)   NULL,
    [Birthdate]                                        DATETIME2 (7)    NULL,
    [Board_Certification__c]                           NVARCHAR (255)   NULL,
    [Bonus__c]                                         DECIMAL (18, 2)  NULL,
    [Bus_Relationships__c]                             NVARCHAR (255)   NULL,
    [Candidate_Source_Detail__c]                       NVARCHAR (150)   NULL,
    [CAQH_ID_Number__c]                                NVARCHAR (100)   NULL,
    [CAQH_Password__c]                                 NVARCHAR (100)   NULL,
    [CAQH_Username__c]                                 NVARCHAR (100)   NULL,
    [Comments__c]                                      NTEXT            NULL,
    [Compensation_explanation__c]                      NVARCHAR (255)   NULL,
    [ConnectionReceivedId]                             NCHAR (18)       NULL,
    [ConnectionSentId]                                 NCHAR (18)       NULL,
    [Consider_other__c]                                NVARCHAR (255)   NULL,
    [Cover_Letter__c]                                  NTEXT            NULL,
    [CreatedById]                                      NCHAR (18)       NULL,
    [CreatedDate]                                      DATETIME2 (7)    NOT NULL,
    [Cred_Citizenship__c]                              NVARCHAR (255)   NULL,
    [Cred_City_of_Birth__c]                            NVARCHAR (255)   NULL,
    [Cred_Country_of_Birth_1__c]                       NVARCHAR (255)   NULL,
    [Cred_Date_Of_Birth__c]                            DATETIME2 (7)    NULL,
    [Cred_Enter_Non_English_Language_u_speak__c]       NTEXT            NULL,
    [Cred_FML_Name__c]                                 NVARCHAR (1300)  NULL,
    [Cred_FNIN_Country_of_Issue_1__c]                  NVARCHAR (255)   NULL,
    [Cred_Foreign_National_Identification_Num__c]      NVARCHAR (255)   NULL,
    [Cred_Gender__c]                                   NVARCHAR (255)   NULL,
    [Cred_LF_Name__c]                                  NVARCHAR (1300)  NULL,
    [Cred_LFM_Name__c]                                 NVARCHAR (1300)  NULL,
    [Cred_Marital_Status__c]                           NVARCHAR (255)   NULL,
    [Cred_NPI__c]                                      NVARCHAR (10)    NULL,
    [Cred_NPI_ID_Password__c]                          NVARCHAR (100)   NULL,
    [Cred_NPI_User_Password__c]                        NVARCHAR (255)   NULL,
    [Cred_Other_First_Name__c]                         NVARCHAR (255)   NULL,
    [Cred_Other_Last_Name__c]                          NVARCHAR (100)   NULL,
    [Cred_Other_Middle_Name__c]                        NVARCHAR (100)   NULL,
    [Cred_Social_Security_ID__c]                       NVARCHAR (9)     NULL,
    [Cred_Spouse_Name__c]                              NVARCHAR (255)   NULL,
    [Cred_Suffix__c]                                   NVARCHAR (255)   NULL,
    [Current_Active__c]                                NTEXT            NULL,
    [Current_offers__c]                                NVARCHAR (255)   NULL,
    [Currently_Contracted_With__c]                     NVARCHAR (100)   NULL,
    [Date_Availabletext__c]                            NVARCHAR (255)   NULL,
    [Date_Expected_to_Start__c]                        DATETIME2 (7)    NULL,
    [Date_Expired__c]                                  DATETIME2 (7)    NULL,
    [Date_of_Birth__c]                                 DATETIME2 (7)    NULL,
    [Demographic_Distribution__c]                      NVARCHAR (255)   NULL,
    [Demographic_Score__c]                             DECIMAL (18)     NULL,
    [Department]                                       NVARCHAR (80)    NULL,
    [Department__c]                                    NVARCHAR (255)   NULL,
    [Describe_the_type_of_practice__c]                 NVARCHAR (255)   NULL,
    [Describe_your_current_benefits_package__c]        NVARCHAR (255)   NULL,
    [Description]                                      NTEXT            NULL,
    [Desired_Geographic_Zone__c]                       NVARCHAR (255)   NULL,
    [Desired_Geographic_Zones__c]                      NTEXT            NULL,
    [Do_you_have_a_Current_License__c]                 NVARCHAR (255)   NULL,
    [Do_you_have_ACLS__c]                              NVARCHAR (255)   NULL,
    [Do_you_have_ATLS__c]                              NVARCHAR (255)   NULL,
    [Do_you_have_PALS__c]                              NVARCHAR (255)   NULL,
    [Do_you_know_about_us__c]                          NVARCHAR (255)   NULL,
    [Do_you_know_anyone_else_interested__c]            NVARCHAR (255)   NULL,
    [DoNotCall]                                        VARCHAR (5)      NOT NULL,
    [ED_or_Non_ED__c]                                  NVARCHAR (255)   NULL,
    [ED_or_Non_ED_shifts_and_or_hours_worked__c]       NVARCHAR (255)   NULL,
    [ED_Volume__c]                                     DECIMAL (18)     NULL,
    [Email]                                            NVARCHAR (80)    NULL,
    [Email_linked_to_CAQH_account__c]                  NVARCHAR (80)    NULL,
    [EmailBouncedDate]                                 DATETIME2 (7)    NULL,
    [EmailBouncedReason]                               NVARCHAR (255)   NULL,
    [Emp__c]                                           NVARCHAR (1300)  NULL,
    [Employee_Id__c]                                   DECIMAL (18)     NULL,
    [Employee_Type__c]                                 NVARCHAR (255)   NULL,
    [Examples_if_in_ED__c]                             NVARCHAR (255)   NULL,
    [Existing_Client_Health_System__c]                 NVARCHAR (255)   NULL,
    [Expiration_Dates__c]                              DATETIME2 (7)    NULL,
    [Fax]                                              NVARCHAR (40)    NULL,
    [First_Name_DDP__c]                                NVARCHAR (1300)  NULL,
    [FirstName]                                        NVARCHAR (40)    NULL,
    [Former_Contact__c]                                VARCHAR (5)      NULL,
    [genius_com__Genius_Hard_Bounce__c]                VARCHAR (5)      NULL,
    [genius_com__Genius_Hard_Bounce_Date__c]           DATETIME2 (7)    NULL,
    [genius_com__GeniusScore__c]                       DECIMAL (18)     NULL,
    [Geographic_Information__c]                        NTEXT            NULL,
    [HasOptedOutOfEmail]                               VARCHAR (5)      NOT NULL,
    [HasOptedOutOfFax]                                 VARCHAR (5)      NOT NULL,
    [Have_you_ever_worked_with_a_EMR__c]               NVARCHAR (255)   NULL,
    [Have_you_worked_in_the_following__c]              NTEXT            NULL,
    [Have_you_worked_with__c]                          NVARCHAR (255)   NULL,
    [HomePhone]                                        NVARCHAR (40)    NULL,
    [Hourly__c]                                        DECIMAL (18, 2)  NULL,
    [How_many_hours_do_you_work_in_a_week_avg__c]      NVARCHAR (255)   NULL,
    [How_would_you_rate_your_computer_skills__c]       NVARCHAR (255)   NULL,
    [Id]                                               NCHAR (18)       NOT NULL,
    [If_Other_list_Specialty__c]                       NVARCHAR (75)    NULL,
    [Inactive_license_s__c]                            NTEXT            NULL,
    [Interest_Rating__c]                               NVARCHAR (255)   NULL,
    [IsDeleted]                                        VARCHAR (5)      NOT NULL,
    [IsEmailBounced]                                   VARCHAR (5)      NOT NULL,
    [Jigsaw]                                           NVARCHAR (20)    NULL,
    [JigsawContactId]                                  NVARCHAR (20)    NULL,
    [Job_Level__c]                                     NVARCHAR (255)   NULL,
    [JSO2__Active_Accomodation_File__c]                NCHAR (18)       NULL,
    [JSO2__Active_Benefits_File__c]                    NCHAR (18)       NULL,
    [JSO2__Active_Consents_File__c]                    NCHAR (18)       NULL,
    [JSO2__Active_Direct_Deposit_File__c]              NCHAR (18)       NULL,
    [JSO2__Active_Driver_File__c]                      NCHAR (18)       NULL,
    [JSO2__Active_EEO_File__c]                         NCHAR (18)       NULL,
    [JSO2__Active_Emergency_File__c]                   NCHAR (18)       NULL,
    [JSO2__Active_Employee_File__c]                    NCHAR (18)       NULL,
    [JSO2__Active_I_9_File__c]                         NCHAR (18)       NULL,
    [JSO2__Active_State_Tax_File__c]                   NCHAR (18)       NULL,
    [JSO2__Active_W_4_File__c]                         NCHAR (18)       NULL,
    [Last_Name_DDP__c]                                 NVARCHAR (1300)  NULL,
    [LastActivityDate]                                 DATETIME2 (7)    NULL,
    [LastCURequestDate]                                DATETIME2 (7)    NULL,
    [LastCUUpdateDate]                                 DATETIME2 (7)    NULL,
    [LastModifiedById]                                 NCHAR (18)       NULL,
    [LastModifiedDate]                                 DATETIME2 (7)    NOT NULL,
    [LastName]                                         NVARCHAR (80)    NOT NULL,
    [LastReferencedDate]                               DATETIME2 (7)    NULL,
    [LastViewedDate]                                   DATETIME2 (7)    NULL,
    [Lead_Rating_A_E__c]                               NVARCHAR (255)   NULL,
    [Lead_Source_Detail__c]                            NVARCHAR (1000)  NULL,
    [Leadership_Role__c]                               NVARCHAR (255)   NULL,
    [LeadSource]                                       NVARCHAR (40)    NULL,
    [Legal_Entity__c]                                  NVARCHAR (255)   NULL,
    [License_Expiration_Date__c]                       DATETIME2 (7)    NULL,
    [LID__LinkedIn_Company_Id__c]                      NVARCHAR (80)    NULL,
    [LID__LinkedIn_Member_Token__c]                    NVARCHAR (80)    NULL,
    [Location_Type__c]                                 NVARCHAR (255)   NULL,
    [LWB__c]                                           DECIMAL (18, 2)  NULL,
    [MailingCity]                                      NVARCHAR (40)    NULL,
    [MailingCountry]                                   NVARCHAR (80)    NULL,
    [MailingGeocodeAccuracy]                           NVARCHAR (40)    NULL,
    [MailingLatitude]                                  DECIMAL (18, 15) NULL,
    [MailingLongitude]                                 DECIMAL (18, 15) NULL,
    [MailingPostalCode]                                NVARCHAR (20)    NULL,
    [MailingState]                                     NVARCHAR (80)    NULL,
    [MailingStreet]                                    NVARCHAR (255)   NULL,
    [MasterRecordId]                                   NCHAR (18)       NULL,
    [MD_Compensation__c]                               NVARCHAR (255)   NULL,
    [MD_Graduation_Date__c]                            DATETIME2 (7)    NULL,
    [Medical_Director__c]                              NVARCHAR (1300)  NULL,
    [Medical_School__c]                                NVARCHAR (255)   NULL,
    [Medical_School_Completion__c]                     DATETIME2 (7)    NULL,
    [Medical_Speciality__c]                            NVARCHAR (255)   NULL,
    [Medical_Speciality_Other__c]                      NVARCHAR (255)   NULL,
    [Metro_Area__c]                                    NVARCHAR (255)   NULL,
    [Middle_Initial__c]                                NVARCHAR (1300)  NULL,
    [Middle_Name__c]                                   NVARCHAR (64)    NULL,
    [mkto2__Acquisition_Date__c]                       DATETIME2 (7)    NULL,
    [mkto2__Acquisition_Program__c]                    NVARCHAR (255)   NULL,
    [mkto2__Acquisition_Program_Id__c]                 DECIMAL (18)     NULL,
    [mkto2__Inferred_City__c]                          NVARCHAR (255)   NULL,
    [mkto2__Inferred_Company__c]                       NVARCHAR (255)   NULL,
    [mkto2__Inferred_Country__c]                       NVARCHAR (255)   NULL,
    [mkto2__Inferred_Metropolitan_Area__c]             NVARCHAR (255)   NULL,
    [mkto2__Inferred_Phone_Area_Code__c]               NVARCHAR (255)   NULL,
    [mkto2__Inferred_Postal_Code__c]                   NVARCHAR (255)   NULL,
    [mkto2__Inferred_State_Region__c]                  NVARCHAR (255)   NULL,
    [mkto2__Lead_Score__c]                             DECIMAL (18)     NULL,
    [mkto2__Original_Referrer__c]                      NVARCHAR (255)   NULL,
    [mkto2__Original_Search_Engine__c]                 NVARCHAR (255)   NULL,
    [mkto2__Original_Search_Phrase__c]                 NVARCHAR (255)   NULL,
    [mkto2__Original_Source_Info__c]                   NVARCHAR (2000)  NULL,
    [mkto2__Original_Source_Type__c]                   NVARCHAR (255)   NULL,
    [mkto_si__HideDate__c]                             DATETIME2 (7)    NULL,
    [mkto_si__Last_Interesting_Moment__c]              NVARCHAR (1300)  NULL,
    [mkto_si__Last_Interesting_Moment_Date__c]         DATETIME2 (7)    NULL,
    [mkto_si__Last_Interesting_Moment_Desc__c]         NVARCHAR (255)   NULL,
    [mkto_si__Last_Interesting_Moment_Source__c]       NVARCHAR (100)   NULL,
    [mkto_si__Last_Interesting_Moment_Type__c]         NVARCHAR (100)   NULL,
    [mkto_si__Priority__c]                             DECIMAL (18)     NULL,
    [mkto_si__Relative_Score__c]                       NVARCHAR (1300)  NULL,
    [mkto_si__Relative_Score_Value__c]                 DECIMAL (18)     NULL,
    [mkto_si__Sales_Insight__c]                        NVARCHAR (1300)  NULL,
    [mkto_si__Urgency__c]                              NVARCHAR (1300)  NULL,
    [mkto_si__Urgency_Value__c]                        DECIMAL (18)     NULL,
    [mkto_si__View_in_Marketo__c]                      NVARCHAR (1300)  NULL,
    [MLP_NATL_CERT__c]                                 NTEXT            NULL,
    [MLPs_Utilized__c]                                 NVARCHAR (255)   NULL,
    [MobilePhone]                                      NVARCHAR (40)    NULL,
    [Month_Year_Completed__c]                          DATETIME2 (7)    NULL,
    [Most_recent_employer__c]                          NVARCHAR (255)   NULL,
    [Name]                                             NVARCHAR (121)   NOT NULL,
    [National_Certified__c]                            NTEXT            NULL,
    [Next_Step__c]                                     NTEXT            NULL,
    [Opportunity_Detail__c]                            NVARCHAR (255)   NULL,
    [Other__c]                                         NVARCHAR (255)   NULL,
    [Other_Certifications__c]                          NTEXT            NULL,
    [Other_Credentials__c]                             NTEXT            NULL,
    [OtherCity]                                        NVARCHAR (40)    NULL,
    [OtherCountry]                                     NVARCHAR (80)    NULL,
    [OtherGeocodeAccuracy]                             NVARCHAR (40)    NULL,
    [OtherLatitude]                                    DECIMAL (18, 15) NULL,
    [OtherLongitude]                                   DECIMAL (18, 15) NULL,
    [OtherPhone]                                       NVARCHAR (40)    NULL,
    [OtherPostalCode]                                  NVARCHAR (20)    NULL,
    [OtherState]                                       NVARCHAR (80)    NULL,
    [OtherStreet]                                      NVARCHAR (255)   NULL,
    [OwnerId]                                          NCHAR (18)       NOT NULL,
    [Ownership_Structure__c]                           NVARCHAR (255)   NULL,
    [PA_NP_Graduation_Date__c]                         DATETIME2 (7)    NULL,
    [PA_NP_Utilized__c]                                NVARCHAR (255)   NULL,
    [Pain_Points__c]                                   NTEXT            NULL,
    [PANP_Completion__c]                               DATETIME2 (7)    NULL,
    [PANP_Program__c]                                  NVARCHAR (255)   NULL,
    [Payer_mix__c]                                     NVARCHAR (255)   NULL,
    [PE_DDP_Accont_Prac_Loc__c]                        NVARCHAR (1300)  NULL,
    [PE_DDP_Contract__c]                               NCHAR (18)       NULL,
    [Phone]                                            NVARCHAR (40)    NULL,
    [PhotoUrl]                                         NVARCHAR (255)   NULL,
    [Position__c]                                      NVARCHAR (250)   NULL,
    [Preferred_Name__c]                                NVARCHAR (255)   NULL,
    [Primary_Taxonomy__c]                              NVARCHAR (1300)  NULL,
    [Primary_Taxonomy_Description__c]                  NVARCHAR (255)   NULL,
    [Procedures_exp__c]                                NVARCHAR (255)   NULL,
    [Professional_Suffix__c]                           NVARCHAR (50)    NULL,
    [Program_ED_prepared__c]                           NVARCHAR (255)   NULL,
    [Provider_Master_ID__c]                            NVARCHAR (255)   NULL,
    [Qualification_Rating__c]                          NVARCHAR (255)   NULL,
    [Record_Status__c]                                 NVARCHAR (255)   NULL,
    [RecordTypeId]                                     NCHAR (18)       NULL,
    [Recuitment_Status__c]                             NVARCHAR (255)   NULL,
    [Relationships_with_others__c]                     NVARCHAR (255)   NULL,
    [ReportsToId]                                      NCHAR (18)       NULL,
    [Research__c]                                      NTEXT            NULL,
    [Residency_Completion__c]                          NVARCHAR (255)   NULL,
    [Residency_Program__c]                             NVARCHAR (255)   NULL,
    [Salary__c]                                        DECIMAL (18, 2)  NULL,
    [Salary_benefits_exp__c]                           NVARCHAR (255)   NULL,
    [Salutation]                                       NVARCHAR (40)    NULL,
    [Secondary_Email__c]                               NVARCHAR (80)    NULL,
    [Specialty__c]                                     NVARCHAR (255)   NULL,
    [Staff_Status__c]                                  NVARCHAR (255)   NULL,
    [State_License__c]                                 NTEXT            NULL,
    [State_of_Birth_1__c]                              NVARCHAR (255)   NULL,
    [Stipend__c]                                       NVARCHAR (255)   NULL,
    [Suffix__c]                                        NVARCHAR (5)     NULL,
    [SystemModstamp]                                   DATETIME2 (7)    NOT NULL,
    [Tell_me_about_your_expereince__c]                 NVARCHAR (255)   NULL,
    [Time_to_provide__c]                               NVARCHAR (255)   NULL,
    [Title]                                            NVARCHAR (128)   NULL,
    [Title__c]                                         NVARCHAR (255)   NULL,
    [Title_Categories__c]                              NVARCHAR (255)   NULL,
    [Title_Short_List_Job_Board__c]                    NVARCHAR (255)   NULL,
    [Title_Status__c]                                  NVARCHAR (255)   NULL,
    [Training_Program__c]                              NVARCHAR (255)   NULL,
    [ts2__Action__c]                                   NVARCHAR (1300)  NULL,
    [ts2__Active_Search__c]                            VARCHAR (5)      NULL,
    [ts2__Asst_Email__c]                               NVARCHAR (35)    NULL,
    [ts2__Best_Fit__c]                                 NVARCHAR (255)   NULL,
    [ts2__Business_Telephone_Number__c]                NVARCHAR (40)    NULL,
    [ts2__Business_Unit__c]                            NVARCHAR (255)   NULL,
    [ts2__Candidate_Source__c]                         NCHAR (18)       NULL,
    [ts2__Certifications__c]                           NTEXT            NULL,
    [ts2__Contact_Method__c]                           NVARCHAR (255)   NULL,
    [ts2__Contact_Tags__c]                             NVARCHAR (255)   NULL,
    [ts2__Current_Hourly__c]                           DECIMAL (18, 2)  NULL,
    [ts2__Current_Salary__c]                           DECIMAL (18, 2)  NULL,
    [ts2__Date_Available__c]                           DATETIME2 (7)    NULL,
    [ts2__Desired_Hourly__c]                           DECIMAL (18, 2)  NULL,
    [ts2__Desired_Salary__c]                           DECIMAL (18, 2)  NULL,
    [ts2__DischargeStatus__c]                          NVARCHAR (255)   NULL,
    [ts2__Doc_Id__c]                                   NVARCHAR (100)   NULL,
    [ts2__EduacademicHonors1__c]                       NVARCHAR (255)   NULL,
    [ts2__EduacademicHonors2__c]                       NVARCHAR (255)   NULL,
    [ts2__Education__c]                                NTEXT            NULL,
    [ts2__Education_School_1__c]                       NVARCHAR (125)   NULL,
    [ts2__Education_School_2__c]                       NVARCHAR (125)   NULL,
    [ts2__EduDegreeDate1__c]                           DATETIME2 (7)    NULL,
    [ts2__EduDegreeDate2__c]                           DATETIME2 (7)    NULL,
    [ts2__EduDegreeMajor1__c]                          NVARCHAR (255)   NULL,
    [ts2__EduDegreeMajor2__c]                          NVARCHAR (255)   NULL,
    [ts2__EduDegreeMinor1__c]                          NVARCHAR (255)   NULL,
    [ts2__EduDegreeMinor2__c]                          NVARCHAR (255)   NULL,
    [ts2__EduDegreeName1__c]                           NVARCHAR (255)   NULL,
    [ts2__EduDegreeName2__c]                           NVARCHAR (255)   NULL,
    [ts2__EduDegreeType1__c]                           NVARCHAR (255)   NULL,
    [ts2__EduDegreeType2__c]                           NVARCHAR (255)   NULL,
    [ts2__Edudocumentation1__c]                        NVARCHAR (255)   NULL,
    [ts2__Edudocumentation2__c]                        NVARCHAR (255)   NULL,
    [ts2__EduhonorsProgram1__c]                        NVARCHAR (255)   NULL,
    [ts2__EduhonorsProgram2__c]                        NVARCHAR (255)   NULL,
    [ts2__EduOtherHonors1__c]                          NVARCHAR (255)   NULL,
    [ts2__EduOtherHonors2__c]                          NVARCHAR (255)   NULL,
    [ts2__EduschoolTypes1__c]                          NVARCHAR (255)   NULL,
    [ts2__EduschoolTypes2__c]                          NVARCHAR (255)   NULL,
    [ts2__EEO_Disabled__c]                             NVARCHAR (255)   NULL,
    [ts2__EEO_Disabled_Received__c]                    NVARCHAR (1300)  NULL,
    [ts2__EEO_Gender__c]                               NVARCHAR (255)   NULL,
    [ts2__EEO_Gender_Received__c]                      NVARCHAR (1300)  NULL,
    [ts2__EEO_Populate__c]                             VARCHAR (5)      NULL,
    [ts2__EEO_Race__c]                                 NVARCHAR (255)   NULL,
    [ts2__EEO_Race_Received__c]                        NVARCHAR (1300)  NULL,
    [ts2__EEO_Veteran_Status__c]                       NVARCHAR (255)   NULL,
    [ts2__EEO_Veteran_Status_Received__c]              NVARCHAR (1300)  NULL,
    [ts2__Emp_PositionHistory_positiontype1__c]        NVARCHAR (255)   NULL,
    [ts2__Emp_PositionHistory_positiontype2__c]        NVARCHAR (255)   NULL,
    [ts2__Employer1CategoryCode__c]                    NVARCHAR (255)   NULL,
    [ts2__Employer1Description__c]                     NTEXT            NULL,
    [ts2__Employer1EndDate__c]                         DATETIME2 (7)    NULL,
    [ts2__Employer1StartDate__c]                       DATETIME2 (7)    NULL,
    [ts2__Employer1Title__c]                           NTEXT            NULL,
    [ts2__Employer2_Category_Code__c]                  NVARCHAR (255)   NULL,
    [ts2__Employer2Description__c]                     NTEXT            NULL,
    [ts2__Employer2EndDate__c]                         DATETIME2 (7)    NULL,
    [ts2__Employer2StartDate__c]                       DATETIME2 (7)    NULL,
    [ts2__Employer2Title__c]                           NVARCHAR (255)   NULL,
    [ts2__Employer3_Category_Code__c]                  NVARCHAR (255)   NULL,
    [ts2__Employer3Description__c]                     NTEXT            NULL,
    [ts2__Employer3EndDate__c]                         DATETIME2 (7)    NULL,
    [ts2__Employer3StartDate__c]                       DATETIME2 (7)    NULL,
    [ts2__Employer3Title__c]                           NVARCHAR (255)   NULL,
    [ts2__EmployerOrgName_1__c]                        NVARCHAR (255)   NULL,
    [ts2__EmployerOrgName_2__c]                        NVARCHAR (255)   NULL,
    [ts2__EmployerOrgName_3__c]                        NVARCHAR (255)   NULL,
    [ts2__Executive_summary__c]                        NTEXT            NULL,
    [ts2__Experience_Summary__c]                       NVARCHAR (255)   NULL,
    [ts2__Facebook_Profile__c]                         NVARCHAR (255)   NULL,
    [ts2__Firstname__c]                                NVARCHAR (40)    NULL,
    [ts2__Geo_Location_Passed__c]                      VARCHAR (5)      NULL,
    [ts2__Hard_Rating__c]                              NVARCHAR (1300)  NULL,
    [ts2__Hard_Skills__c]                              DECIMAL (18)     NULL,
    [ts2__HasEmailBounced__c]                          VARCHAR (5)      NULL,
    [ts2__Hide_Photo__c]                               VARCHAR (5)      NULL,
    [ts2__Home_Telephone_Number__c]                    NVARCHAR (40)    NULL,
    [ts2__I9_Received__c]                              VARCHAR (5)      NULL,
    [ts2__Internet_Email_Address__c]                   NVARCHAR (80)    NULL,
    [ts2__iPaper_Key__c]                               NVARCHAR (100)   NULL,
    [ts2__Job_Type__c]                                 NTEXT            NULL,
    [ts2__JobNotificationsSummary__c]                  DECIMAL (18)     NULL,
    [ts2__Jobs_Applied_For__c]                         NVARCHAR (255)   NULL,
    [ts2__Language_Comments_1__c]                      NVARCHAR (255)   NULL,
    [ts2__Language_Comments_2__c]                      NVARCHAR (255)   NULL,
    [ts2__Language_Read_1__c]                          NVARCHAR (255)   NULL,
    [ts2__Language_Read_2__c]                          NVARCHAR (255)   NULL,
    [ts2__Language_Speak_1__c]                         NVARCHAR (255)   NULL,
    [ts2__Language_Speak_2__c]                         NVARCHAR (255)   NULL,
    [ts2__Language_Write_1__c]                         NVARCHAR (255)   NULL,
    [ts2__Language_Write_2__c]                         NVARCHAR (255)   NULL,
    [ts2__Languages__c]                                NVARCHAR (100)   NULL,
    [ts2__Lastname__c]                                 NVARCHAR (40)    NULL,
    [ts2__Latitude__c]                                 DECIMAL (18, 5)  NULL,
    [ts2__Legacy_ContactID__c]                         NVARCHAR (100)   NULL,
    [ts2__Legacy_DocumentID__c]                        NVARCHAR (100)   NULL,
    [ts2__Level__c]                                    NVARCHAR (255)   NULL,
    [ts2__License_or_Certification_Credential_Type__c] NVARCHAR (255)   NULL,
    [ts2__License_or_Certification_Description_1__c]   NVARCHAR (255)   NULL,
    [ts2__License_or_Certification_Description_2__c]   NVARCHAR (255)   NULL,
    [ts2__License_or_Certification_Name_1__c]          NVARCHAR (255)   NULL,
    [ts2__License_or_Certification_Name_2__c]          NVARCHAR (255)   NULL,
    [ts2__LinkedIn_Profile__c]                         NVARCHAR (255)   NULL,
    [ts2__Login_Password__c]                           NVARCHAR (100)   NULL,
    [ts2__Longitude__c]                                DECIMAL (18, 5)  NULL,
    [ts2__LUID__c]                                     NVARCHAR (35)    NULL,
    [ts2__MailingCountryText__c]                       NVARCHAR (80)    NULL,
    [ts2__MailingStateText__c]                         NVARCHAR (80)    NULL,
    [ts2__Match__c]                                    DECIMAL (18)     NULL,
    [ts2__Memo__c]                                     NVARCHAR (255)   NULL,
    [ts2__Middlename__c]                               NVARCHAR (64)    NULL,
    [ts2__Military_History_Type__c]                    NVARCHAR (255)   NULL,
    [ts2__Mobile_Telephone_Number__c]                  NVARCHAR (40)    NULL,
    [ts2__Notice__c]                                   NVARCHAR (255)   NULL,
    [ts2__People_Status__c]                            NVARCHAR (255)   NULL,
    [ts2__Picture__c]                                  NVARCHAR (1300)  NULL,
    [ts2__Picture_Id__c]                               NVARCHAR (30)    NULL,
    [ts2__Preferred_Name__c]                           NVARCHAR (255)   NULL,
    [ts2__Qualification_Summary__c]                    NVARCHAR (255)   NULL,
    [ts2__Reference_1__c]                              NVARCHAR (255)   NULL,
    [ts2__Reference_2__c]                              NVARCHAR (255)   NULL,
    [ts2__Referral_Lookup__c]                          NCHAR (18)       NULL,
    [ts2__ReferrerEmailMessage__c]                     NTEXT            NULL,
    [ts2__ReferrerEmailSubject__c]                     NVARCHAR (255)   NULL,
    [ts2__Relocated__c]                                VARCHAR (5)      NULL,
    [ts2__Relocation_Date__c]                          DATETIME2 (7)    NULL,
    [ts2__Resume_Last_Updated__c]                      DATETIME2 (7)    NULL,
    [ts2__Search_Social_Profiles__c]                   NVARCHAR (1300)  NULL,
    [ts2__Second_Best_Fit__c]                          NVARCHAR (255)   NULL,
    [ts2__Security_Credential_1__c]                    NVARCHAR (255)   NULL,
    [ts2__Security_Credential_Description_1__c]        NVARCHAR (255)   NULL,
    [ts2__Security_Credential_Type_1__c]               NVARCHAR (255)   NULL,
    [ts2__SessionKey__c]                               NVARCHAR (32)    NULL,
    [ts2__Shift__c]                                    NTEXT            NULL,
    [ts2__Skill_Codes__c]                              NTEXT            NULL,
    [ts2__Social_Security__c]                          NVARCHAR (9)     NULL,
    [ts2__Soft_Rating__c]                              NVARCHAR (1300)  NULL,
    [ts2__Soft_Skills__c]                              DECIMAL (18)     NULL,
    [ts2__Source__c]                                   NVARCHAR (255)   NULL,
    [ts2__Source_Notes__c]                             NVARCHAR (255)   NULL,
    [ts2__SSN1__c]                                     NVARCHAR (3)     NULL,
    [ts2__SSN2__c]                                     NVARCHAR (2)     NULL,
    [ts2__SSN3__c]                                     NVARCHAR (4)     NULL,
    [ts2__Taxonomy_Last_12_Months__c]                  NVARCHAR (255)   NULL,
    [ts2__Taxonomy_Qualifications__c]                  NVARCHAR (255)   NULL,
    [ts2__Taxonomy_Skills__c]                          NVARCHAR (255)   NULL,
    [ts2__Taxonomy_Work_History_12_24__c]              NVARCHAR (255)   NULL,
    [ts2__Taxonomy_Work_History_24_36__c]              NVARCHAR (255)   NULL,
    [ts2__Taxonomy_Work_History_36_48__c]              NVARCHAR (255)   NULL,
    [ts2__Text_Resume__c]                              NTEXT            NULL,
    [ts2__Total_Months_Employed__c]                    DECIMAL (18)     NULL,
    [ts2__Twitter_Profile__c]                          NVARCHAR (255)   NULL,
    [ts2__Verified__c]                                 VARCHAR (5)      NULL,
    [ts2__Verified_Date__c]                            DATETIME2 (7)    NULL,
    [ts2__Verified_Key__c]                             NVARCHAR (255)   NULL,
    [ts2__W4_Received__c]                              VARCHAR (5)      NULL,
    [ts2__Years_of_Experience__c]                      DECIMAL (18)     NULL,
    [VISA_Status__c]                                   NVARCHAR (255)   NULL,
    [Visitor_Message__c]                               NTEXT            NULL,
    [Volume_Threshold__c]                              NVARCHAR (255)   NULL,
    [Wait_time__c]                                     DECIMAL (18)     NULL,
    [What_are_the_most_important_factors__c]           NVARCHAR (255)   NULL,
    [What_are_your_core_strengths__c]                  NVARCHAR (255)   NULL,
    [What_group_are_you_working_for__c]                NVARCHAR (255)   NULL,
    [What_interest_you__c]                             NVARCHAR (255)   NULL,
    [What_is_motivating_you__c]                        NVARCHAR (255)   NULL,
    [What_is_the_best_time_for_a_follow_up__c]         NVARCHAR (255)   NULL,
    [What_is_your_current_employment_status__c]        NVARCHAR (255)   NULL,
    [What_is_your_hourly_compensation__c]              DECIMAL (18)     NULL,
    [What_is_your_salary_compensation__c]              DECIMAL (18)     NULL,
    [What_is_your_typical_shift_length__c]             NVARCHAR (255)   NULL,
    [Where_are_you_at_in_your_job_search__c]           NVARCHAR (255)   NULL,
    [Where_would_you_like_to_expand_skill_set__c]      NVARCHAR (255)   NULL,
    [Who_holds_the_ED_contract__c]                     NVARCHAR (255)   NULL,
    [Why_don_t_you_quickly_walk_me_through_yo__c]      NVARCHAR (255)   NULL,
    [Willingness_for_basic_background_check__c]        NVARCHAR (255)   NULL,
    [Would_you_submit_to_a_credentials_check__c]       NVARCHAR (255)   NULL,
    [Zone_Name_Priority__c]                            NVARCHAR (255)   NULL
);

