CREATE TABLE [dbo].[SFDCNewHireChecklistStaging] (
    [Add_Work_History_Verif_Received__c]   DATETIME2 (7)  NULL,
    [Add_Work_History_Verif_Sent__c]       NVARCHAR (80)  NULL,
    [Adverse_Action__c]                    VARCHAR (5)    NULL,
    [Anticipated_Credentials_Committee__c] DATETIME2 (7)  NULL,
    [Application_Received__c]              DATETIME2 (7)  NULL,
    [Attestation_Signature_Date__c]        DATETIME2 (7)  NULL,
    [Board_Certification_Verified__c]      DATETIME2 (7)  NULL,
    [Claims_History_Received__c]           DATETIME2 (7)  NULL,
    [Clinical_Privilege_Verif_Received__c] DATETIME2 (7)  NULL,
    [Clinical_Privilege_Verif_Sent__c]     NVARCHAR (80)  NULL,
    [Comments2__c]                         NTEXT          NULL,
    [Comments_3__c]                        NTEXT          NULL,
    [Comments__c]                          NTEXT          NULL,
    [ConnectionReceivedId]                 NCHAR (18)     NULL,
    [ConnectionSentId]                     NCHAR (18)     NULL,
    [Contact__c]                           NCHAR (18)     NULL,
    [CreatedById]                          NCHAR (18)     NULL,
    [CreatedDate]                          DATETIME2 (7)  NOT NULL,
    [Credentialer__c]                      NCHAR (18)     NULL,
    [Credentials_Committee_Date__c]        DATETIME2 (7)  NULL,
    [Credentials_File_Complete__c]         DATETIME2 (7)  NULL,
    [CV_Review_Date__c]                    DATETIME2 (7)  NULL,
    [CV_Reviewed__c]                       NVARCHAR (255) NULL,
    [DEA_CDS_Certificate_Verified__c]      DATETIME2 (7)  NULL,
    [EPLS__c]                              DATETIME2 (7)  NULL,
    [Id]                                   NCHAR (18)     NOT NULL,
    [IsDeleted]                            VARCHAR (5)    NOT NULL,
    [LastActivityDate]                     DATETIME2 (7)  NULL,
    [LastModifiedById]                     NCHAR (18)     NULL,
    [LastModifiedDate]                     DATETIME2 (7)  NOT NULL,
    [LastReferencedDate]                   DATETIME2 (7)  NULL,
    [LastViewedDate]                       DATETIME2 (7)  NULL,
    [Malpractice_Insurance_Cert_Rec_d__c]  DATETIME2 (7)  NULL,
    [Manager_Reviewed_Date__c]             DATETIME2 (7)  NULL,
    [Name]                                 NVARCHAR (80)  NULL,
    [NPDB_Query__c]                        DATETIME2 (7)  NULL,
    [OIG__c]                               DATETIME2 (7)  NULL,
    [OwnerId]                              NCHAR (18)     NOT NULL,
    [Partnership_Agreement_Date__c]        NVARCHAR (100) NULL,
    [Provider_Name__c]                     NVARCHAR (255) NULL,
    [RecordTypeId]                         NCHAR (18)     NULL,
    [Recred_Application_Received__c]       DATETIME2 (7)  NULL,
    [Recred_Application_Sent__c]           DATETIME2 (7)  NULL,
    [References_Completed_Date_2__c]       DATETIME2 (7)  NULL,
    [References_Completed_Date_3__c]       DATETIME2 (7)  NULL,
    [References_Received_Date__c]          DATETIME2 (7)  NULL,
    [References_Sent__c]                   NVARCHAR (80)  NULL,
    [Restrictions_to_Privileges__c]        VARCHAR (5)    NULL,
    [Sanctions__c]                         VARCHAR (5)    NULL,
    [State_Medical_License_Verified__c]    DATETIME2 (7)  NULL,
    [Status__c]                            NVARCHAR (255) NULL,
    [SystemModstamp]                       DATETIME2 (7)  NOT NULL,
    [Training_Verif_Received__c]           DATETIME2 (7)  NULL,
    [Training_Verif_Sent__c]               NVARCHAR (100) NULL,
    [Work_History_Gaps__c]                 NVARCHAR (80)  NULL,
    [Yes_to_Attestation_Questions__c]      VARCHAR (5)    NULL,
    [Yes_to_Questionnaire__c]              VARCHAR (5)    NULL
);

