CREATE TABLE [dbo].[StaffHistoryPrior] (
    [StaffHistoryID]           INT           NULL,
    [ProviderMasterID]         INT           NULL,
    [StaffGroup]               VARCHAR (50)  NULL,
    [StaffSubGroup]            VARCHAR (50)  NULL,
    [StaffArea]                VARCHAR (50)  NULL,
    [StartDate]                DATETIME      NULL,
    [EndDate]                  DATETIME      NULL,
    [WebID]                    INT           NULL,
    [CorporateEmail]           VARCHAR (100) NULL,
    [PersonalEmail]            VARCHAR (100) NULL,
    [ExchangeDirectoryName]    VARCHAR (50)  NULL,
    [ExchangeContainer]        VARCHAR (100) NULL,
    [ExchangeDirectoryName2]   VARCHAR (50)  NULL,
    [ExchangeContainer2]       VARCHAR (100) NULL,
    [StaffStatus]              VARCHAR (50)  NULL,
    [PartnershipLevel]         VARCHAR (100) NULL,
    [PartnershipLevelCode]     VARCHAR (10)  NULL,
    [EchoPartnershipLevelCode] CHAR (10)     NULL,
    [PartnershipLevelDate]     DATETIME      NULL,
    [StateMedicalLicense]      VARCHAR (20)  NULL,
    [ActiveFlag]               CHAR (1)      NULL,
    [SentFlag]                 CHAR (1)      NULL,
    [SentDate]                 DATETIME      NULL,
    [NewHireSentFlag]          CHAR (1)      NULL,
    [NewHireSentDate]          DATETIME      NULL,
    [NewHireInfoSentFlag]      CHAR (1)      NULL,
    [NewHireInfoSentDate]      DATETIME      NULL,
    [LatestWorkDate]           DATETIME      NULL,
    [CreDate]                  DATETIME      CONSTRAINT [DF_StaffHistory_CreDate_1] DEFAULT (getdate()) NULL,
    [UpdDate]                  DATETIME      CONSTRAINT [DF_StaffHistory_UpdDate_1] DEFAULT (getdate()) NULL
);

