CREATE TABLE [dbo].[tblCmp] (
    [CmpKey]          VARCHAR (100) NULL,
    [CmpID]           INT           IDENTITY (1, 1) NOT NULL,
    [CmpSys_CmpID]    INT           NULL,
    [CmpName]         VARCHAR (75)  NULL,
    [CmpCode]         VARCHAR (10)  NULL,
    [CmpAddress1]     VARCHAR (50)  NULL,
    [CmpAddress2]     VARCHAR (50)  NULL,
    [CmpCity]         VARCHAR (30)  NULL,
    [CmpState]        CHAR (2)      NULL,
    [CmpZip]          VARCHAR (10)  NULL,
    [CmpCountry]      VARCHAR (20)  NULL,
    [CmpPhone]        VARCHAR (15)  NULL,
    [CmpFax]          VARCHAR (15)  NULL,
    [CmpWeb]          VARCHAR (50)  NULL,
    [CmpSiteBedNo]    INT           NOT NULL,
    [CmpPhyGrpYN]     BIT           NULL,
    [CmpSysYN]        BIT           NULL,
    [CmpSiteYN]       BIT           NULL,
    [CmpBillAgentYN]  BIT           NULL,
    [CmpMalCarYN]     BIT           NULL,
    [CmpOtherYN]      BIT           NULL,
    [CmpTranscriptYN] BIT           NULL,
    [CmpIPAYN]        BIT           NOT NULL,
    [CmpComment]      TEXT          NULL,
    [CmpDateCreate]   SMALLDATETIME NULL,
    [CmpDateEdit]     SMALLDATETIME NULL,
    [CmpDateInactive] SMALLDATETIME NULL,
    [CmpInactiveYN]   BIT           NULL,
    [CmpFlagYN]       BIT           NULL,
    [zzz]             CHAR (10)     NULL,
    [zzMCID]          INT           NULL
);

