CREATE TABLE [dbo].[TCPIP_Details_SCROSA] (
    [id]         INT            NOT NULL,
    [Uid]        CHAR (10)      NULL,
    [TCID0]      CHAR (4)       NULL,
    [TCID]       CHAR (9)       NOT NULL,
    [dat]        DATETIME       NOT NULL,
    [site]       CHAR (10)      NOT NULL,
    [role]       CHAR (10)      NOT NULL,
    [Tin_A]      CHAR (5)       NOT NULL,
    [Tout_A]     CHAR (5)       NOT NULL,
    [Tin_P]      CHAR (5)       NOT NULL,
    [Tout_P]     CHAR (5)       NOT NULL,
    [Tin_Z]      CHAR (5)       NOT NULL,
    [Tout_Z]     CHAR (5)       NOT NULL,
    [min_wkd_A]  CHAR (6)       NOT NULL,
    [min_wkd_P]  CHAR (6)       NOT NULL,
    [min_wkd_Z]  CHAR (6)       NOT NULL,
    [hrs_wkd]    FLOAT (53)     NOT NULL,
    [hrs_sick]   FLOAT (53)     NOT NULL,
    [hrs_vac]    FLOAT (53)     NOT NULL,
    [hrs_hol]    FLOAT (53)     NOT NULL,
    [hrs_oth]    FLOAT (53)     NOT NULL,
    [type]       CHAR (5)       NOT NULL,
    [hrs_mkup]   FLOAT (53)     NOT NULL,
    [isLocked]   VARCHAR (3)    NOT NULL,
    [isApproved] VARCHAR (3)    NOT NULL,
    [time_stmp]  DATETIME       NOT NULL,
    [admnName]   VARCHAR (50)   NOT NULL,
    [commnt]     VARCHAR (1000) NOT NULL,
    [flag]       CHAR (1)       NOT NULL,
    [bonus1]     FLOAT (53)     NULL,
    [bonus2]     FLOAT (53)     NULL
);

