CREATE TABLE [dbo].[TCPIP_Details_NX_MA] (
    [id]         INT            NOT NULL,
    [Uid]        CHAR (10)      NOT NULL,
    [TCID0]      CHAR (4)       NULL,
    [TCID]       CHAR (9)       NULL,
    [dat]        DATETIME       NOT NULL,
    [Tin_A]      CHAR (5)       NOT NULL,
    [Tout_A]     CHAR (5)       NOT NULL,
    [Tin_P]      CHAR (5)       NOT NULL,
    [Tout_P]     CHAR (5)       NOT NULL,
    [min_wkd_A]  CHAR (6)       NOT NULL,
    [min_wkd_P]  CHAR (6)       NOT NULL,
    [hrs_wkd]    CHAR (6)       NOT NULL,
    [hrs_sick]   CHAR (6)       NOT NULL,
    [hrs_vac]    CHAR (6)       NOT NULL,
    [hrs_hol]    CHAR (6)       NOT NULL,
    [hrs_oth]    CHAR (6)       NOT NULL,
    [hrs_mkup]   CHAR (6)       NOT NULL,
    [hrs_TOT]    CHAR (6)       NOT NULL,
    [hrs_STT]    CHAR (6)       NOT NULL,
    [hrs_OT]     CHAR (6)       NOT NULL,
    [hrs_DT]     CHAR (6)       NOT NULL,
    [type]       CHAR (10)      NULL,
    [isLocked]   CHAR (1)       NOT NULL,
    [isApproved] CHAR (1)       NOT NULL,
    [time_stmp]  DATETIME       NOT NULL,
    [admnName]   VARCHAR (50)   NOT NULL,
    [commnt]     VARCHAR (1000) NOT NULL,
    [flag]       CHAR (1)       NOT NULL
);

