CREATE TABLE [dbo].[Test_PAEMPOS] (
    [COMPANY]        SMALLINT        NOT NULL,
    [EMPLOYEE]       INT             NOT NULL,
    [R_POSITION]     CHAR (12)       NOT NULL,
    [POS_LEVEL]      SMALLINT        NOT NULL,
    [FTE]            DECIMAL (11, 6) NOT NULL,
    [EFFECT_DATE]    DATETIME        NOT NULL,
    [END_DATE]       DATETIME        NOT NULL,
    [JOB_CODE]       CHAR (9)        NOT NULL,
    [PROCESS_LEVEL]  CHAR (5)        NOT NULL,
    [DEPARTMENT]     CHAR (5)        NOT NULL,
    [PAY_RATE]       DECIMAL (13, 4) NOT NULL,
    [USER_LEVEL]     CHAR (10)       NOT NULL,
    [LOCAT_CODE]     CHAR (10)       NOT NULL,
    [SUPERVISOR]     CHAR (10)       NOT NULL,
    [SUPERVISOR_IND] CHAR (10)       NOT NULL,
    [UNION_CODE]     CHAR (10)       NOT NULL,
    [BARGAIN_UNIT]   CHAR (10)       NOT NULL,
    [DATE_ASSIGN]    DATETIME        NOT NULL,
    [WORK_SCHED]     CHAR (10)       NOT NULL,
    [SHIFT]          TINYINT         NOT NULL,
    [SCHEDULE]       CHAR (9)        NOT NULL,
    [PAY_GRADE]      CHAR (3)        NOT NULL,
    [PAY_STEP]       SMALLINT        NOT NULL,
    [EXP_COMPANY]    SMALLINT        NOT NULL,
    [EXP_ACCT_UNIT]  CHAR (15)       NOT NULL,
    [EXP_ACCOUNT]    INT             NOT NULL,
    [EXP_SUB_ACCT]   SMALLINT        NOT NULL,
    [ACTIVITY]       CHAR (15)       NOT NULL,
    [ACCT_CATEGORY]  CHAR (5)        NOT NULL,
    [POS_EFF_DT]     DATETIME        NOT NULL,
    [ANNUAL_HOURS]   SMALLINT        NOT NULL,
    [PRO_RATE_A_SAL] DECIMAL (13, 4) NOT NULL,
    [DATE_STAMP]     DATETIME        NOT NULL,
    [TIME_STAMP]     DECIMAL (6)     NOT NULL,
    [USER_ID]        CHAR (10)       NOT NULL,
    [CURRENCY_CODE]  CHAR (5)        NOT NULL,
    [CURR_ND]        TINYINT         NOT NULL,
    [BASE_CURRENCY]  CHAR (5)        NOT NULL,
    [BASE_ND]        TINYINT         NOT NULL,
    [BASE_PAY_RATE]  DECIMAL (13, 4) NOT NULL,
    [USER_AMOUNT]    DECIMAL (13, 4) NOT NULL,
    [L_INDEX]        CHAR (4)        NOT NULL,
    [PEPSET2_SS_SW]  CHAR (1)        NOT NULL,
    [PEPSET6_SS_SW]  CHAR (1)        NOT NULL,
    [PEPSET7_SS_SW]  CHAR (1)        NOT NULL,
    [PEPSET9_SS_SW]  CHAR (1)        NOT NULL,
    [L_ATPEP_SS_SW]  CHAR (1)        NOT NULL
);

