CREATE TABLE [dbo].[WebBenefitsEnrollment] (
    [Term Date]             VARCHAR (255) NULL,
    [Master ID #]           VARCHAR (255) NULL,
    [Division]              VARCHAR (255) NULL,
    [First Name]            VARCHAR (255) NULL,
    [Last Name]             VARCHAR (255) NULL,
    [Title]                 VARCHAR (255) NULL,
    [Address]               VARCHAR (255) NULL,
    [City]                  VARCHAR (255) NULL,
    [State]                 VARCHAR (255) NULL,
    [Postal Code]           VARCHAR (255) NULL,
    [Social Security]       VARCHAR (255) NULL,
    [DOB]                   VARCHAR (255) NULL,
    [DOH]                   VARCHAR (255) NULL,
    [DOH2]                  VARCHAR (255) NULL,
    [e-mail address]        VARCHAR (255) NULL,
    [Status]                VARCHAR (255) NULL,
    [Year-to-date Hours]    VARCHAR (255) NULL,
    [Year-To-Date Earnings] VARCHAR (255) NULL,
    [ Annualized Salary]    VARCHAR (255) NULL,
    [ Avg. Mo. Salary]      VARCHAR (255) NULL,
    [ Health Plan]          VARCHAR (255) NULL,
    [Health Coverage]       VARCHAR (255) NULL,
    [Medical 2004]          VARCHAR (255) NULL,
    [Medical 2005]          VARCHAR (255) NULL,
    [Dental Plan]           VARCHAR (255) NULL,
    [Dental 2004]           VARCHAR (255) NULL,
    [Dental 2005]           VARCHAR (255) NULL,
    [Vision 2004]           VARCHAR (255) NULL,
    [Vision 2005]           VARCHAR (255) NULL,
    [MSA or FSA 2004]       VARCHAR (255) NULL,
    [HSA or FSA 2005]       VARCHAR (255) NULL,
    [401(k) % 2003]         VARCHAR (255) NULL,
    [401(k) Flat]           VARCHAR (255) NULL,
    [SV]                    VARCHAR (255) NULL,
    [Pim]                   VARCHAR (255) NULL,
    [Inv]                   VARCHAR (255) NULL,
    [Bal]                   VARCHAR (255) NULL,
    [Int]                   VARCHAR (255) NULL,
    [LCV]                   VARCHAR (255) NULL,
    [Wil]                   VARCHAR (255) NULL,
    [To Stk]                VARCHAR (255) NULL,
    [Van EX]                VARCHAR (255) NULL,
    [Cal]                   VARCHAR (255) NULL,
    [SDA]                   VARCHAR (255) NULL,
    [Total]                 VARCHAR (255) NULL,
    [LTD Benefit Amount]    VARCHAR (255) NULL,
    [LTD 2004]              VARCHAR (255) NULL,
    [LTD 2005]              VARCHAR (255) NULL,
    [Employer FSA]          VARCHAR (255) NULL,
    [Employee FSA]          VARCHAR (255) NULL,
    [Employer HSA]          VARCHAR (255) NULL,
    [Employee HSA]          VARCHAR (255) NULL,
    [DCAP 2004]             VARCHAR (255) NULL,
    [DCAP 2005]             VARCHAR (255) NULL,
    [Life Ins 2004]         VARCHAR (255) NULL,
    [Life Ins 2005]         VARCHAR (255) NULL,
    [Dep Life 2004]         VARCHAR (255) NULL,
    [Dep Life 2005]         VARCHAR (255) NULL,
    [Supp Life 2004]        VARCHAR (255) NULL,
    [Supp Life 2005]        VARCHAR (255) NULL
);

