CREATE TABLE [dbo].[WebBenefitsimport_table] (
    [id]                   INT            NULL,
    [Company]              NVARCHAR (255) NULL,
    [FirstName]            NVARCHAR (255) NULL,
    [LastName]             NVARCHAR (255) NULL,
    [sufffix]              NVARCHAR (255) NULL,
    [Address]              NVARCHAR (255) NULL,
    [City]                 NVARCHAR (255) NULL,
    [State]                NVARCHAR (255) NULL,
    [Zipcode]              FLOAT (53)     NULL,
    [SSN]                  VARCHAR (20)   NULL,
    [DOB]                  DATETIME       NULL,
    [DOH]                  SMALLDATETIME  NULL,
    [Status]               NVARCHAR (255) NULL,
    [ytd_hrs]              FLOAT (53)     NULL,
    [ytd_earn]             FLOAT (53)     NULL,
    [annual_salary]        FLOAT (53)     NULL,
    [health]               NVARCHAR (255) NULL,
    [medical]              FLOAT (53)     NULL,
    [dental]               FLOAT (53)     NULL,
    [vision]               FLOAT (53)     NULL,
    [msa]                  FLOAT (53)     NULL,
    [401k]                 FLOAT (53)     NULL,
    [MM]                   FLOAT (53)     NULL,
    [Pim]                  FLOAT (53)     NULL,
    [Inv]                  FLOAT (53)     NULL,
    [Bal]                  FLOAT (53)     NULL,
    [Int]                  FLOAT (53)     NULL,
    [LCV]                  FLOAT (53)     NULL,
    [CS]                   FLOAT (53)     NULL,
    [Index]                FLOAT (53)     NULL,
    [Frnk]                 FLOAT (53)     NULL,
    [Nav]                  FLOAT (53)     NULL,
    [SDA]                  FLOAT (53)     NULL,
    [Tot]                  FLOAT (53)     NULL,
    [monthly_ltd]          FLOAT (53)     NULL,
    [annual_dcap]          FLOAT (53)     NULL,
    [ProviderMasterID]     INT            NULL,
    [LTDBenefitAmount]     FLOAT (53)     NULL,
    [LTDMax]               FLOAT (53)     NULL,
    [HealthPlan]           NVARCHAR (255) NULL,
    [DentalPlan]           NVARCHAR (255) NULL,
    [AverageMonthlySalary] FLOAT (53)     NULL,
    [EmployerFSA]          FLOAT (53)     NULL,
    [EmployeeFSA]          FLOAT (53)     NULL,
    [EmployerHSA]          FLOAT (53)     NULL,
    [EmployeeHSA]          FLOAT (53)     NULL,
    [LifeInsurance]        FLOAT (53)     NULL,
    [DepLifeInsurance]     FLOAT (53)     NULL,
    [SuppLifeInsurance]    FLOAT (53)     NULL,
    [X]                    VARCHAR (1)    NULL
);

