CREATE TABLE [dbo].[WebCPACEvalStaging] (
    [ProviderMasterID]                INT             NULL,
    [MDProviderMasterID]              INT             NULL,
    [RDProviderMasterID]              INT             NULL,
    [PhysicianName]                   VARCHAR (100)   NULL,
    [HospitalClinic]                  VARCHAR (100)   NULL,
    [DeptDirector]                    VARCHAR (100)   NULL,
    [DateOfEmployment]                DATETIME        NULL,
    [BoardStatus]                     VARCHAR (40)    NULL,
    [CredentialsCurrent]              VARCHAR (20)    NULL,
    [DateLevel1]                      DATETIME        NULL,
    [CurrentLevelandDate]             VARCHAR (100)   NULL,
    [AdvancementLevel]                VARCHAR (100)   NULL,
    [EligibilityDate]                 DATETIME        NULL,
    [Hours]                           NUMERIC (10, 2) NULL,
    [AcceleratedAdvancement]          VARCHAR (20)    NULL,
    [CategorySelfEvaluation]          VARCHAR (100)   NULL,
    [SelfHospitalsYes]                VARCHAR (1000)  NULL,
    [SelfSocietiesYes]                VARCHAR (1000)  NULL,
    [SelfConductYes]                  VARCHAR (1000)  NULL,
    [SelfDatabankYes]                 VARCHAR (1000)  NULL,
    [SelfGovActionYes]                VARCHAR (1000)  NULL,
    [SelfHealthYes]                   VARCHAR (1000)  NULL,
    [SelfInsuranceYes]                VARCHAR (1000)  NULL,
    [SelfClaimsYes]                   VARCHAR (1000)  NULL,
    [SelfOutsideActYes]               VARCHAR (200)   NULL,
    [SelfDateComplete]                DATETIME        NULL,
    [SelfExplanationAffirmative]      VARCHAR (8000)  NULL,
    [SelfClaimsInformation]           VARCHAR (8000)  NULL,
    [SelfOutsideActivitiesDescr]      VARCHAR (200)   NULL,
    [SelfOutsideVolunteerDescr]       VARCHAR (8000)  NULL,
    [SelfOutsideOtherDescr]           VARCHAR (8000)  NULL,
    [SelfACCDetails]                  VARCHAR (8000)  NULL,
    [MDAdvancementRecommended]        VARCHAR (100)   NULL,
    [MDImprovementExpectedYes]        VARCHAR (200)   NULL,
    [MDCategoriesImprovementExpected] VARCHAR (50)    NULL,
    [MDAssessmentCategory]            VARCHAR (200)   NULL,
    [MDAssessment]                    VARCHAR (8000)  NULL,
    [MDSuggestionCategory]            VARCHAR (200)   NULL,
    [MDSuggestion]                    VARCHAR (8000)  NULL,
    [MDCommentsbyEvaluee]             VARCHAR (8000)  NULL,
    [MDCommentsbyEvalueeCategory]     VARCHAR (200)   NULL,
    [MDDateComplete]                  DATETIME        NULL,
    [RDEvalBasedUpon]                 VARCHAR (100)   NULL,
    [RDEvalBasedUponCategory]         VARCHAR (100)   NULL,
    [RDOverallComments]               VARCHAR (8000)  NULL,
    [RDOverallCommentsQ]              VARCHAR (100)   NULL,
    [RDCommentsStandards]             VARCHAR (8000)  NULL,
    [RDCommentsStandardsQ]            VARCHAR (200)   NULL,
    [RDLeadership]                    VARCHAR (200)   NULL,
    [RDLeadershipComments]            VARCHAR (8000)  NULL,
    [RDSatisfactory]                  VARCHAR (200)   NULL,
    [RDSatisfactoryComments]          VARCHAR (8000)  NULL,
    [RDRecommend]                     VARCHAR (200)   NULL,
    [RDRecommendComments]             VARCHAR (8000)  NULL,
    [RDDateComplete]                  DATETIME        NULL
);

