CREATE TABLE [dbo].[WebCPACEvaluStaging] (
    [EvaluationID]         INT             NULL,
    [ProviderMasterID]     INT             NULL,
    [MDProviderMasterID]   INT             NULL,
    [RDProviderMasterID]   INT             NULL,
    [SelfCompleteDate]     DATETIME        NULL,
    [MDCompleteDate]       DATETIME        NULL,
    [RDCompleteDate]       DATETIME        NULL,
    [PhysicianName]        VARCHAR (100)   NULL,
    [HospitalClinic]       VARCHAR (100)   NULL,
    [MedDirName]           VARCHAR (100)   NULL,
    [RegDirName]           VARCHAR (100)   NULL,
    [DateofEmployment]     DATETIME        NULL,
    [BoardStatus]          VARCHAR (40)    NULL,
    [CredentialsCurrent]   VARCHAR (20)    NULL,
    [DateLevel1]           DATETIME        NULL,
    [CurrentLevelandDate]  VARCHAR (100)   NULL,
    [AdvancementLevel]     VARCHAR (100)   NULL,
    [EligibilityDate]      DATETIME        NULL,
    [Hours]                NUMERIC (10, 2) NULL,
    [AcceleratedAdv]       VARCHAR (20)    NULL,
    [CategorySelfEval]     VARCHAR (100)   NULL,
    [SelfPeriod]           VARCHAR (300)   NULL,
    [SelfHospPriv]         VARCHAR (300)   NULL,
    [SelfHospDiscip]       VARCHAR (300)   NULL,
    [SelfHospModPriv]      VARCHAR (300)   NULL,
    [SelfSocComplaint]     VARCHAR (300)   NULL,
    [SelfSocDiscip]        VARCHAR (300)   NULL,
    [SelfSocDeny]          VARCHAR (300)   NULL,
    [SelfConductDiscip]    VARCHAR (300)   NULL,
    [SelfDatabank]         VARCHAR (300)   NULL,
    [SelfGovInvestig]      VARCHAR (300)   NULL,
    [SelfGovFelony]        VARCHAR (300)   NULL,
    [SelfGovDUI]           VARCHAR (300)   NULL,
    [SelfHealthDiag]       VARCHAR (300)   NULL,
    [SelfHealthDrugs]      VARCHAR (300)   NULL,
    [SelfHealthPhys]       VARCHAR (300)   NULL,
    [SelfHealthImpair]     VARCHAR (300)   NULL,
    [SelfInsCov]           VARCHAR (300)   NULL,
    [SelfClaimInCEP]       VARCHAR (300)   NULL,
    [SelfClaimOutCEP]      VARCHAR (300)   NULL,
    [SelfActPlaintiff]     VARCHAR (300)   NULL,
    [SelfActDef]           VARCHAR (300)   NULL,
    [SelfActOther]         VARCHAR (300)   NULL,
    [SelfActOtherCEP]      VARCHAR (300)   NULL,
    [SelfExplanation]      VARCHAR (300)   NULL,
    [SelfClaimExplanation] VARCHAR (300)   NULL,
    [SelfEMSWork]          VARCHAR (300)   NULL,
    [SelfAmbFire]          VARCHAR (300)   NULL,
    [SelfPlaintiffExpert]  VARCHAR (300)   NULL,
    [SelfDefenseExpert]    VARCHAR (300)   NULL,
    [SelfGovAppointee]     VARCHAR (300)   NULL,
    [SelfMedSoc]           VARCHAR (300)   NULL,
    [SelfBoardMember]      VARCHAR (300)   NULL,
    [SelfVolunteer]        VARCHAR (300)   NULL,
    [SelfQIRM]             VARCHAR (300)   NULL,
    [SelfSports]           VARCHAR (300)   NULL,
    [SelfOther]            VARCHAR (300)   NULL,
    [SelfOtherDesc]        VARCHAR (8000)  NULL,
    [SelfVolunteerDesc]    VARCHAR (8000)  NULL,
    [SelfUCSite]           VARCHAR (300)   NULL,
    [SelfUCLoc]            VARCHAR (300)   NULL,
    [SelfUCDept]           VARCHAR (300)   NULL,
    [SelfUCHoursMo]        VARCHAR (300)   NULL,
    [SelfUCDateHire]       VARCHAR (300)   NULL,
    [SelfUCEmployer]       VARCHAR (300)   NULL,
    [MDClinRes]            VARCHAR (300)   NULL,
    [MDClinDocum]          VARCHAR (300)   NULL,
    [MDClinQual]           VARCHAR (300)   NULL,
    [MDPSScore]            VARCHAR (300)   NULL,
    [MDPSComplaint]        VARCHAR (300)   NULL,
    [MDRMClaims]           VARCHAR (300)   NULL,
    [MDRMCobra]            VARCHAR (300)   NULL,
    [MDLocal]              VARCHAR (300)   NULL,
    [MDFiduEducation]      VARCHAR (300)   NULL,
    [MDFiduConduct]        VARCHAR (300)   NULL,
    [MDClinPerSkills]      VARCHAR (300)   NULL,
    [MDTechSkills]         VARCHAR (300)   NULL,
    [MDProComm]            VARCHAR (300)   NULL,
    [MDProDemeanor]        VARCHAR (300)   NULL,
    [MDTeamSkills]         VARCHAR (300)   NULL,
    [MDOverallPerform]     VARCHAR (300)   NULL,
    [MDAssessment]         VARCHAR (8000)  NULL,
    [MDSuggestion]         VARCHAR (8000)  NULL,
    [MDRecommend]          VARCHAR (300)   NULL,
    [MDCommentsbyEvaluee]  VARCHAR (8000)  NULL,
    [RDBasedPers]          VARCHAR (300)   NULL,
    [RDBasedDir]           VARCHAR (300)   NULL,
    [RDBasedEDPhys]        VARCHAR (300)   NULL,
    [RDBasedNursing]       VARCHAR (300)   NULL,
    [RDCommentsOverall]    VARCHAR (8000)  NULL,
    [RDCommentsCEP]        VARCHAR (8000)  NULL,
    [RDLeadership]         VARCHAR (300)   NULL,
    [RDLeadershipReason]   VARCHAR (8000)  NULL,
    [RDPerformance]        VARCHAR (300)   NULL,
    [RDPerformanceReason]  VARCHAR (8000)  NULL,
    [RDRecommend]          VARCHAR (300)   NULL,
    [RDRecommendReason]    VARCHAR (8000)  NULL
);

