CREATE TABLE [dbo].[WebTC_detail] (
    [id]            INT            NOT NULL,
    [site]          CHAR (4)       NOT NULL,
    [dat]           SMALLDATETIME  NOT NULL,
    [uid]           CHAR (10)      NOT NULL,
    [Baserate_A]    VARCHAR (10)   NULL,
    [Nitediff_A]    VARCHAR (10)   NULL,
    [Evngdiff_A]    VARCHAR (10)   NULL,
    [Wknddiff_A]    VARCHAR (10)   NULL,
    [Baserate_B]    VARCHAR (10)   NULL,
    [Nitediff_B]    VARCHAR (10)   NULL,
    [Evngdiff_B]    VARCHAR (10)   NULL,
    [Wknddiff_B]    VARCHAR (10)   NULL,
    [mtgHr]         FLOAT (53)     NOT NULL,
    [Mtgrate]       VARCHAR (10)   NOT NULL,
    [Bonuspay]      VARCHAR (10)   NULL,
    [bonusNotes]    VARCHAR (1000) NULL,
    [Projstipend]   VARCHAR (10)   NULL,
    [units1]        VARCHAR (10)   NULL,
    [Unitrate1]     VARCHAR (10)   NULL,
    [type1]         VARCHAR (50)   NULL,
    [note1]         VARCHAR (1000) NULL,
    [units2]        VARCHAR (10)   NULL,
    [unitrate2]     VARCHAR (10)   NULL,
    [type2]         VARCHAR (10)   NULL,
    [note2]         VARCHAR (1000) NULL,
    [BaseRate_N]    FLOAT (53)     NULL,
    [BaseRate_BN]   FLOAT (53)     NULL,
    [NiteDiff_N]    FLOAT (53)     NULL,
    [NiteDiff_BN]   FLOAT (53)     NULL,
    [Evngdiff_N]    FLOAT (53)     NULL,
    [Evngdiff_BN]   FLOAT (53)     NULL,
    [Wknddiff_N]    FLOAT (53)     NULL,
    [Wknddiff_BN]   FLOAT (53)     NULL,
    [MtgRate_N]     FLOAT (53)     NULL,
    [BonusPay_N]    FLOAT (53)     NULL,
    [units1_n]      FLOAT (53)     NULL,
    [units1rate_N]  FLOAT (53)     NULL,
    [units2_n]      FLOAT (53)     NULL,
    [units2rate_N]  FLOAT (53)     NULL,
    [Projstipend_N] FLOAT (53)     NULL
);

