CREATE LOGIN [LawsonLinks]
    WITH PASSWORD = N'wfo{q1hdM}o<lxfyubxCAvRhmsFT7_&#$!~<Tx{?kgwea|^k', SID = 0x18DF12118FAE2F4E8D828003F6D5FEDA, DEFAULT_DATABASE = [LAWDATASTAGE], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

