CREATE VIEW dbo.vw_MEDAMERICA_GLACTUALvsBUDGET
AS
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 1 AS PERIOD, 1 AS QTR, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 AS ACTUAL, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 AS ACT_QTD, 0 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 AS ACT_YTD, 0 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 1 AS PERIOD, 1 AS QTR, 0 AS ACTUAL, 
                      CR_UNITS_01 + DB_UNITS_01 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, CR_UNITS_01 + DB_UNITS_01 AS QTY_QTD, 
                      0 AS BUD_QTD, 0 AS BUDQTY_QTD, 0 AS ACT_YTD, CR_UNITS_01 + DB_UNITS_01 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 1 AS PERIOD, 1 AS QTR, 0 AS ACTUAL, 0 AS ACTQTY, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 AS BUDGET, CR_UNITS_01 + DB_UNITS_01 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 AS BUD_QTD, CR_UNITS_01 + DB_UNITS_01 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 AS BUD_YTD, CR_UNITS_01 + DB_UNITS_01 AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 2 AS PERIOD, 1 AS QTR, 
                      CR_AMOUNT_02 + DB_AMOUNT_02 AS ACTUAL, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 AS ACT_QTD, 0 AS QTY_QTD, 
                      0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 AS ACT_YTD, 0 AS QTY_YTD, 
                      0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS AS GLAMOUNTS_11
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 2 AS PERIOD, 1 AS QTR, 0 AS ACTUAL, 
                      CR_UNITS_02 + DB_UNITS_02 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 0 AS ACT_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS AS GLUNITS_11
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 2 AS PERIOD, 1 AS QTR, 0 AS ACTUAL, 0 AS ACTQTY, 
                      CR_AMOUNT_02 + DB_AMOUNT_02 AS BUDGET, CR_UNITS_02 + DB_UNITS_02 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 AS BUD_QTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 AS BUD_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL AS FBDETAIL_11
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 3 AS PERIOD, 1 AS QTR, 
                      CR_AMOUNT_03 + DB_AMOUNT_03 AS ACTUAL, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 AS ACT_QTD,
                       0 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 AS ACT_YTD,
                       0 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS AS GLAMOUNTS_10
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 3 AS PERIOD, 1 AS QTR, 0 AS ACTUAL, 
                      CR_UNITS_03 + DB_UNITS_03 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      0 AS ACT_YTD, CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 AS QTY_YTD, 0 AS BUD_YTD, 
                      0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS AS GLUNITS_10
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 3 AS PERIOD, 1 AS QTR, 0 AS ACTUAL, 0 AS ACTQTY, 
                      CR_AMOUNT_03 + DB_AMOUNT_03 AS BUDGET, CR_UNITS_03 + DB_UNITS_03 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 AS BUD_QTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 AS BUD_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL AS FBDETAIL_10
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 4 AS PERIOD, 2 AS QTR, 
                      CR_AMOUNT_04 + DB_AMOUNT_04 AS ACTUAL, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, CR_AMOUNT_04 + DB_AMOUNT_04 AS ACT_QTD, 
                      0 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04
                       + DB_AMOUNT_04 AS ACT_YTD, 0 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS AS GLAMOUNTS_9
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 4 AS PERIOD, 2 AS QTR, 0 AS ACTUAL, 
                      CR_UNITS_04 + DB_UNITS_04 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, CR_UNITS_04 + DB_UNITS_04 AS QTY_QTD, 
                      0 AS BUD_QTD, 0 AS BUDQTY_QTD, 0 AS ACT_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 AS QTY_YTD, 
                      0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS AS GLUNITS_9
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 4 AS PERIOD, 2 AS QTR, 0 AS ACTUAL, 0 AS ACTQTY, 
                      CR_AMOUNT_04 + DB_AMOUNT_04 AS BUDGET, CR_UNITS_04 + DB_UNITS_04 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_04 + DB_AMOUNT_04 AS BUD_QTD, CR_UNITS_04 + DB_UNITS_04 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04 + DB_AMOUNT_04
                       AS BUD_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL AS FBDETAIL_9
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 5 AS PERIOD, 2 AS QTR, 
                      CR_AMOUNT_05 + DB_AMOUNT_05 AS ACTUAL, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 
                      CR_AMOUNT_04 + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 AS ACT_QTD, 0 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04
                       + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 AS ACT_YTD, 0 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS AS GLAMOUNTS_8
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS ACTUAL, 5 AS PERIOD, 2 AS QTR, 0 AS ACT_YTD, 
                      CR_UNITS_05 + DB_UNITS_05 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, 
                      CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 0 AS Expr1, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS AS GLUNITS_8
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 5 AS PERIOD, 2 AS QTR, 0 AS ACTUAL, 0 AS ACTQTY, 
                      CR_AMOUNT_05 + DB_AMOUNT_05 AS BUDGET, CR_UNITS_05 + DB_UNITS_05 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_04 + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 AS BUD_QTD, 
                      CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04 + DB_AMOUNT_04
                       + CR_AMOUNT_05 + DB_AMOUNT_05 AS BUD_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL AS FBDETAIL_8
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS ACTUAL, 6 AS PERIOD, 2 AS QTR, 
                      CR_AMOUNT_06 + DB_AMOUNT_06 AS Expr1, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 
                      CR_AMOUNT_04 + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 AS ACT_QTD, 0 AS QTY_QTD, 
                      0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04
                       + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 AS ACT_YTD, 0 AS QTY_YTD, 0 AS BUD_YTD, 
                      0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS AS GLAMOUNTS_7
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 6 AS PERIOD, 2 AS QTR, 0 AS ACTUAL, 
                      CR_UNITS_06 + DB_UNITS_06 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, 
                      CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05 + CR_UNITS_06 + DB_UNITS_06 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      0 AS ACT_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS AS GLUNITS_7
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 6 AS PERIOD, 2 AS QTR, 0 AS ACTUAL, 0 AS ACTQTY, 
                      CR_AMOUNT_06 + DB_AMOUNT_06 AS BUDGET, CR_UNITS_06 + DB_UNITS_06 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_04 + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 AS BUD_QTD, 
                      CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05 + CR_UNITS_06 + DB_UNITS_06 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04 + DB_AMOUNT_04
                       + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 AS BUD_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL AS FBDETAIL_7
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 7 AS PERIOD, 3 AS QTR, 
                      CR_AMOUNT_07 + DB_AMOUNT_07 AS ACTUAL, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, CR_AMOUNT_07 + DB_AMOUNT_07 AS ACT_QTD, 
                      0 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04
                       + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 AS ACT_YTD, 
                      0 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS AS GLAMOUNTS_6
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS ACTUAL, 7 AS PERIOD, 3 AS QTR, 0 AS ACT_YTD, 
                      CR_UNITS_07 + DB_UNITS_07 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, CR_UNITS_07 + DB_UNITS_07 AS QTY_QTD, 
                      0 AS BUD_QTD, 0 AS BUDQTY_QTD, 0 AS Expr1, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS AS GLUNITS_6
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 7 AS PERIOD, 3 AS QTR, 0 AS ACTUAL, 0 AS ACTQTY, 
                      CR_AMOUNT_07 + DB_AMOUNT_07 AS BUDGET, CR_UNITS_07 + DB_UNITS_07 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_07 + DB_AMOUNT_07 AS BUD_QTD, CR_UNITS_07 + DB_UNITS_07 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04 + DB_AMOUNT_04
                       + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 AS BUD_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL AS FBDETAIL_6
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS ACTUAL, 8 AS PERIOD, 3 AS QTR, 
                      CR_AMOUNT_08 + DB_AMOUNT_08 AS Expr1, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 
                      CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08 + DB_AMOUNT_08 AS ACT_QTD, 0 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04
                       + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08
                       + DB_AMOUNT_08 AS ACT_YTD, 0 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS AS GLAMOUNTS_5
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 8 AS PERIOD, 3 AS QTR, 0 AS ACTUAL, 
                      CR_UNITS_08 + DB_UNITS_08 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, 
                      CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 0 AS ACT_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 AS QTY_YTD, 0 AS BUD_YTD, 
                      0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS AS GLUNITS_5
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 8 AS PERIOD, 3 AS QTR, 0 AS ACTUAL, 0 AS ACTQTY, 
                      CR_AMOUNT_08 + DB_AMOUNT_08 AS BUDGET, CR_UNITS_08 + DB_UNITS_08 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08 + DB_AMOUNT_08 AS BUD_QTD, 
                      CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04 + DB_AMOUNT_04
                       + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08 + DB_AMOUNT_08
                       AS BUD_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL AS FBDETAIL_5
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 9 AS PERIOD, 3 AS QTR, 
                      CR_AMOUNT_09 + DB_AMOUNT_09 AS ACTUAL, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 
                      CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08 + DB_AMOUNT_08 + CR_AMOUNT_09 + DB_AMOUNT_09 AS ACT_QTD, 0 AS QTY_QTD, 
                      0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04
                       + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08
                       + DB_AMOUNT_08 + CR_AMOUNT_09 + DB_AMOUNT_09 AS ACT_YTD, 0 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS AS GLAMOUNTS_4
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS ACTUAL, 9 AS PERIOD, 3 AS QTR, 0 AS ACT_YTD, 
                      CR_UNITS_09 + DB_UNITS_09 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, 
                      CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 + CR_UNITS_09 + DB_UNITS_09 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      0 AS Expr1, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 + CR_UNITS_09 + DB_UNITS_09 AS QTY_YTD, 
                      0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS AS GLUNITS_4
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 9 AS PERIOD, 3 AS QTR, 0 AS ACTUAL, 0 AS ACTQTY, 
                      CR_AMOUNT_09 + DB_AMOUNT_09 AS BUDGET, CR_UNITS_09 + DB_UNITS_09 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08 + DB_AMOUNT_08 + CR_AMOUNT_09 + DB_AMOUNT_09 AS BUD_QTD, 
                      CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 + CR_UNITS_09 + DB_UNITS_09 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04 + DB_AMOUNT_04
                       + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08 + DB_AMOUNT_08
                       + CR_AMOUNT_09 + DB_AMOUNT_09 AS BUD_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 + CR_UNITS_09 + DB_UNITS_09 AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL AS FBDETAIL_4
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS ACTUAL, 10 AS PERIOD, 4 AS QTR, 
                      CR_AMOUNT_10 + DB_AMOUNT_10 AS Expr1, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, CR_AMOUNT_10 + DB_AMOUNT_10 AS ACT_QTD, 
                      0 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04
                       + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08
                       + DB_AMOUNT_08 + CR_AMOUNT_09 + DB_AMOUNT_09 + CR_AMOUNT_10 + DB_AMOUNT_10 AS ACT_YTD, 0 AS QTY_YTD, 0 AS BUD_YTD, 
                      0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS AS GLAMOUNTS_3
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 10 AS PERIOD, 4 AS QTR, 0 AS ACTUAL, 
                      CR_UNITS_10 + DB_UNITS_10 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, CR_UNITS_10 + DB_UNITS_10 AS QTY_QTD, 
                      0 AS BUD_QTD, 0 AS BUDQTY_QTD, 0 AS ACT_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 + CR_UNITS_09 + DB_UNITS_09 + CR_UNITS_10 +
                       DB_UNITS_10 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS AS GLUNITS_3
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 10 AS PERIOD, 4 AS QTR, 0 AS ACTUAL, 
                      0 AS ACTQTY, CR_AMOUNT_10 + DB_AMOUNT_10 AS BUDGET, CR_UNITS_10 + DB_UNITS_10 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_10 + DB_AMOUNT_10 AS BUD_QTD, CR_UNITS_10 + DB_UNITS_10 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04 + DB_AMOUNT_04
                       + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08 + DB_AMOUNT_08
                       + CR_AMOUNT_09 + DB_AMOUNT_09 + CR_AMOUNT_10 + DB_AMOUNT_10 AS BUD_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 + CR_UNITS_09 + DB_UNITS_09 + CR_UNITS_10 +
                       DB_UNITS_10 AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL AS FBDETAIL_3
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 11 AS PERIOD, 4 AS QTR, 
                      CR_AMOUNT_11 + DB_AMOUNT_11 AS ACTUAL, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 
                      CR_AMOUNT_10 + DB_AMOUNT_10 + CR_AMOUNT_11 + DB_AMOUNT_11 AS ACT_QTD, 0 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04
                       + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08
                       + DB_AMOUNT_08 + CR_AMOUNT_09 + DB_AMOUNT_09 + CR_AMOUNT_10 + DB_AMOUNT_10 + CR_AMOUNT_11 + DB_AMOUNT_11 AS ACT_YTD, 
                      0 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS AS GLAMOUNTS_2
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS ACTUAL, 11 AS PERIOD, 4 AS QTR, 0 AS ACT_YTD, 
                      CR_UNITS_11 + DB_UNITS_11 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, 
                      CR_UNITS_10 + DB_UNITS_10 + CR_UNITS_11 + DB_UNITS_11 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 0 AS Expr1, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 + CR_UNITS_09 + DB_UNITS_09 + CR_UNITS_10 +
                       DB_UNITS_10 + CR_UNITS_11 + DB_UNITS_11 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS AS GLUNITS_2
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 11 AS PERIOD, 4 AS QTR, 0 AS ACTUAL, 
                      0 AS ACTQTY, CR_AMOUNT_11 + DB_AMOUNT_11 AS BUDGET, CR_UNITS_11 + DB_UNITS_11 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_10 + DB_AMOUNT_10 + CR_AMOUNT_11 + DB_AMOUNT_11 AS BUD_QTD, 
                      CR_UNITS_10 + DB_UNITS_10 + CR_UNITS_11 + DB_UNITS_11 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04 + DB_AMOUNT_04
                       + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08 + DB_AMOUNT_08
                       + CR_AMOUNT_09 + DB_AMOUNT_09 + CR_AMOUNT_10 + DB_AMOUNT_10 + CR_AMOUNT_11 + DB_AMOUNT_11 AS BUD_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 + CR_UNITS_09 + DB_UNITS_09 + CR_UNITS_10 +
                       DB_UNITS_10 + CR_UNITS_11 + DB_UNITS_11 AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL AS FBDETAIL_2
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS ACTUAL, 12 AS PERIOD, 4 AS QTR, 
                      CR_AMOUNT_12 + DB_AMOUNT_12 AS Expr1, 0 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 
                      CR_AMOUNT_10 + DB_AMOUNT_10 + CR_AMOUNT_11 + DB_AMOUNT_11 + CR_AMOUNT_12 + DB_AMOUNT_12 AS ACT_QTD, 0 AS QTY_QTD, 
                      0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      CR_BEG_BAL + DB_BEG_BAL + CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04
                       + DB_AMOUNT_04 + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08
                       + DB_AMOUNT_08 + CR_AMOUNT_09 + DB_AMOUNT_09 + CR_AMOUNT_10 + DB_AMOUNT_10 + CR_AMOUNT_11 + DB_AMOUNT_11 + CR_AMOUNT_12
                       + DB_AMOUNT_12 AS ACT_YTD, 0 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLAMOUNTS AS GLAMOUNTS_1
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, 0 AS BUDGET_NBR, 12 AS PERIOD, 4 AS QTR, 0 AS ACTUAL, 
                      CR_UNITS_12 + DB_UNITS_12 AS ACTQTY, 0 AS BUDGET, 0 AS BUDQTY, 0 AS ACT_QTD, 
                      CR_UNITS_10 + DB_UNITS_10 + CR_UNITS_11 + DB_UNITS_11 + CR_UNITS_12 + DB_UNITS_12 AS QTY_QTD, 0 AS BUD_QTD, 0 AS BUDQTY_QTD, 
                      0 AS ACT_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 + CR_UNITS_09 + DB_UNITS_09 + CR_UNITS_10 +
                       DB_UNITS_10 + CR_UNITS_11 + DB_UNITS_11 + CR_UNITS_12 + DB_UNITS_12 AS QTY_YTD, 0 AS BUD_YTD, 0 AS BUDQTY_YTD
FROM         PROD.dbo.GLUNITS AS GLUNITS_1
UNION ALL
SELECT     FISCAL_YEAR, COMPANY, ACCT_UNIT, ACCOUNT, SUB_ACCOUNT, VAR_LEVELS, BUDGET_NBR, 12 AS PERIOD, 4 AS QTR, 0 AS ACTUAL, 
                      0 AS ACTQTY, CR_AMOUNT_12 + DB_AMOUNT_12 AS BUDGET, CR_UNITS_12 + DB_UNITS_12 AS BUDQTY, 0 AS ACT_QTD, 0 AS QTY_QTD, 
                      CR_AMOUNT_10 + DB_AMOUNT_10 + CR_AMOUNT_11 + DB_AMOUNT_11 + CR_AMOUNT_12 + DB_AMOUNT_12 AS BUD_QTD, 
                      CR_UNITS_10 + DB_UNITS_10 + CR_UNITS_11 + DB_UNITS_11 + CR_UNITS_12 + DB_UNITS_12 AS BUDQTY_QTD, 0 AS ACT_YTD, 0 AS QTY_YTD, 
                      CR_AMOUNT_01 + DB_AMOUNT_01 + CR_AMOUNT_02 + DB_AMOUNT_02 + CR_AMOUNT_03 + DB_AMOUNT_03 + CR_AMOUNT_04 + DB_AMOUNT_04
                       + CR_AMOUNT_05 + DB_AMOUNT_05 + CR_AMOUNT_06 + DB_AMOUNT_06 + CR_AMOUNT_07 + DB_AMOUNT_07 + CR_AMOUNT_08 + DB_AMOUNT_08
                       + CR_AMOUNT_09 + DB_AMOUNT_09 + CR_AMOUNT_10 + DB_AMOUNT_10 + CR_AMOUNT_11 + DB_AMOUNT_11 + CR_AMOUNT_12 + DB_AMOUNT_12
                       AS BUD_YTD, 
                      CR_UNITS_01 + DB_UNITS_01 + CR_UNITS_02 + DB_UNITS_02 + CR_UNITS_03 + DB_UNITS_03 + CR_UNITS_04 + DB_UNITS_04 + CR_UNITS_05 + DB_UNITS_05
                       + CR_UNITS_06 + DB_UNITS_06 + CR_UNITS_07 + DB_UNITS_07 + CR_UNITS_08 + DB_UNITS_08 + CR_UNITS_09 + DB_UNITS_09 + CR_UNITS_10 +
                       DB_UNITS_10 + CR_UNITS_11 + DB_UNITS_11 + CR_UNITS_12 + DB_UNITS_12 AS BUDQTY_YTD
FROM         PROD.dbo.FBDETAIL AS FBDETAIL_1

GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4[30] 2[40] 3) )"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 3
   End
   Begin DiagramPane = 
      PaneHidden = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 13
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 5
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vw_MEDAMERICA_GLACTUALvsBUDGET';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 1, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vw_MEDAMERICA_GLACTUALvsBUDGET';

