CREATE PROCEDURE [dbo].[usp_LoadWebSiteLineHourly] AS

/*Script populates the hourly rate by site for upload to the web.*/

	DELETE FROM AppStaging.DBO.WEBSITELINEHOURLYSTAGING WHERE CTRBSEHOUR = 0
	DELETE FROM AppStaging.DBO.WEBSITELINEHOURLYSTAGING WHERE CTRID = 22

	UPDATE AppStaging.DBO.WEBSITELINEHOURLYSTAGING
		SET SITELOCATIONID = M.SITELOCATIONID
			FROM AppStaging.DBO.WEBSITELINEHOURLYSTAGING S, PMDBStaging.DBO.SITELOCATIONSITELINEMATCHES M
				WHERE S.CTRID = M.SITELINECTRID

	UPDATE AppStaging.DBO.WEBSITELINEHOURLYSTAGING
		SET WEBCODE = T.WEBCODE, SITELOCATIONNAME = T.SITELOCATIONNAME
			FROM AppStaging.DBO.WEBSITELINEHOURLYSTAGING S, PMDBStaging.DBO.SITELOCATIONLOOKUP T
				WHERE S.SITELOCATIONID = T.SITELOCATIONID

	/*UPDATE WebSiteLineHourlyStaging
		SET MARSPracticeCode = P.MARSPracticeCode
			FROM WebSiteLineHourlyStaging, PMDBStaging.dbo.SiteLocationLookup P
				WHERE WebSiteLineHourlyStaging.WebCode = P.WebCode
					AND P.WebCode is not null*/

	INSERT INTO WEBSTAGING.DBO.WEBSITELINEHOURLY
		(SiteName,
		WebCode,
		SiteLineHourly,
		MARSPracticeCode)
			SELECT 
			SiteLocationName,
			WebCode,
			CtrBseHour,
			MARSPracticeCode
				FROM AppStaging.DBO.WEBSITELINEHOURLYSTAGING
					WHERE SITELOCATIONID IS NOT NULL
