CREATE TABLE [dbo].[AHAData] (
    [Year]                       VARCHAR (50) NULL,
    [AHAID]                      VARCHAR (50) NULL,
    [Medicare Provider ID]       VARCHAR (50) NULL,
    [Hospital Name]              VARCHAR (50) NULL,
    [Address 1 (physical)]       VARCHAR (50) NULL,
    [City Name (physical)]       VARCHAR (50) NULL,
    [State (physical)]           VARCHAR (50) NULL,
    [Zip code (physical)]        VARCHAR (50) NULL,
    [Address 2 (physical)]       VARCHAR (50) NULL,
    [Telephone number]           VARCHAR (50) NULL,
    [Fax Number]                 VARCHAR (50) NULL,
    [Web address]                VARCHAR (50) NULL,
    [CBSA name]                  VARCHAR (50) NULL,
    [CBSA type]                  VARCHAR (50) NULL,
    [Hospital Location]          VARCHAR (50) NULL,
    [Hospital's County name]     VARCHAR (50) NULL,
    [Latitude]                   VARCHAR (50) NULL,
    [Longitude]                  VARCHAR (50) NULL,
    [Control   Ownership Type]   VARCHAR (50) NULL,
    [Primary Service]            VARCHAR (50) NULL,
    [Teaching Affiliation]       VARCHAR (50) NULL,
    [Total hospital beds]        VARCHAR (50) NULL,
    [Admissions (hospital unit)] VARCHAR (50) NULL,
    [Emergency room visits]      VARCHAR (50) NULL,
    [Licensed Beds]              VARCHAR (50) NULL,
    [Emergency Department ]      VARCHAR (50) NULL
);

