CREATE TABLE [dbo].[Equity2014] (
    [Entity]   VARCHAR (50) NULL,
    [MPDB#]    VARCHAR (50) NULL,
    [Lawson#]  VARCHAR (50) NULL,
    [Doc-Name] VARCHAR (50) NULL,
    [1]        VARCHAR (50) NULL,
    [2]        VARCHAR (50) NULL,
    [3]        VARCHAR (50) NULL,
    [4]        VARCHAR (50) NULL,
    [5]        VARCHAR (50) NULL,
    [6]        VARCHAR (50) NULL,
    [7]        VARCHAR (50) NULL,
    [8]        VARCHAR (50) NULL,
    [9]        VARCHAR (50) NULL,
    [10]       VARCHAR (50) NULL,
    [11]       VARCHAR (50) NULL,
    [12]       VARCHAR (50) NULL,
    [12PE]     VARCHAR (50) NULL,
    [13]       VARCHAR (50) NULL,
    [14]       VARCHAR (50) NULL,
    [15]       VARCHAR (50) NULL,
    [15PE]     VARCHAR (50) NULL,
    [16]       VARCHAR (50) NULL,
    [17]       VARCHAR (50) NULL,
    [18]       VARCHAR (50) NULL
);

