CREATE TABLE [dbo].[OE_MD2009] (
    [id]                 INT            NULL,
    [ProviderMasterID]   FLOAT (53)     NULL,
    [TermDate]           NVARCHAR (255) NULL,
    [MasterID]           NVARCHAR (255) NULL,
    [Division]           NVARCHAR (255) NULL,
    [SocialSecurity]     FLOAT (53)     NULL,
    [LastName]           NVARCHAR (255) NULL,
    [FirstName]          NVARCHAR (255) NULL,
    [Digits]             FLOAT (53)     NULL,
    [Address]            NVARCHAR (255) NULL,
    [City]               NVARCHAR (255) NULL,
    [State]              NVARCHAR (255) NULL,
    [PostalCode]         NVARCHAR (255) NULL,
    [DOB]                SMALLDATETIME  NULL,
    [DOH]                SMALLDATETIME  NULL,
    [DOH2]               SMALLDATETIME  NULL,
    [EmailAddress]       SMALLDATETIME  NULL,
    [EStatus]            NVARCHAR (255) NULL,
    [YearToDateHours]    VARCHAR (255)  NULL,
    [YearToDateEarnings] VARCHAR (50)   NULL,
    [AnnualizedSalary]   VARCHAR (53)   NULL,
    [AvgMoSalary]        VARCHAR (53)   NULL,
    [chk]                VARCHAR (200)  NULL,
    [HealthPlan]         VARCHAR (255)  NULL,
    [HealthCoverage]     VARCHAR (255)  NULL,
    [Medical_0]          VARCHAR (53)   NULL,
    [Medical_1]          VARCHAR (53)   NULL,
    [DentalPlan]         VARCHAR (50)   NULL,
    [dentalCoverage]     VARCHAR (50)   NULL,
    [Dental_0]           VARCHAR (53)   NULL,
    [Dental_1]           VARCHAR (53)   NULL,
    [Vision2008]         VARCHAR (50)   NULL,
    [FSA_0]              VARCHAR (53)   NULL,
    [FSA_1]              VARCHAR (53)   NULL,
    [HSA_0]              VARCHAR (53)   NULL,
    [HSA_1]              VARCHAR (53)   NULL,
    [Perc401k]           VARCHAR (53)   NULL,
    [PercRoth]           VARCHAR (53)   NULL,
    [Flat401k]           VARCHAR (53)   NULL,
    [RetireAddition]     VARCHAR (50)   NULL,
    [SV]                 VARCHAR (50)   NULL,
    [Pim]                VARCHAR (50)   NULL,
    [Inv]                VARCHAR (50)   NULL,
    [Bal]                VARCHAR (50)   NULL,
    [Euro]               VARCHAR (50)   NULL,
    [LCV]                VARCHAR (50)   NULL,
    [ToStk]              VARCHAR (50)   NULL,
    [VanEX]              VARCHAR (50)   NULL,
    [Cal]                VARCHAR (50)   NULL,
    [GROFD]              VARCHAR (50)   NULL,
    [SEI]                VARCHAR (50)   NULL,
    [PCRA]               VARCHAR (50)   NULL,
    [fTotal]             VARCHAR (50)   NULL,
    [LTDBenefitAmount]   VARCHAR (50)   NULL,
    [LTD_0]              VARCHAR (50)   NULL,
    [LTDMax]             VARCHAR (50)   NULL,
    [LTD_1]              VARCHAR (50)   NULL,
    [EmployerFSA]        VARCHAR (50)   NULL,
    [EmployerHSA]        VARCHAR (50)   NULL,
    [DCAP_0]             VARCHAR (50)   NULL,
    [DCAP_1]             VARCHAR (50)   NULL,
    [LifeIns_0]          VARCHAR (50)   NULL,
    [LifeIns_1]          VARCHAR (50)   NULL,
    [DepLife_0]          VARCHAR (50)   NULL,
    [DepLife_1]          VARCHAR (50)   NULL,
    [SuppLife_0]         VARCHAR (50)   NULL,
    [SuppLife_1]         VARCHAR (50)   NULL,
    [sign]               VARCHAR (200)  NULL,
    [signDate]           DATETIME       NULL,
    [LawsonID]           VARCHAR (50)   NULL,
    [FullName]           VARCHAR (50)   NULL,
    [Site]               VARCHAR (50)   NULL,
    [HSACatchup_0]       VARCHAR (50)   NULL,
    [HSACatchup_1]       VARCHAR (50)   NULL,
    [FlatRoth]           VARCHAR (50)   NULL,
    [Over50_401KCatchup] VARCHAR (50)   NULL,
    [Over50_RothCatchup] VARCHAR (50)   NULL,
    [Int]                VARCHAR (50)   NULL,
    [SpouseLifeIns_0]    VARCHAR (50)   NULL,
    [SpouseLifeIns_1]    VARCHAR (50)   NULL,
    [LTD_Plan]           VARCHAR (50)   NULL
);

