CREATE TABLE [dbo].[PATSATSTAGING] (
    [PatSatStagingID] INT            NOT NULL,
    [SOURCEUNIQUEID]  CHAR (22)      NOT NULL,
    [I1]              VARCHAR (100)  NOT NULL,
    [I3]              CHAR (5)       NULL,
    [I9]              VARCHAR (20)   NULL,
    [I2]              CHAR (22)      NULL,
    [I6]              VARCHAR (20)   NULL,
    [I7]              VARCHAR (20)   NULL,
    [M1]              INT            NULL,
    [M2]              INT            NULL,
    [M3]              INT            NULL,
    [M4]              INT            NULL,
    [P1]              INT            NULL,
    [P2]              INT            NULL,
    [P3]              INT            NULL,
    [P4]              INT            NULL,
    [P5]              INT            NULL,
    [P6]              INT            NULL,
    [P7]              INT            NULL,
    [N1]              INT            NULL,
    [N2]              INT            NULL,
    [N3]              INT            NULL,
    [N4]              INT            NULL,
    [N5]              INT            NULL,
    [N6]              INT            NULL,
    [N7]              INT            NULL,
    [OS1]             FLOAT (53)     NULL,
    [OS2]             FLOAT (53)     NULL,
    [OS3]             FLOAT (53)     NULL,
    [OS4]             FLOAT (53)     NULL,
    [OS5]             FLOAT (53)     NULL,
    [OS6]             FLOAT (53)     NULL,
    [OS7]             FLOAT (53)     NULL,
    [OS8]             FLOAT (53)     NULL,
    [Z1]              VARCHAR (5000) NULL,
    [Z2]              VARCHAR (400)  NULL,
    [R1]              INT            NULL,
    [R2]              INT            NULL,
    [R3]              INT            NULL,
    [CREDATE]         DATETIME       NULL,
    [UPDDATE]         DATETIME       NULL,
    [Language]        VARCHAR (20)   NULL,
    [CommentID]       VARCHAR (50)   NULL,
    [EXPORT]          INT            NOT NULL
);

