CREATE TABLE [dbo].[WebBonusMarchArchive] (
    [Clock]            VARCHAR (10)    NULL,
    [SSN]              VARCHAR (20)    NULL,
    [StaffGroup]       VARCHAR (10)    NULL,
    [ProviderMasterID] INT             NULL,
    [Name]             VARCHAR (100)   NULL,
    [Address1]         VARCHAR (100)   NULL,
    [Address2]         VARCHAR (100)   NULL,
    [City]             VARCHAR (50)    NULL,
    [State]            VARCHAR (50)    NULL,
    [Zip]              VARCHAR (20)    NULL,
    [PshipIDNumber]    VARCHAR (20)    NULL,
    [PshipName]        VARCHAR (100)   NULL,
    [PshipAdd1]        VARCHAR (100)   NULL,
    [PshipCity]        VARCHAR (50)    NULL,
    [PshipState]       VARCHAR (50)    NULL,
    [PshipZip]         VARCHAR (20)    NULL,
    [Line1]            DECIMAL (18, 4) NULL,
    [Line2]            DECIMAL (18, 4) NULL,
    [Line3]            DECIMAL (18, 4) NULL,
    [Line4]            DECIMAL (18, 4) NULL,
    [Line5]            DECIMAL (18, 4) NULL,
    [Line6]            DECIMAL (18, 4) NULL,
    [Line7]            DECIMAL (18, 4) NULL,
    [Line8]            DECIMAL (18, 4) NULL,
    [Line8a]           DECIMAL (18, 4) NULL,
    [Line8b]           DECIMAL (18, 4) NULL,
    [Line9]            DECIMAL (18, 4) NULL,
    [Line10]           DECIMAL (18, 4) NULL,
    [Credate]          DATETIME        NULL
);

