CREATE TABLE [dbo].[WebBenefitsContributionsArchive] (
    [ProviderMasterID] INT             NULL,
    [LastName]         VARCHAR (100)   NULL,
    [FirstName]        VARCHAR (50)    NULL,
    [Title]            VARCHAR (50)    NULL,
    [IncLineA]         DECIMAL (18, 4) NULL,
    [IncLineB]         DECIMAL (18, 4) NULL,
    [IncLineC]         DECIMAL (18, 4) NULL,
    [IncLineD]         DECIMAL (18, 4) NULL,
    [IncLineE]         DECIMAL (18, 4) NULL,
    [IncLineF]         DECIMAL (18, 4) NULL,
    [IncLineG]         DECIMAL (18, 4) NULL,
    [UnIncLineA]       DECIMAL (18, 4) NULL,
    [UnIncLineB]       DECIMAL (18, 4) NULL,
    [UnIncLineC]       DECIMAL (18, 4) NULL,
    [UnIncLineD]       DECIMAL (18, 4) NULL,
    [UnIncLineE]       DECIMAL (18, 4) NULL,
    [UnIncLineF]       DECIMAL (18, 4) NULL,
    [UnIncLineG]       DECIMAL (18, 4) NULL,
    [UnInclineH]       DECIMAL (18, 4) NULL,
    [UnIncLineI]       DECIMAL (18, 4) NULL,
    [DBLineA]          DECIMAL (18, 4) NULL,
    [DBLineB]          DECIMAL (18, 4) NULL,
    [DBLineC]          DECIMAL (18, 4) NULL,
    [DBLineD]          DECIMAL (18, 4) NULL,
    [IncForm]          CHAR (1)        NULL,
    [UnincForm]        CHAR (1)        NULL,
    [DBForm]           CHAR (1)        NULL,
    [Credate]          DATETIME        CONSTRAINT [DF_WebBenefitsContributionsArchive_Credate] DEFAULT (getdate()) NULL
);

