CREATE TABLE [dbo].[WebBenefitsContributions] (
    [ProviderMasterID] INT             NULL,
    [LastName]         VARCHAR (100)   NULL,
    [FirstName]        VARCHAR (50)    NULL,
    [Title]            VARCHAR (50)    NULL,
    [IncLineA]         NUMERIC (18, 2) NULL,
    [IncLineB]         NUMERIC (18, 2) NULL,
    [IncLineC]         NUMERIC (18, 2) NULL,
    [IncLineD]         NUMERIC (18, 2) NULL,
    [IncLineE]         NUMERIC (18, 2) NULL,
    [IncLineF]         NUMERIC (18, 2) NULL,
    [IncLineG]         NUMERIC (18, 2) NULL,
    [IncLineH]         NUMERIC (18, 2) NULL,
    [IncLineI]         NUMERIC (18, 2) NULL,
    [UnIncLineA]       NUMERIC (18, 2) NULL,
    [UnIncLineB]       NUMERIC (18, 2) NULL,
    [UnIncLineC]       NUMERIC (18, 2) NULL,
    [UnIncLineD]       NUMERIC (18, 2) NULL,
    [UnIncLineE]       NUMERIC (18, 2) NULL,
    [UnIncLineF]       NUMERIC (18, 2) NULL,
    [UnIncLineG]       NUMERIC (18, 2) NULL,
    [UnInclineH]       NUMERIC (18, 2) NULL,
    [UnIncLineI]       NUMERIC (18, 2) NULL,
    [DBLineA]          NUMERIC (18, 2) NULL,
    [DBLineB]          NUMERIC (18, 2) NULL,
    [DBLineC]          NUMERIC (18, 2) NULL,
    [DBLineD]          NUMERIC (18, 2) NULL,
    [IncForm]          CHAR (1)        NULL,
    [UnincForm]        CHAR (1)        NULL,
    [DBForm]           CHAR (1)        NULL,
    [Credate]          DATETIME        CONSTRAINT [DF_WebBenefitsContributions_Credate] DEFAULT (getdate()) NULL
);

