CREATE TABLE [dbo].[WebK12012] (
    [GROUP]              VARCHAR (50) NULL,
    [LawsonID]           VARCHAR (50) NULL,
    [MPDBID]             VARCHAR (50) NULL,
    [Year]               VARCHAR (50) NULL,
    [versionNum]         VARCHAR (50) NULL,
    [ombNum]             VARCHAR (50) NULL,
    [p1a]                VARCHAR (50) NULL,
    [p1bName]            VARCHAR (50) NULL,
    [p1bStreet]          VARCHAR (50) NULL,
    [p1bCity]            VARCHAR (50) NULL,
    [p1bState]           VARCHAR (50) NULL,
    [p1bZip]             VARCHAR (50) NULL,
    [p2e]                VARCHAR (50) NULL,
    [p2fName]            VARCHAR (50) NULL,
    [p2fStreet1]         VARCHAR (50) NULL,
    [p2fStreet2]         VARCHAR (50) NULL,
    [p2fCity]            VARCHAR (50) NULL,
    [p2fState]           VARCHAR (50) NULL,
    [p2fZip]             VARCHAR (50) NULL,
    [p2gGP]              VARCHAR (50) NULL,
    [p2gLP]              VARCHAR (50) NULL,
    [p2hDP]              VARCHAR (50) NULL,
    [p2i1]               VARCHAR (50) NULL,
    [p2i2]               VARCHAR (50) NULL,
    [p2jBegProf]         VARCHAR (50) NULL,
    [p2jEndProf]         VARCHAR (50) NULL,
    [p2jBegLoss]         VARCHAR (50) NULL,
    [p2jEndLoss]         VARCHAR (50) NULL,
    [p2jBegCap]          VARCHAR (50) NULL,
    [p2jEndCap]          VARCHAR (50) NULL,
    [ p2kRec ]           VARCHAR (50) NULL,
    [ p2lBegCap ]        VARCHAR (50) NULL,
    [ p2lCapContrib ]    VARCHAR (50) NULL,
    [ p2lIncrease ]      VARCHAR (50) NULL,
    [ p2lWD ]            VARCHAR (50) NULL,
    [ p2lEndCap ]        VARCHAR (50) NULL,
    [P2lOther]           VARCHAR (50) NULL,
    [P2lOtherNote]       VARCHAR (50) NULL,
    [p2mNo]              VARCHAR (50) NULL,
    [ p31 ]              VARCHAR (50) NULL,
    [ p34 ]              VARCHAR (50) NULL,
    [ p35 ]              VARCHAR (50) NULL,
    [p313Code]           VARCHAR (50) NULL,
    [ p313 ]             VARCHAR (50) NULL,
    [p314code]           VARCHAR (50) NULL,
    [ p314 ]             VARCHAR (50) NULL,
    [p317Code]           VARCHAR (50) NULL,
    [ p317 ]             VARCHAR (50) NULL,
    [p318Code]           VARCHAR (50) NULL,
    [ p318 ]             VARCHAR (50) NULL,
    [p319Code]           VARCHAR (50) NULL,
    [ p319 ]             VARCHAR (50) NULL,
    [p320CCode]          VARCHAR (50) NULL,
    [p320CNote]          VARCHAR (50) NULL,
    [p320Code]           VARCHAR (50) NULL,
    [ p320 ]             VARCHAR (50) NULL,
    [stmt1401k]          VARCHAR (50) NULL,
    [stmt1Roth]          VARCHAR (50) NULL,
    [stmt1DefBen]        VARCHAR (50) NULL,
    [ stmt1DepCare ]     VARCHAR (50) NULL,
    [ stmt1HealthIns ]   VARCHAR (50) NULL,
    [ stmt1HSA ]         VARCHAR (50) NULL,
    [ stmt2OrdInc ]      VARCHAR (50) NULL,
    [ stmt2Interest ]    VARCHAR (50) NULL,
    [ stmt2TotInc ]      VARCHAR (50) NULL,
    [ stmt2CharContrib ] VARCHAR (50) NULL,
    [ stmt2Deds ]        VARCHAR (50) NULL,
    [ stmt2NonDed ]      VARCHAR (50) NULL,
    [ stmt2Other ]       VARCHAR (50) NULL,
    [ stmt2Total ]       VARCHAR (50) NULL,
    [ stmt41c ]          VARCHAR (50) NULL,
    [ stmt420c ]         VARCHAR (50) NULL
);

