CREATE TABLE [dbo].[WebK12011] (
    [Clock]            VARCHAR (10)    NULL,
    [StaffGroup]       VARCHAR (10)    NULL,
    [PartnerTaxID]     VARCHAR (20)    NULL,
    [ProviderMasterID] INT             NULL,
    [Name]             VARCHAR (100)   NULL,
    [Address1]         VARCHAR (100)   NULL,
    [Address2]         VARCHAR (100)   NULL,
    [City]             VARCHAR (50)    NULL,
    [State]            VARCHAR (50)    NULL,
    [Zip]              VARCHAR (20)    NULL,
    [Pship-IDNumber]   VARCHAR (20)    NULL,
    [Pship-Name]       VARCHAR (100)   NULL,
    [Pship-Add1]       VARCHAR (100)   NULL,
    [Pship-City]       VARCHAR (50)    NULL,
    [Pship-St]         VARCHAR (50)    NULL,
    [Pship-Zip]        VARCHAR (20)    NULL,
    [1]                NUMERIC (18, 4) NULL,
    [2]                NUMERIC (18, 4) NULL,
    [3]                NUMERIC (18, 4) NULL,
    [4]                NUMERIC (18, 4) NULL,
    [5]                NUMERIC (18, 4) NULL,
    [6]                NUMERIC (18, 4) NULL,
    [7]                VARCHAR (20)    NULL,
    [8]                VARCHAR (20)    NULL,
    [9]                NUMERIC (18, 4) NULL,
    [10]               NUMERIC (18, 4) NULL,
    [11]               NUMERIC (18, 4) NULL,
    [12]               NUMERIC (18, 4) NULL,
    [13]               NUMERIC (18, 4) NULL,
    [14]               NUMERIC (18, 4) NULL,
    [15]               NUMERIC (18, 4) NULL,
    [15a]              NUMERIC (18, 4) NULL,
    [16]               NUMERIC (18, 4) NULL,
    [17]               NUMERIC (18, 4) NULL,
    [18]               NUMERIC (18, 4) NULL,
    [19a]              VARCHAR (20)    NULL,
    [19b]              VARCHAR (20)    NULL,
    [19c]              NUMERIC (18, 4) NULL,
    [19d]              NUMERIC (18, 4) NULL,
    [19e]              NUMERIC (18, 4) NULL,
    [20]               NUMERIC (18, 4) NULL,
    [21]               NUMERIC (18, 4) NULL,
    [22]               NUMERIC (18, 4) NULL,
    [23]               VARCHAR (20)    NULL,
    [24]               NUMERIC (18, 4) NULL,
    [25]               NUMERIC (18, 4) NULL,
    [26]               NUMERIC (18, 4) NULL,
    [Credate]          DATETIME        CONSTRAINT [DF_WebK12011_Credate] DEFAULT (getdate()) NULL
);

