CREATE TABLE [dbo].[PendingContracts] (
    [StaffGroupStatus]                    VARCHAR (200) NULL,
    [LastName]                            VARCHAR (100) NULL,
    [FirstName]                           VARCHAR (100) NULL,
    [Title]                               VARCHAR (100) NULL,
    [InsurancePlanCode]                   VARCHAR (100) NULL,
    [InsurancePlanName]                   VARCHAR (200) NULL,
    [SiteName]                            VARCHAR (200) NULL,
    [InsurancePlanPinNbr]                 VARCHAR (100) NULL,
    [InsurancePlanGroupNbr]               VARCHAR (100) NULL,
    [ApplicationMailedtoPhysicianDate]    DATETIME      NULL,
    [ApplicationDuebyPhysician]           DATETIME      NULL,
    [ApplicationReceivedbyPhysician]      DATETIME      NULL,
    [ApplicationMailedtoPayer]            DATETIME      NULL,
    [FollowupWithPayer]                   DATETIME      NULL,
    [InsurancePlanEffectiveDate]          DATETIME      NULL,
    [ProviderMasterID]                    INT           NULL,
    [Site1FirstWorked]                    VARCHAR (100) NULL,
    [Site2FirstWorked]                    VARCHAR (100) NULL,
    [Site3FirstWorked]                    VARCHAR (100) NULL,
    [Site4FirstWorked]                    VARCHAR (100) NULL,
    [Site5FirstWorked]                    VARCHAR (100) NULL,
    [Site6FirstWorked]                    VARCHAR (100) NULL,
    [Site7FirstWorked]                    VARCHAR (100) NULL,
    [Site8FirstWorked]                    VARCHAR (100) NULL,
    [ApplicationMailedtoPhysicianDateNew] VARCHAR (100) NULL,
    [ApplicationDuebyPhysicianNew]        VARCHAR (100) NULL,
    [ApplicationReceivedbyPhysicianNew]   VARCHAR (100) NULL,
    [ApplicationMailedtoPayerNew]         VARCHAR (100) NULL,
    [FollowupWithPayerNew]                VARCHAR (100) NULL,
    [InsurancePlanEffectiveDateNew]       VARCHAR (100) NULL,
    [Comments]                            VARCHAR (100) NULL
);

