CREATE TABLE [dbo].[PhysicianEchoAddressCurrent] (
    [dr_id]       CHAR (12)     NOT NULL,
    [fac_cd]      CHAR (4)      NULL,
    [sch_type]    CHAR (5)      NOT NULL,
    [addr]        CHAR (30)     NOT NULL,
    [AddrNew]     VARCHAR (255) NULL,
    [AddrCompare] VARCHAR (255) NULL,
    [addr2]       CHAR (30)     NOT NULL,
    [city]        CHAR (20)     NOT NULL,
    [state]       CHAR (2)      NOT NULL,
    [zip]         CHAR (10)     NOT NULL,
    [loc_code]    CHAR (3)      NULL,
    [phone]       CHAR (14)     NULL,
    [cmt]         CHAR (40)     NULL,
    [extension]   CHAR (5)      NULL,
    [override]    BIT           NULL,
    [phone2]      CHAR (14)     NULL,
    [extension2]  CHAR (5)      NULL,
    [tax_id]      CHAR (15)     NULL,
    [sub_tax_id]  CHAR (8)      NULL,
    [tied_tax]    BIT           NULL,
    [p_type]      CHAR (5)      NULL,
    [evenings]    BIT           NULL,
    [sun_s1]      CHAR (8)      NULL,
    [sun_e1]      CHAR (8)      NULL,
    [sun_s2]      CHAR (8)      NULL,
    [sun_e2]      CHAR (8)      NULL,
    [sun_hrs]     SMALLINT      NULL,
    [sun_eve]     BIT           NULL,
    [mon_s1]      CHAR (8)      NULL,
    [mon_e1]      CHAR (8)      NULL,
    [mon_s2]      CHAR (8)      NULL,
    [mon_e2]      CHAR (8)      NULL,
    [mon_hrs]     SMALLINT      NULL,
    [mon_eve]     BIT           NULL,
    [tues_s1]     CHAR (8)      NULL,
    [tues_e1]     CHAR (8)      NULL,
    [tues_s2]     CHAR (8)      NULL,
    [tues_e2]     CHAR (8)      NULL,
    [tues_hrs]    SMALLINT      NULL,
    [tues_eve]    BIT           NULL,
    [wednes_s1]   CHAR (8)      NULL,
    [wednes_e1]   CHAR (8)      NULL,
    [wednes_s2]   CHAR (8)      NULL,
    [wednes_e2]   CHAR (8)      NULL,
    [wednes_hrs]  SMALLINT      NULL,
    [wednes_eve]  BIT           NULL,
    [thurs_s1]    CHAR (8)      NULL,
    [thurs_e1]    CHAR (8)      NULL,
    [thurs_s2]    CHAR (8)      NULL,
    [thurs_e2]    CHAR (8)      NULL,
    [thurs_hrs]   SMALLINT      NULL,
    [thurs_eve]   BIT           NULL,
    [fri_s1]      CHAR (8)      NULL,
    [fri_e1]      CHAR (8)      NULL,
    [fri_s2]      CHAR (8)      NULL,
    [fri_e2]      CHAR (8)      NULL,
    [fri_hrs]     SMALLINT      NULL,
    [fri_eve]     BIT           NULL,
    [satur_s1]    CHAR (8)      NULL,
    [satur_e1]    CHAR (8)      NULL,
    [satur_s2]    CHAR (8)      NULL,
    [udf1]        CHAR (5)      NULL,
    [satur_e2]    CHAR (8)      NULL,
    [udf2]        CHAR (5)      NULL,
    [satur_hrs]   SMALLINT      NULL,
    [satur_eve]   BIT           NULL,
    [fax]         CHAR (14)     NULL,
    [nation]      CHAR (20)     NULL,
    [addr_id]     CHAR (12)     NULL,
    [lap]         CHAR (12)     NULL,
    [totalhours]  SMALLINT      NULL,
    [link]        INT           NULL,
    [l_pgroups]   CHAR (15)     NULL,
    [latitude]    DECIMAL (18)  NULL,
    [longitude]   DECIMAL (18)  NULL
);

