CREATE TABLE [dbo].[PhysicianEchoDrNameCurrent] (
    [dr_id]          CHAR (12)       NOT NULL,
    [fdate]          DATETIME        NULL,
    [dr_no_ext]      CHAR (12)       NOT NULL,
    [tdate]          DATETIME        NULL,
    [dr_lname]       CHAR (60)       NOT NULL,
    [reqhours]       DECIMAL (5, 2)  NOT NULL,
    [dr_fname]       CHAR (15)       NOT NULL,
    [havehours]      DECIMAL (5, 2)  NOT NULL,
    [dr_iname]       CHAR (15)       NOT NULL,
    [morehours]      DECIMAL (10, 2) NOT NULL,
    [drsal]          CHAR (4)        NOT NULL,
    [cms1]           CHAR (70)       NOT NULL,
    [drtitle]        CHAR (7)        NOT NULL,
    [UpdatedTitle]   VARCHAR (20)    NULL,
    [drsuffix]       CHAR (3)        NOT NULL,
    [dr_olname]      CHAR (60)       NOT NULL,
    [dr_ofname]      CHAR (15)       NOT NULL,
    [dr_oiname]      CHAR (15)       NOT NULL,
    [drosal]         CHAR (4)        NOT NULL,
    [drosuffix]      CHAR (3)        NOT NULL,
    [birthdate]      DATETIME        NULL,
    [gender]         CHAR (1)        NOT NULL,
    [ss_no]          CHAR (11)       NOT NULL,
    [sec_id]         CHAR (30)       NOT NULL,
    [paid]           BIT             NOT NULL,
    [paydate]        DATETIME        NULL,
    [mslnet]         BIT             NOT NULL,
    [duedate]        DATETIME        NULL,
    [amount]         DECIMAL (5, 2)  NOT NULL,
    [notdate]        DATETIME        NULL,
    [sec_cd]         CHAR (5)        NOT NULL,
    [secnum]         SMALLINT        NOT NULL,
    [staff_cd]       CHAR (3)        NOT NULL,
    [tdu]            CHAR (1)        NOT NULL,
    [act_date]       DATETIME        NULL,
    [act_text]       CHAR (35)       NOT NULL,
    [note_date]      DATETIME        NULL,
    [tre]            CHAR (1)        NOT NULL,
    [create_dt]      DATETIME        NULL,
    [lst_md_dt]      DATETIME        NULL,
    [import_dt]      DATETIME        NULL,
    [ud1]            CHAR (3)        NOT NULL,
    [ud2]            CHAR (3)        NOT NULL,
    [ud3]            CHAR (3)        NOT NULL,
    [ud4]            CHAR (3)        NOT NULL,
    [ud5]            CHAR (3)        NOT NULL,
    [ud5_date]       DATETIME        NULL,
    [ud6]            CHAR (3)        NOT NULL,
    [ud6_date]       DATETIME        NULL,
    [ud7]            CHAR (3)        NOT NULL,
    [ud7_date]       DATETIME        NULL,
    [ud8]            CHAR (3)        NOT NULL,
    [ud8_date]       DATETIME        NULL,
    [ud9]            CHAR (3)        NOT NULL,
    [ud10]           CHAR (3)        NOT NULL,
    [ud11]           CHAR (3)        NOT NULL,
    [ud12]           CHAR (3)        NOT NULL,
    [ptle1]          CHAR (7)        NOT NULL,
    [ptle2]          CHAR (7)        NOT NULL,
    [ptle3]          CHAR (7)        NOT NULL,
    [stle1]          CHAR (7)        NOT NULL,
    [stle2]          CHAR (7)        NOT NULL,
    [stle3]          CHAR (7)        NOT NULL,
    [ethnic]         CHAR (1)        NOT NULL,
    [birthplace]     CHAR (30)       NOT NULL,
    [fmg]            BIT             NOT NULL,
    [spec1]          CHAR (3)        NULL,
    [spec2]          CHAR (3)        NULL,
    [spec3]          CHAR (3)        NULL,
    [spec4]          CHAR (3)        NULL,
    [sub_spec1]      CHAR (3)        NULL,
    [sub_spec2]      CHAR (3)        NULL,
    [sub_spec3]      CHAR (3)        NULL,
    [expertise1]     CHAR (4)        NULL,
    [expertise2]     CHAR (4)        NULL,
    [expertise3]     CHAR (4)        NULL,
    [expertise4]     CHAR (4)        NULL,
    [expertise5]     CHAR (4)        NULL,
    [expertise6]     CHAR (4)        NULL,
    [bd_cert1]       BIT             NULL,
    [bd_cert2]       BIT             NULL,
    [bd_cert3]       BIT             NULL,
    [bd_cert4]       BIT             NULL,
    [bd_yr1]         SMALLINT        NULL,
    [bd_yr2]         SMALLINT        NULL,
    [bd_yr3]         SMALLINT        NULL,
    [bd_yr4]         SMALLINT        NULL,
    [bd_elg1]        BIT             NULL,
    [bd_elg2]        BIT             NULL,
    [bd_elg3]        BIT             NULL,
    [bd_elg4]        BIT             NULL,
    [sub_bd1]        BIT             NULL,
    [sub_bd2]        BIT             NULL,
    [sub_bd3]        BIT             NULL,
    [sub_be1]        BIT             NULL,
    [sub_be2]        BIT             NULL,
    [sub_be3]        BIT             NULL,
    [sub_by1]        SMALLINT        NULL,
    [sub_by2]        SMALLINT        NULL,
    [sub_by3]        SMALLINT        NULL,
    [f_lang1]        CHAR (2)        NOT NULL,
    [f_lang2]        CHAR (2)        NOT NULL,
    [f_lang3]        CHAR (2)        NOT NULL,
    [f_lang4]        CHAR (2)        NOT NULL,
    [marital]        CHAR (1)        NOT NULL,
    [pict1]          CHAR (100)      NOT NULL,
    [spouse]         CHAR (55)       NOT NULL,
    [pict2]          CHAR (100)      NOT NULL,
    [both]           CHAR (55)       NOT NULL,
    [citisen]        CHAR (15)       NOT NULL,
    [visa]           CHAR (10)       NOT NULL,
    [expdate]        DATETIME        NULL,
    [typ_pract1]     CHAR (1)        NOT NULL,
    [typ_pract2]     CHAR (1)        NOT NULL,
    [typ_pract3]     CHAR (1)        NOT NULL,
    [pract_cd1]      CHAR (5)        NOT NULL,
    [pract_cd2]      CHAR (5)        NOT NULL,
    [pract_cd3]      CHAR (5)        NOT NULL,
    [yr_prt_st]      SMALLINT        NOT NULL,
    [yr_loc_st]      SMALLINT        NOT NULL,
    [yr_join]        SMALLINT        NOT NULL,
    [cmt1]           CHAR (40)       NOT NULL,
    [cmt2]           CHAR (40)       NOT NULL,
    [cmt3]           CHAR (40)       NOT NULL,
    [cmt4]           CHAR (40)       NOT NULL,
    [cmt5]           CHAR (40)       NOT NULL,
    [cmt6]           CHAR (40)       NOT NULL,
    [cmt7]           CHAR (40)       NOT NULL,
    [cmt8]           CHAR (40)       NOT NULL,
    [cmt9]           CHAR (40)       NOT NULL,
    [ama_no]         CHAR (15)       NOT NULL,
    [efmg_no]        CHAR (15)       NOT NULL,
    [org_name]       CHAR (40)       NOT NULL,
    [medicare]       CHAR (14)       NOT NULL,
    [medicaid]       CHAR (14)       NOT NULL,
    [beeper]         CHAR (20)       NOT NULL,
    [beeper2]        CHAR (20)       NOT NULL,
    [fax]            CHAR (14)       NOT NULL,
    [meet]           CHAR (1)        NOT NULL,
    [aliasid]        CHAR (12)       NOT NULL,
    [upin]           CHAR (15)       NOT NULL,
    [ytd_tot]        DECIMAL (9, 2)  NOT NULL,
    [ytd_pay]        DECIMAL (9, 2)  NOT NULL,
    [facility]       VARCHAR (500)   NOT NULL,
    [coverage24]     BIT             NOT NULL,
    [notes]          TEXT            NOT NULL,
    [bd_reyr1]       SMALLINT        NULL,
    [bd_reyr2]       SMALLINT        NULL,
    [bd_reyr3]       SMALLINT        NULL,
    [bd_reyr4]       SMALLINT        NULL,
    [sub_reby1]      SMALLINT        NULL,
    [sub_reby2]      SMALLINT        NULL,
    [sub_reby3]      SMALLINT        NULL,
    [npdb]           CHAR (3)        NOT NULL,
    [netpass1]       CHAR (12)       NULL,
    [profile]        TEXT            NULL,
    [email]          CHAR (100)      NOT NULL,
    [netpass2]       CHAR (12)       NULL,
    [wavefile]       CHAR (100)      NULL,
    [address]        INT             NULL,
    [train]          INT             NULL,
    [proref]         INT             NULL,
    [stfstatu]       INT             NULL,
    [credent]        INT             NULL,
    [appass]         INT             NULL,
    [educate]        INT             NULL,
    [comte]          INT             NULL,
    [pvlege]         INT             NULL,
    [cmeinf]         INT             NULL,
    [staffs]         INT             NULL,
    [depart]         INT             NULL,
    [drmeet]         INT             NULL,
    [applet]         INT             NULL,
    [ticlet]         INT             NULL,
    [society]        INT             NULL,
    [dr_chk]         INT             NULL,
    [ersched]        INT             NULL,
    [er_group]       INT             NULL,
    [partner]        INT             NULL,
    [covering]       INT             NULL,
    [dr_plan1]       INT             NULL,
    [proctor]        INT             NULL,
    [quality]        INT             NULL,
    [insrev]         INT             NULL,
    [carry]          INT             NULL,
    [aihis]          INT             NULL,
    [supproc]        INT             NULL,
    [mrecst]         INT             NULL,
    [maljudge]       INT             NULL,
    [hrecst]         INT             NULL,
    [workhist]       INT             NULL,
    [html_drs]       INT             NULL,
    [pict3]          CHAR (100)      NULL,
    [htmldrs]        INT             NULL,
    [imagetra]       INT             NULL,
    [usmle_id]       CHAR (8)        NULL,
    [ecfmg_date]     DATETIME        NULL,
    [active123]      CHAR (1)        NOT NULL,
    [rec_date]       DATETIME        NULL,
    [rea_date]       DATETIME        NULL,
    [applet_rec]     INT             NOT NULL,
    [ticlet_rec]     INT             NOT NULL,
    [netpass3]       CHAR (12)       NOT NULL,
    [expertise7]     CHAR (4)        NULL,
    [f_lang5]        CHAR (2)        NULL,
    [pract_cd4]      CHAR (5)        NULL,
    [typ_pract4]     CHAR (1)        NULL,
    [stle4]          CHAR (7)        NULL,
    [spec5]          CHAR (3)        NULL,
    [sub_spec4]      CHAR (3)        NULL,
    [ptle4]          CHAR (7)        NULL,
    [cmt10]          CHAR (40)       NULL,
    [bd_cert5]       BIT             NULL,
    [bd_elg5]        BIT             NULL,
    [sub_bd4]        BIT             NULL,
    [sub_be4]        BIT             NULL,
    [lap_mod]        BIT             NULL,
    [contact_tp]     CHAR (1)        NULL,
    [link]           INT             NOT NULL,
    [verfac]         BIT             NOT NULL,
    [SSNUnformatted] VARCHAR (9)     NULL
);

