CREATE TABLE [dbo].[ProviderMasterUpdateLog] (
    [PMULPrimeKey]                 INT           NOT NULL,
    [StaffGroup]                   VARCHAR (50)  NULL,
    [ProviderMasterID]             INT           NULL,
    [WebID]                        INT           NULL,
    [TaxIDIncorporated]            VARCHAR (11)  NULL,
    [TaxIDIncorporatedOld]         VARCHAR (11)  NULL,
    [LastName]                     VARCHAR (50)  NULL,
    [LastNameOld]                  VARCHAR (50)  NULL,
    [FirstName]                    VARCHAR (50)  NULL,
    [FirstNameOld]                 VARCHAR (50)  NULL,
    [MiddleNameOrInitial]          VARCHAR (50)  NULL,
    [MiddleNameOrInitialOld]       VARCHAR (50)  NULL,
    [PreferredName]                VARCHAR (50)  NULL,
    [PreferredNameOld]             VARCHAR (50)  NULL,
    [IncorporatedName]             VARCHAR (100) NULL,
    [IncorporatedNameOld]          VARCHAR (100) NULL,
    [Title]                        VARCHAR (100) NULL,
    [TitleOld]                     VARCHAR (100) NULL,
    [MaritalStatus]                VARCHAR (50)  NULL,
    [MaritalStatusOld]             VARCHAR (50)  NULL,
    [SpouseName]                   VARCHAR (50)  NULL,
    [SpouseNameOld]                VARCHAR (50)  NULL,
    [EmailAddress]                 VARCHAR (100) NULL,
    [EmailAddressOld]              VARCHAR (100) NULL,
    [CEPEmail]                     VARCHAR (100) NULL,
    [CEPEmailOld]                  VARCHAR (100) NULL,
    [CellPhoneNbr]                 VARCHAR (50)  NULL,
    [CellPhoneNbrOld]              VARCHAR (50)  NULL,
    [PagerNbr]                     VARCHAR (50)  NULL,
    [PagerNbrOld]                  VARCHAR (50)  NULL,
    [AddressType1]                 VARCHAR (20)  NULL,
    [AddressType1Old]              VARCHAR (20)  NULL,
    [AddressForPayrollFlag1]       CHAR (3)      NULL,
    [AddressForPayrollFlag1Old]    CHAR (3)      NULL,
    [AddressForNonPayrollFlag1]    CHAR (3)      NULL,
    [AddressForNonPayrollFlag1Old] CHAR (3)      NULL,
    [Address1]                     VARCHAR (100) NULL,
    [Address1Old]                  VARCHAR (100) NULL,
    [City1]                        VARCHAR (50)  NULL,
    [City1Old]                     VARCHAR (50)  NULL,
    [State1]                       VARCHAR (50)  NULL,
    [State1Old]                    VARCHAR (50)  NULL,
    [ZipCode1]                     VARCHAR (50)  NULL,
    [ZipCode1Old]                  VARCHAR (50)  NULL,
    [Country1]                     VARCHAR (100) NULL,
    [Country1Old]                  VARCHAR (100) NULL,
    [PhoneNbr1]                    VARCHAR (50)  NULL,
    [PhoneNbr1Old]                 VARCHAR (50)  NULL,
    [FaxNbr1]                      VARCHAR (50)  NULL,
    [FaxNbr1Old]                   VARCHAR (50)  NULL,
    [AddressType2]                 VARCHAR (20)  NULL,
    [AddressType2Old]              VARCHAR (20)  NULL,
    [AddressForPayrollFlag2]       CHAR (3)      NULL,
    [AddressForPayrollFlag2Old]    CHAR (3)      NULL,
    [AddressForNonPayrollFlag2]    CHAR (3)      NULL,
    [AddressForNonPayrollFlag2Old] CHAR (3)      NULL,
    [Address2]                     VARCHAR (100) NULL,
    [Address2Old]                  VARCHAR (100) NULL,
    [City2]                        VARCHAR (50)  NULL,
    [City2Old]                     VARCHAR (50)  NULL,
    [State2]                       VARCHAR (50)  NULL,
    [State2Old]                    VARCHAR (50)  NULL,
    [ZipCode2]                     VARCHAR (50)  NULL,
    [ZipCode2Old]                  VARCHAR (50)  NULL,
    [Country2]                     VARCHAR (100) NULL,
    [Country2Old]                  VARCHAR (100) NULL,
    [PhoneNbr2]                    VARCHAR (50)  NULL,
    [PhoneNbr2Old]                 VARCHAR (50)  NULL,
    [FaxNbr2]                      VARCHAR (50)  NULL,
    [FaxNbr2Old]                   VARCHAR (50)  NULL,
    [AddressType3]                 VARCHAR (20)  NULL,
    [AddressType3Old]              VARCHAR (50)  NULL,
    [AddressForPayrollFlag3]       CHAR (3)      NULL,
    [AddressForPayrollFlag3Old]    CHAR (3)      NULL,
    [AddressForNonPayrollFlag3]    CHAR (3)      NULL,
    [AddressForNonPayrollFlag3Old] CHAR (3)      NULL,
    [Address3]                     VARCHAR (100) NULL,
    [Address3Old]                  VARCHAR (100) NULL,
    [City3]                        VARCHAR (50)  NULL,
    [City3Old]                     VARCHAR (50)  NULL,
    [State3]                       VARCHAR (50)  NULL,
    [State3Old]                    VARCHAR (50)  NULL,
    [ZipCode3]                     VARCHAR (50)  NULL,
    [ZipCode3Old]                  VARCHAR (50)  NULL,
    [Country3]                     VARCHAR (100) NULL,
    [Country3Old]                  VARCHAR (50)  NULL,
    [PhoneNbr3]                    VARCHAR (50)  NULL,
    [PhoneNbr3Old]                 VARCHAR (50)  NULL,
    [FaxNbr3]                      VARCHAR (50)  NULL,
    [FaxNbr3Old]                   VARCHAR (50)  NULL,
    [PrimarySite]                  VARCHAR (100) NULL,
    [Site1]                        VARCHAR (5)   NULL,
    [Site1Old]                     VARCHAR (5)   NULL,
    [Site2]                        VARCHAR (5)   NULL,
    [Site2Old]                     VARCHAR (5)   NULL,
    [Site3]                        VARCHAR (5)   NULL,
    [Site3Old]                     VARCHAR (5)   NULL,
    [Site4]                        VARCHAR (5)   NULL,
    [Site4Old]                     VARCHAR (5)   NULL,
    [TimeStmp]                     DATETIME      NULL,
    [Author]                       VARCHAR (60)  NULL,
    [TimeStmpApproval]             DATETIME      NULL,
    [AuthorApproval]               VARCHAR (60)  NULL,
    [InternalUpdateFlag]           CHAR (1)      NULL,
    [MatchedToArchiveFlag]         CHAR (1)      NULL,
    [CreDate]                      DATETIME      CONSTRAINT [DF_ProviderMasterUpdateLog_CreDate] DEFAULT (getdate()) NULL,
    [UpdDate]                      DATETIME      CONSTRAINT [DF_ProviderMasterUpdateLog_UpdDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_ProviderMasterUpdateLog] PRIMARY KEY CLUSTERED ([PMULPrimeKey] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ProviderMasterUpdateLog_ProviderMaster] FOREIGN KEY ([ProviderMasterID]) REFERENCES [dbo].[ProviderMaster] ([ProviderMasterID])
);


GO
CREATE NONCLUSTERED INDEX [PMUL_ProviderMasterID_idx]
    ON [dbo].[ProviderMasterUpdateLog]([ProviderMasterID] ASC) WITH (FILLFACTOR = 90);

