CREATE TABLE [dbo].[ProviderHospitalEchoPrior] (
    [cd]        CHAR (6)       NOT NULL,
    [txt]       CHAR (50)      NOT NULL,
    [subname]   CHAR (50)      NOT NULL,
    [addr]      CHAR (30)      NOT NULL,
    [addr2]     CHAR (30)      NOT NULL,
    [city]      CHAR (20)      NOT NULL,
    [state]     CHAR (2)       NOT NULL,
    [zip]       CHAR (10)      NOT NULL,
    [nation]    CHAR (30)      NOT NULL,
    [phone]     CHAR (14)      NOT NULL,
    [contact1]  CHAR (40)      NOT NULL,
    [contact2]  CHAR (40)      NOT NULL,
    [fax]       CHAR (14)      NOT NULL,
    [email]     CHAR (100)     NOT NULL,
    [payfee]    DECIMAL (9, 2) NOT NULL,
    [cvo_type]  CHAR (3)       NOT NULL,
    [homehtml]  CHAR (100)     NOT NULL,
    [ver_elec]  BIT            NOT NULL,
    [link]      INT            IDENTITY (1, 1) NOT NULL,
    [autofax]   BIT            NOT NULL,
    [autoemail] BIT            NOT NULL,
    [tax_id]    CHAR (15)      NOT NULL
);

