CREATE TABLE [dbo].[SiteLocationLookupFlat] (
    [SiteLocationID]                   INT           NOT NULL,
    [StaffGroup]                       VARCHAR (50)  NULL,
    [PayrollDivision]                  CHAR (2)      NULL,
    [PayrollDept]                      CHAR (3)      NULL,
    [WebCode]                          VARCHAR (20)  NULL,
    [MARSLocationNameProd]             VARCHAR (100) NULL,
    [PayrollName]                      VARCHAR (100) NULL,
    [WebName]                          VARCHAR (100) NULL,
    [EchoName]                         VARCHAR (100) NULL,
    [SiteLocationName]                 VARCHAR (100) NULL,
    [MedicalDirectorName]              VARCHAR (200) NULL,
    [AsstMedicalDirectorName]          VARCHAR (200) NULL,
    [ReimbursementDirectorName]        VARCHAR (200) NULL,
    [QIDirector1Name]                  VARCHAR (200) NULL,
    [QIDirector2Name]                  VARCHAR (200) NULL,
    [QIDirector3Name]                  VARCHAR (200) NULL,
    [QIDirector4Name]                  VARCHAR (200) NULL,
    [QIDirector5Name]                  VARCHAR (200) NULL,
    [DirectorOfNursePhysRelationsName] VARCHAR (200) NULL,
    [ChiefMedicalOfficerName]          VARCHAR (200) NULL,
    [EMSDirectorName]                  VARCHAR (200) NULL,
    [RegionName]                       VARCHAR (100) NULL,
    [RegionalDirectorName]             VARCHAR (100) NULL,
    [MedicareGroup]                    VARCHAR (30)  NULL,
    [MediCalGroup]                     VARCHAR (30)  NULL,
    [MedicaidGroup]                    VARCHAR (30)  NULL,
    [BlueShieldGroup]                  VARCHAR (30)  NULL,
    [TaxID]                            CHAR (15)     NULL,
    [NPIGroup]                         VARCHAR (50)  NULL,
    [ActiveInactive]                   VARCHAR (100) NULL,
    [ActiveInactiveMBSI]               VARCHAR (100) NULL,
    [StartDate]                        DATETIME      NULL,
    [TermDate]                         DATETIME      NULL,
    [DummySiteLocationFlag]            CHAR (1)      NULL,
    [WebSchedulingBeginDate]           DATETIME      NULL,
    [ContractRostersFlag]              CHAR (1)      NULL,
    [CreDate]                          DATETIME      NULL,
    [UpdDate]                          DATETIME      NULL
);

