INSERT INTO tblbdg(
       [Bdg_CtrID]
      ,[BdgYear]
      --,[BdgID]
      ,[BdgKey]
      ,[BdgAvgChgPt]
      ,[BdgBillFee]
      ,[BdgBillRate]
      ,[BdgBillSpec]
      ,[BdgBlendedHrs]
      ,[BdgBlendedPtsHr]
      ,[BdgCEPRetentionAmt]
      ,[BdgCEPRetentionPct]
      ,[BdgCollPerPt]
      ,[BdgContribCEP]
      ,[BdgContribPct]
      ,[BdgDocEarnedHrly]
      ,[BdgDocHours]
      ,[BdgDonations]
      ,[BdgEncounters]
      ,[BdgFixedLocalAmt]
      ,[BdgGrossColl]
      ,[BdgInterest]
      ,[BdgInterestRate]
      ,[BdgLclExp]
      ,[BdgLclExpPct]
      ,[BdgLclPct]
      ,[BdgLclVarAmt]
      ,[BdgMalpractice]
      ,[BdgMDearned]
      ,[BdgMDpct]
      ,[BdgMPFlatFeeAmt]
      ,[BdgMPRate]
      ,[BdgNetPctofNOR]
      ,[BdgNetRevPerPt]
      ,[BdgNOR]
      ,[BdgOffTop]
      ,[BdgOthRcpts]
      ,[BdgPACost]
      ,[BdgPACostHr]
      ,[BdgPACostPct]
      ,[BdgPAHours]
      ,[BdgPASupportCostAmt]
      ,[BdgPASupportCostPct]
      ,[BdgPatients]
      ,[BdgPstChgs]
      ,[BdgPTCost]
      ,[BdgPITpct]
      ,[BdgPITearned]
      ,[BdgPITEarnedPct]
      ,[BdgPTCostPct]
      ,[BdgPtsPerHr]
      ,[BdgRDearned]
      ,[BdgRDpct]
      ,[BdgStipendsRcvd]
      ,[BdgTargetRate]
      ,[BdgSiteNetInc]
      ,[BdgSiteOverhead]
      ,[BdgSiteOvrHdAmt]
      ,[BdgSiteOvrHdPct]
      ,[BdgTotalColl]
      ,[BdgDateCreate]
      ,[BdgDateEdit]
      ,[BdgFlagYN]
      ,[BdgInactiveYN]
)
SELECT
       [Bdg_CtrID]
      ,'2017'
      --,[BdgID]
      ,'2017 - ' + C.CtrKey  AS [BdgKey]
      , 0   AS  [BdgAvgChgPt]
      , 0   AS  [BdgBillFee]
      , 0   AS  [BdgBillRate]
      , 0   AS  [BdgBillSpec]
      , 0   AS  [BdgBlendedHrs]
      , 0   AS  [BdgBlendedPtsHr]
      , 0   AS  [BdgCEPRetentionAmt]
      , 0.005   AS  [BdgCEPRetentionPct]
      , 0   AS  [BdgCollPerPt]
      , 0   AS  [BdgContribCEP]
      , [BdgContribPct]
      , 0   AS  [BdgDocEarnedHrly]
      , 0   AS  [BdgDocHours]
      , 0   AS  [BdgDonations]
      , 0   AS  [BdgEncounters]
      , 0   AS  [BdgFixedLocalAmt]
      , 0   AS  [BdgGrossColl]
      , 0   AS  [BdgInterest]
      , 0.02   AS  [BdgInterestRate]
      , 0   AS  [BdgLclExp]
      , 0   AS  [BdgLclExpPct]
      , 0   AS  [BdgLclPct]
      , 0   AS  [BdgLclVarAmt]
      , 0   AS  [BdgMalpractice]
      , 0   AS  [BdgMDearned]
      , [BdgMDpct]
      , 0   AS  [BdgMPFlatFeeAmt]
      , [BdgMPRate]
      , 0   AS  [BdgNetPctofNOR]
      , 0   AS  [BdgNetRevPerPt]
      , 0   AS  [BdgNOR]
      , 0   AS  [BdgOffTop]
      , 0   AS  [BdgOthRcpts]
      , 0   AS  [BdgPACost]
      , 0   AS  [BdgPACostHr]
      , 0   AS  [BdgPACostPct]
      , 0   AS  [BdgPAHours]
      , 0   AS  [BdgPASupportCostAmt]
      , 0   AS  [BdgPASupportCostPct]
      , 0   AS  [BdgPatients]
      , 0   AS  [BdgPstChgs]
      , 0   AS  [BdgPTCost]
      , [BdgPITpct]
      , 0   AS  [BdgPITearned]
      , 0   AS  [BdgPITEarnedPct]
      , 0   AS  [BdgPTCostPct]
      , 0   AS  [BdgPtsPerHr]
      , 0   AS  [BdgRDearned]
      , [BdgRDpct]
      , 0   AS  [BdgStipendsRcvd]
      , 0   AS  [BdgTargetRate]
      , 0   AS  [BdgSiteNetInc]
      , 0   AS  [BdgSiteOverhead]
      , 0   AS  [BdgSiteOvrHdAmt]
      , 0   AS  [BdgSiteOvrHdPct]
      , 0   AS  [BdgTotalColl]
      , 0   AS  [BdgDateCreate]
      , 0   AS  [BdgDateEdit]
      , 0   AS  [BdgFlagYN]
      , 0   AS  [BdgInactiveYN]
FROM tblbdg T
JOIN tblCtr C ON C.CtrID = T.Bdg_CtrID
 WHERE T.BdgYear = 2016
 AND NOT EXISTS( SELECT 1 FROM tblbdg T2 WHERE T2.BdgYear = 2017 AND T2.Bdg_CtrID = T.Bdg_CtrID)
 
 GO
 
 