USE [ApplicationIntegration]
GO
/****** Object:  StoredProcedure [dbo].[usp_LawsonNewHireEntry_PA52DME]    Script Date: 07/13/2016 18:10:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER                       PROCEDURE [dbo].[usp_LawsonNewHireEntry_PA52DME] 
AS

/* 	Author: 	Reetika Singh
	Date:		4/4/2011
	Purpose:	Create PA52 DME for PFI to load
	Revision:	

*/
SET QUOTED_IDENTIFIER OFF 
SET ANSI_NULLS OFF 

BEGIN





TRUNCATE TABLE DME_52


INSERT INTO DME_52
SELECT DISTINCT '_PDL=PROD&_TKN=PA52.4&_EVT=ADD&_RTN=DATA&_LFN=ALL&_TDS=IGNORE&FC=A&PCT-COMPANY=100',

'&PCT-APPLICANT=' + CASE WHEN ApplicantNo IS NULL THEN ''
			ELSE LTRIM(RTRIM(ApplicantNo)) END
+'&PCT-ACTION-CODE=HIRE &PCT-EFFECT-DATE='+ EffectiveDate+ 
'&PCT-UPDATE-BENEFIT='+CASE WHEN Benefits IS NULL THEN ''
			ELSE LTRIM(RTRIM(Benefits)) END
+'&PCT-UPD-ABS-MGMT='+CASE WHEN AbMgmnt IS NULL THEN ''
			ELSE LTRIM(RTRIM(AbMgmnt)) END
+'&PCT-UPDATE-REQ-DED='+CASE WHEN ReqDeds IS NULL THEN ''
			ELSE LTRIM(RTRIM(ReqDeds)) END
+'&PCT-EDM-EFFECT-DT='+ EffectiveDate+ 
'&ASSIGN-EMPLOYEE-NBR='+CASE WHEN PreAssignEmpNo IS NULL THEN ''
			ELSE LTRIM(RTRIM(PreAssignEmpNo)) END
+'&IMMEDIATE-ACTION=N&BYPASS-POPUPS=Y' ,

'&PCT-NEW-VALUE-11='+CASE WHEN Status IS NULL THEN ''
			ELSE LTRIM(RTRIM(Status)) END
+'&PCT-NEW-VALUE-13='+CASE WHEN FTE IS NULL THEN ''
			ELSE LTRIM(RTRIM(FTE)) END
+'&PCT-NEW-VALUE-14='+CASE WHEN Pos IS NULL THEN ''
			ELSE LTRIM(RTRIM(Pos)) END
+'&PCT-NEW-VALUE-15='+CASE WHEN ProcessLevel IS NULL THEN ''
			ELSE LTRIM(RTRIM(ProcessLevel)) END
+'&PCT-NEW-VALUE-17='+CASE WHEN PosPL IS NULL THEN ''
			ELSE LTRIM(RTRIM(PosPL)) END
+'&PCT-NEW-VALUE-18='+CASE WHEN ProcessLevel IS NULL THEN ''
			ELSE LTRIM(RTRIM(ProcessLevel)) END
+'&PCT-NEW-VALUE-112='+CASE WHEN AutoTimeRcd IS NULL THEN ''
			ELSE LTRIM(RTRIM(AutoTimeRcd)) END
+'&PCT-NEW-VALUE-2r3='+CASE WHEN PayRate IS NULL THEN ''
			ELSE LTRIM(RTRIM(PayRate)) END
+'&PCT-NEW-VALUE-34='+CASE WHEN AutoDeposit IS NULL THEN ''
			ELSE LTRIM(RTRIM(AutoDeposit)) END
+'&PCT-NEW-VALUE-36='+CASE WHEN DateOfHire IS NULL THEN ''
			ELSE LTRIM(RTRIM(DateOfHire)) END,

'&PCT-NEW-VALUE-37='+CASE WHEN BenefitDate1 IS NULL THEN ''
			ELSE LTRIM(RTRIM(BenefitDate1)) END
+'&PCT-NEW-VALUE-38='+CASE WHEN BenefitDate2 IS NULL THEN ''
			ELSE LTRIM(RTRIM(BenefitDate2)) END
+'&PCT-NEW-VALUE-39='+CASE WHEN BenefitSalary1 IS NULL THEN ''
			ELSE LTRIM(RTRIM(BenefitSalary1)) END
+'&PCT-NEW-VALUE-310='+CASE WHEN BenefitSalary2 IS NULL THEN ''
			ELSE LTRIM(RTRIM(BenefitSalary2)) END
+'&PCT-NEW-VALUE-2r9='+CASE WHEN MaritalStatus IS NULL THEN ''
			ELSE LTRIM(RTRIM(MaritalStatus)) END ,

'&PCT-NEW-VALUE-1r0='+CASE WHEN Status IS NULL THEN ''
			ELSE LTRIM(RTRIM(Status)) END
+'&PCT-NEW-VALUE-1r2='+CASE WHEN FTE IS NULL THEN ''
			ELSE LTRIM(RTRIM(FTE)) END
+'&PCT-NEW-VALUE-1r3='+CASE WHEN Pos IS NULL THEN ''
			ELSE LTRIM(RTRIM(Pos)) END
+'&PCT-NEW-VALUE-1r4='+CASE WHEN ProcessLevel IS NULL THEN ''
			ELSE LTRIM(RTRIM(ProcessLevel)) END
+'&PCT-NEW-VALUE-1r6='+CASE WHEN PosPL IS NULL THEN ''
			ELSE LTRIM(RTRIM(PosPL)) END
+'&PCT-NEW-VALUE-1r7='+CASE WHEN ProcessLevel IS NULL THEN ''
			ELSE LTRIM(RTRIM(ProcessLevel)) END
+'&PCT-NEW-VALUE-1r11='+CASE WHEN AutoTimeRcd IS NULL THEN ''
			ELSE LTRIM(RTRIM(AutoTimeRcd)) END ,


'&PAT-FLD-NBR-11='+CASE WHEN convert(char(4), FLD_NBR_01)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_01))) END
+'&PAT-FLD-NBR-12='+CASE WHEN convert(char(4), FLD_NBR_02)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_02))) END
+'&PAT-FLD-NBR-13='+ CASE WHEN convert(char(4), FLD_NBR_03)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_03)))END
+'&PAT-FLD-NBR-14='+ CASE WHEN convert(char(4), FLD_NBR_04)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_04)))END
+'&PAT-FLD-NBR-15='+ CASE WHEN convert(char(4), FLD_NBR_05)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_05)))END ,

'&PAT-FLD-NBR-16='+ CASE WHEN convert(char(4), FLD_NBR_06)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_06)))END
+'&PAT-FLD-NBR-17='+ CASE WHEN convert(char(4), FLD_NBR_07)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_07)))END
+'&PAT-FLD-NBR-18='+ CASE WHEN convert(char(4), FLD_NBR_08)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_08)))END
+'&PAT-FLD-NBR-19='+ CASE WHEN convert(char(4), FLD_NBR_09)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_09)))END
+'&PAT-FLD-NBR-110='+ CASE WHEN convert(char(4), FLD_NBR_10)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_10)))END
+'&PAT-FLD-NBR-111='+ CASE WHEN convert(char(4), FLD_NBR_11)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_11)))END
+'&PAT-FLD-NBR-112='+ CASE WHEN convert(char(4), FLD_NBR_12)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_12)))END
+'&PAT-FLD-NBR-21='+ CASE WHEN convert(char(4), FLD_NBR_13)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_13))) END
+'&PAT-FLD-NBR-22='+ CASE WHEN convert(char(4), FLD_NBR_14)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_14)))END
+'&PAT-FLD-NBR-23='+ CASE WHEN convert(char(4), FLD_NBR_15)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_15)))END
+'&PAT-FLD-NBR-24='+ CASE WHEN convert(char(4), FLD_NBR_16)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_16)))END ,

'&PAT-FLD-NBR-25='+ CASE WHEN convert(char(4), FLD_NBR_17)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_17)))END
+'&PAT-FLD-NBR-26='+ CASE WHEN convert(char(4), FLD_NBR_18)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_18)))END
+'&PAT-FLD-NBR-27='+ CASE WHEN convert(char(4), FLD_NBR_19)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_19)))END
+'&PAT-FLD-NBR-28='+ CASE WHEN convert(char(4), FLD_NBR_20)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_20)))END
+'&PAT-FLD-NBR-29='+ CASE WHEN convert(char(4), FLD_NBR_21)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_21)))END
+'&PAT-FLD-NBR-210='+ CASE WHEN convert(char(4), FLD_NBR_22)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_22)))END
+'&PAT-FLD-NBR-211='+ CASE WHEN convert(char(4), FLD_NBR_23)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_23)))END
+'&PAT-FLD-NBR-212='+ CASE WHEN convert(char(4), FLD_NBR_24)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_24)))END ,


'&PAT-FLD-NBR-31='+ CASE WHEN convert(char(4), FLD_NBR_25)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_25)))END
+'&PAT-FLD-NBR-32='+ CASE WHEN convert(char(4), FLD_NBR_26)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_26)))END
+'&PAT-FLD-NBR-33='+ CASE WHEN convert(char(4), FLD_NBR_27)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_27)))END
+'&PAT-FLD-NBR-34='+ CASE WHEN convert(char(4), FLD_NBR_28)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_28)))END
+'&PAT-FLD-NBR-35='+ CASE WHEN convert(char(4), FLD_NBR_29)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_29)))END
+'&PAT-FLD-NBR-36='+ CASE WHEN convert(char(4), FLD_NBR_30)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_30)))END
+'&PAT-FLD-NBR-37='+ CASE WHEN convert(char(4), FLD_NBR_31)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_31)))END
+'&PAT-FLD-NBR-38='+ CASE WHEN convert(char(4), FLD_NBR_32)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_32)))END
+'&PAT-FLD-NBR-39='+ CASE WHEN convert(char(4), FLD_NBR_33)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_33)))END
+'&PAT-FLD-NBR-310='+ CASE WHEN convert(char(4), FLD_NBR_34)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_34)))END
+'&PAT-FLD-NBR-311='+ CASE WHEN convert(char(4), FLD_NBR_35)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_35)))END
+'&PAT-FLD-NBR-312='+ CASE WHEN convert(char(4), FLD_NBR_36)IS NULL THEN ''
			ELSE LTRIM(RTRIM(convert(char(4), FLD_NBR_36)))END ,

'&ORIG-COMPANY=100' + 
+'&ORIG-APPLICANT=' + CASE WHEN ApplicantNo IS NULL THEN ''
			ELSE LTRIM(RTRIM(ApplicantNo)) END
+'&ORIG-ACTION-CODE=HIRE'
+'&ORIG-EFFECT-DATE=' + EffectiveDate 
+'&_HK=' + CASE WHEN LTRIM(RTRIM([_f296:_HK])) IS NULL THEN ''
		ELSE LTRIM(RTRIM([_f296:_HK])) END 
+'&_DELIM=%09&_OUT=XML&_EOT=TRUE' 

FROM dbo.LawsonNewHireEntry
WHERE ApplicantNo IS NOT NULL



--select * from dbo.DME_52








	

END

