CREATE TABLE [jagardg].[tblBdg20110921] (
    [Bdg_CtrID]           INT           NOT NULL,
    [BdgYear]             INT           NOT NULL,
    [BdgID]               INT           IDENTITY (1, 1) NOT NULL,
    [BdgKey]              VARCHAR (100) NOT NULL,
    [BdgAvgChgPt]         MONEY         NOT NULL,
    [BdgBillFee]          MONEY         NOT NULL,
    [BdgBillRate]         FLOAT (53)    NOT NULL,
    [BdgBillSpec]         MONEY         NOT NULL,
    [BdgBlendedHrs]       FLOAT (53)    NOT NULL,
    [BdgBlendedPtsHr]     FLOAT (53)    NOT NULL,
    [BdgCEPRetentionAmt]  MONEY         NOT NULL,
    [BdgCEPRetentionPct]  FLOAT (53)    NOT NULL,
    [BdgCollPerPt]        MONEY         NOT NULL,
    [BdgContribCEP]       MONEY         NOT NULL,
    [BdgContribPct]       FLOAT (53)    NOT NULL,
    [BdgDocEarnedHrly]    MONEY         NOT NULL,
    [BdgDocHours]         FLOAT (53)    NOT NULL,
    [BdgDonations]        MONEY         NOT NULL,
    [BdgEncounters]       INT           NOT NULL,
    [BdgFixedLocalAmt]    MONEY         NOT NULL,
    [BdgGrossColl]        MONEY         NOT NULL,
    [BdgInterest]         MONEY         NOT NULL,
    [BdgInterestRate]     FLOAT (53)    NOT NULL,
    [BdgLclExp]           MONEY         NOT NULL,
    [BdgLclExpPct]        FLOAT (53)    NOT NULL,
    [BdgLclPct]           FLOAT (53)    NOT NULL,
    [BdgLclVarAmt]        MONEY         NOT NULL,
    [BdgMalpractice]      MONEY         NOT NULL,
    [BdgMDearned]         MONEY         NOT NULL,
    [BdgMDpct]            FLOAT (53)    NOT NULL,
    [BdgMPFlatFeeAmt]     MONEY         NOT NULL,
    [BdgMPRate]           FLOAT (53)    NOT NULL,
    [BdgNetPctofNOR]      FLOAT (53)    NOT NULL,
    [BdgNetRevPerPt]      MONEY         NOT NULL,
    [BdgNOR]              MONEY         NOT NULL,
    [BdgOffTop]           MONEY         NOT NULL,
    [BdgOthRcpts]         MONEY         NOT NULL,
    [BdgPACost]           MONEY         NOT NULL,
    [BdgPACostHr]         MONEY         NOT NULL,
    [BdgPACostPct]        FLOAT (53)    NOT NULL,
    [BdgPAHours]          FLOAT (53)    NOT NULL,
    [BdgPASupportCostAmt] MONEY         NOT NULL,
    [BdgPASupportCostPct] FLOAT (53)    NOT NULL,
    [BdgPatients]         INT           NOT NULL,
    [BdgPstChgs]          MONEY         NOT NULL,
    [BdgPTCost]           MONEY         NOT NULL,
    [BdgPITpct]           FLOAT (53)    NOT NULL,
    [BdgPITearned]        MONEY         NOT NULL,
    [BdgPITEarnedPct]     FLOAT (53)    NOT NULL,
    [BdgPTCostPct]        FLOAT (53)    NOT NULL,
    [BdgPtsPerHr]         FLOAT (53)    NOT NULL,
    [BdgRDearned]         MONEY         NOT NULL,
    [BdgRDpct]            FLOAT (53)    NOT NULL,
    [BdgStipendsRcvd]     MONEY         NOT NULL,
    [BdgTargetRate]       FLOAT (53)    NOT NULL,
    [BdgSiteNetInc]       MONEY         NOT NULL,
    [BdgSiteOverhead]     MONEY         NOT NULL,
    [BdgSiteOvrHdAmt]     MONEY         NOT NULL,
    [BdgSiteOvrHdPct]     FLOAT (53)    NOT NULL,
    [BdgTotalColl]        MONEY         NOT NULL,
    [BdgDateCreate]       SMALLDATETIME NULL,
    [BdgDateEdit]         SMALLDATETIME NULL,
    [BdgFlagYN]           BIT           NULL,
    [BdgInactiveYN]       BIT           NULL,
    PRIMARY KEY CLUSTERED ([Bdg_CtrID] ASC, [BdgYear] ASC)
);

