CREATE TABLE [dbo].[tblfrmCntLst] (
    [CntKey]             NVARCHAR (60) NULL,
    [CntID]              INT           IDENTITY (1, 1) NOT NULL,
    [Cnt_CmpID]          INT           NULL,
    [Cnt_HonID]          NVARCHAR (10) NULL,
    [CntTitle]           NVARCHAR (20) NULL,
    [CntNameFirst]       NVARCHAR (20) NULL,
    [CntNameMiddle]      NVARCHAR (20) NULL,
    [CntNameLast]        NVARCHAR (20) NULL,
    [CntNameSuffix]      NVARCHAR (10) NULL,
    [CntAddress1]        NVARCHAR (40) NULL,
    [CntAddress2]        NVARCHAR (40) NULL,
    [CntCity]            NVARCHAR (20) NULL,
    [CntState]           NVARCHAR (2)  NULL,
    [CntZip]             NVARCHAR (10) NULL,
    [CntCountry]         NVARCHAR (20) NULL,
    [CntEmail]           NVARCHAR (50) NULL,
    [CntPhonePref]       NVARCHAR (20) NULL,
    [CntPhonePrefSelect] INT           NULL,
    [CntPhoneHome]       NVARCHAR (20) NULL,
    [CntPhoneWork]       NVARCHAR (20) NULL,
    [CntPhoneCell]       NVARCHAR (20) NULL,
    [CntPhoneAlt]        NVARCHAR (20) NULL,
    [CntPager]           NVARCHAR (20) NULL,
    [CntFaxHome]         NVARCHAR (20) NULL,
    [CntFaxWork]         NVARCHAR (50) NULL,
    [CntPhoneVoicemail]  NVARCHAR (50) NULL,
    [CntCALicNo]         NVARCHAR (50) NULL,
    [CntDocNo]           NVARCHAR (50) NULL,
    [CntSSN]             NVARCHAR (11) NULL,
    [CntDOB]             DATETIME      NULL,
    [CntDateCreate]      DATETIME      NULL,
    [CntDateEdit]        DATETIME      NULL,
    [CntDateInactive]    DATETIME      NULL,
    [CntInactiveYN]      BIT           NULL,
    [CntFlagYN]          BIT           NULL,
    [CntComment]         NTEXT         NULL,
    [CntDocYN]           BIT           NULL,
    [CntPAYN]            BIT           NULL,
    [CntCAMYN]           BIT           NULL,
    [zCnt_PhysicianID]   INT           NULL,
    [zCnt_CAMID]         INT           NULL,
    [zCnt_ContractID]    INT           NULL,
    [CmpKey]             NVARCHAR (70) NULL,
    [CmpCity]            NVARCHAR (20) NULL,
    [CmpState]           NVARCHAR (2)  NULL,
    [CmpZip]             NVARCHAR (10) NULL,
    [CmpPhone]           NVARCHAR (15) NULL
);

