CREATE TABLE [dbo].[tblfrmCmpLst] (
    [CmpKey]              NVARCHAR (70) NULL,
    [CmpID]               INT           IDENTITY (1, 1) NOT NULL,
    [CmpName]             NVARCHAR (40) NULL,
    [CmpCode]             NVARCHAR (10) NULL,
    [CmpAddress1]         NVARCHAR (40) NULL,
    [CmpAddress2]         NVARCHAR (40) NULL,
    [CmpCity]             NVARCHAR (20) NULL,
    [CmpState]            NVARCHAR (2)  NULL,
    [CmpZip]              NVARCHAR (10) NULL,
    [CmpCountry]          NVARCHAR (20) NULL,
    [CmpPhone]            NVARCHAR (15) NULL,
    [CmpFax]              NVARCHAR (15) NULL,
    [CmpWeb]              NVARCHAR (50) NULL,
    [CmpSiteBedNo]        INT           NULL,
    [CmpPhyGrpYN]         BIT           NULL,
    [CmpSysYN]            BIT           NULL,
    [CmpSiteYN]           BIT           NULL,
    [CmpBillAgentYN]      BIT           NULL,
    [CmpMalCarYN]         BIT           NULL,
    [CmpOtherYN]          BIT           NULL,
    [CmpTranscriptYN]     BIT           NULL,
    [CmpComment]          NTEXT         NULL,
    [CmpDateCreate]       DATETIME      NULL,
    [CmpDateEdit]         DATETIME      NULL,
    [CmpDateInactive]     DATETIME      NULL,
    [CmpInactiveYN]       BIT           NULL,
    [CmpFlagYN]           BIT           NULL,
    [CmpPhysiciangroupID] INT           NULL,
    [CmpSystemID]         INT           NULL,
    [CmpContact]          NVARCHAR (50) NULL,
    [CmpTitle]            NVARCHAR (50) NULL,
    [CmpSitID]            INT           NULL,
    [zCmpSys_CmpID]       INT           NULL
);

