CREATE TABLE [dbo].[tblMngCarBackUp050727] (
    [MngCarID]                   INT           IDENTITY (1, 1) NOT NULL,
    [MngCarKey]                  VARCHAR (255) NULL,
    [MngCar_CtrID]               INT           NULL,
    [MngCarIPA_CmpID]            INT           NULL,
    [MngCarBill_CmpID]           INT           NULL,
    [MngCar_CntID]               INT           NULL,
    [MngCar_RatTypID]            INT           NULL,
    [MngCar_LivTypID]            INT           NULL,
    [MngCar_McCtrTypID]          INT           NULL,
    [MngCar_FeeSchRgnID]         INT           NULL,
    [MngCar_FeeSchYrID]          INT           NULL,
    [MngCarClientGroup]          VARCHAR (50)  NULL,
    [MngCarEffectDate]           DATETIME      NULL,
    [MngCarUnsignedYN]           BIT           NOT NULL,
    [MngCarClientSignDate]       DATETIME      NULL,
    [MngCarIPASignDate]          DATETIME      NULL,
    [MngCarAutoRenewYN]          BIT           NOT NULL,
    [MngCarTerminateDate]        DATETIME      NULL,
    [MngCarRenewNoteDaysQty]     INT           NOT NULL,
    [MngCarTermNoCauseDaysQt]    INT           NOT NULL,
    [MngCarTermWithCauseDaysQty] INT           NOT NULL,
    [MngCarComment]              TEXT          NULL,
    [MngCarPMPMCapRateAmt]       MONEY         NULL,
    [MngCarChargePct]            FLOAT (53)    NULL,
    [MngCarCFPrimary]            FLOAT (53)    NULL,
    [MngCarFS1Desc]              VARCHAR (25)  NULL,
    [MngCarCFMedicine]           FLOAT (53)    NULL,
    [MngCarFS2Desc]              VARCHAR (25)  NULL,
    [MngCarCFSurgery]            FLOAT (53)    NULL,
    [MngCarFS3Desc]              VARCHAR (25)  NULL,
    [MngCarMedicarePct]          FLOAT (53)    NULL,
    [MngCarMediCalPct]           FLOAT (53)    NULL,
    [MngCarCaseRate]             FLOAT (53)    NULL,
    [MngCarCEPWideYN]            BIT           NOT NULL,
    [MngCarInactiveYN]           BIT           NOT NULL,
    [MngCarFlagYN]               BIT           NOT NULL,
    [MngCarCaseRateLesserYN]     BIT           NULL,
    [MngCarPctChargeLesserYN]    BIT           NULL,
    [MngCarHoldHarmlessYN]       BIT           NULL,
    [MngCarCMSYN]                BIT           NULL,
    [MngCarCPTYN]                BIT           NULL,
    [MngCarReimbGuideOtherYN]    BIT           NULL,
    [MngCarInPatientRateYN]      BIT           NULL,
    [MngCarUCRateYN]             BIT           NULL,
    [MngCarContractURL]          VARCHAR (250) NULL,
    [MngCarAnniversaryDate]      DATETIME      NULL,
    [MngCarCID]                  VARCHAR (15)  NULL,
    [MngCarTIN]                  VARCHAR (15)  NULL,
    [MngCarInPatientRateDesc]    VARCHAR (250) NULL,
    [MngCarUCRateDesc]           VARCHAR (250) NULL,
    [MngCarReciprocityYN]        BIT           NOT NULL,
    [zMngCarRBRVSPct]            FLOAT (53)    NULL,
    [zMngCarBRRNE]               FLOAT (53)    NULL,
    [zMngCarMedicalScreenExam]   FLOAT (53)    NULL,
    [zMngCarEDHospFee]           FLOAT (53)    NULL,
    [zMngCarEDProfFee]           FLOAT (53)    NULL,
    [zMngCarUCHospFee]           FLOAT (53)    NULL,
    [zMngCarUCProfFee]           FLOAT (53)    NULL,
    [zMngCarOldID]               INT           NULL,
    [zMngCarPostSignIssues]      TEXT          NULL,
    PRIMARY KEY CLUSTERED ([MngCarID] ASC) WITH (FILLFACTOR = 90)
);

