CREATE TABLE [dbo].[tblSttBdgTemp] (
    [SttNetAmt]                   MONEY          NULL,
    [CtrSiteOvrHdpct]             REAL           NULL,
    [SiteName]                    NVARCHAR (100) NULL,
    [SttDate]                     DATETIME       NULL,
    [Stt_CtrID]                   INT            NULL,
    [SttID]                       INT            IDENTITY (1, 1) NOT NULL,
    [SttKey]                      NVARCHAR (100) NULL,
    [SttLink]                     INT            NULL,
    [SttAdmitQty]                 INT            NULL,
    [SttBillFee]                  MONEY          NULL,
    [SttBillRate]                 FLOAT (53)     NULL,
    [SttBillSpec]                 MONEY          NULL,
    [SttBseHour]                  FLOAT (53)     NULL,
    [SttChartQty]                 INT            NULL,
    [SttChartPostQty]             INT            NULL,
    [SttChartMissQty]             INT            NULL,
    [SttChartMiss30Qty]           INT            NULL,
    [SttCashARAmt]                MONEY          NULL,
    [SttCollectibleARAmt]         MONEY          NULL,
    [SttCollectWIP]               MONEY          NULL,
    [SttContribPct]               FLOAT (53)     NULL,
    [SttCurrLoanBal]              MONEY          NULL,
    [SttDiffAmt]                  FLOAT (53)     NULL,
    [SttDiffRate]                 FLOAT (53)     NULL,
    [SttDocHourQty]               FLOAT (53)     NULL,
    [SttDocPaidAdjAmt]            MONEY          NULL,
    [SttDocPaidAmt]               MONEY          NULL,
    [SttIntRate]                  FLOAT (53)     NULL,
    [SttLclExp]                   MONEY          NULL,
    [SttMDPaidAmt]                MONEY          NULL,
    [SttMDpct]                    FLOAT (53)     NULL,
    [SttMPRate]                   FLOAT (53)     NULL,
    [SttNightPct]                 FLOAT (53)     NULL,
    [SttNonCurrAdjAmt]            MONEY          NULL,
    [SttNorAmt]                   MONEY          NULL,
    [SttOffTop]                   MONEY          NULL,
    [SttOtherRcpts]               MONEY          NULL,
    [SttPACost]                   MONEY          NULL,
    [SttPAhoursQty]               FLOAT (53)     NULL,
    [SttPatVisitQty]              FLOAT (53)     NULL,
    [SttPhysTherVisitQty]         FLOAT (53)     NULL,
    [SttPstChgs]                  MONEY          NULL,
    [SttPTCost]                   MONEY          NULL,
    [SttPtsKeyed]                 FLOAT (53)     NULL,
    [SttRDPaidAmt]                MONEY          NULL,
    [SttRDpct]                    FLOAT (53)     NULL,
    [SttRefAR]                    MONEY          NULL,
    [SttSiteOvrHdPct]             FLOAT (53)     NULL,
    [SttSrpAdjAmt]                MONEY          NULL,
    [SttSrpAdjAmtComment]         NTEXT          NULL,
    [SttSrpAdjAmtPct]             FLOAT (53)     NULL,
    [SttStatPITpct]               FLOAT (53)     NULL,
    [SttStipRcvd]                 MONEY          NULL,
    [SttTargetRate]               FLOAT (53)     NULL,
    [SttUnspecifiedComment]       NTEXT          NULL,
    [SttValuationGainLossComment] NTEXT          NULL,
    [SttWIPGainLossComment]       NTEXT          NULL,
    [SttDateCreate]               DATETIME       NULL,
    [SttDateEdit]                 DATETIME       NULL,
    [SttInactiveYN]               BIT            NULL,
    [SttGrossCollAmt]             MONEY          NULL,
    [SttValuationGainLossAmt]     MONEY          NULL,
    [SttWIPGainLossAmt]           MONEY          NULL,
    [SttTotalCollAmt]             MONEY          NULL,
    [SttIntAmt]                   MONEY          NULL,
    [SttSiteOverheadAmt]          MONEY          NULL,
    [SttCompPITpct]               FLOAT (53)     NULL,
    [SttPTCostPct]                FLOAT (53)     NULL,
    [SttLclExpPct]                FLOAT (53)     NULL,
    [SttCompMDpct]                FLOAT (53)     NULL,
    [SttCompRDpct]                FLOAT (53)     NULL,
    [SttNonCurrAdjPct]            FLOAT (53)     NULL,
    [SttContribCEPAmt]            MONEY          NULL,
    [SttSiteNetIncAmt]            MONEY          NULL,
    [SttNetPctofNOR]              FLOAT (53)     NULL,
    [SttDocPaidHourAmt]           MONEY          NULL,
    [SttDocEarnedHourAmt]         MONEY          NULL,
    [SttPAPaidHourAmt]            MONEY          NULL,
    [SttPtsPerHr]                 FLOAT (53)     NULL,
    [SttBlendedPtsPerHr]          REAL           NULL,
    [SttAvgChgPt]                 MONEY          NULL,
    [SttCollPerPtAmt]             MONEY          NULL,
    [SttTotalCollPerPt]           MONEY          NULL,
    [SttAdjCollWIPAmt]            MONEY          NULL,
    [SttCollFeeAmt]               MONEY          NULL,
    [SttNetChangeinARAmt]         MONEY          NULL,
    [SttCashExpAmt]               MONEY          NULL,
    [SttCashRcptAmt]              MONEY          NULL,
    [SttPACostPct]                FLOAT (53)     NULL,
    [SttEndCollectAR]             MONEY          NULL,
    [SttMlpAmt]                   MONEY          NULL,
    [SttPriorCollectAR]           MONEY          NULL,
    [SttPriorLoanBal]             MONEY          NULL,
    [BdgPatients]                 REAL           NULL,
    [BdgPstChgs]                  MONEY          NULL,
    [BdgTargetRate]               REAL           NULL,
    [BdgOffTop]                   MONEY          NULL,
    [BdgLclExp]                   MONEY          NULL,
    [BdgPACost]                   MONEY          NULL,
    [BdgPTCost]                   MONEY          NULL,
    [BdgBillFee]                  MONEY          NULL,
    [BdgBillRate]                 REAL           NULL,
    [BdgBillSpec]                 MONEY          NULL,
    [BdgPITpct]                   REAL           NULL,
    [BdgPITEarnedPct]             REAL           NULL,
    [BdgMDpct]                    REAL           NULL,
    [BdgRDpct]                    REAL           NULL,
    [BdgContribPct]               REAL           NULL,
    [BdgInterestRate]             REAL           NULL,
    [BdgMPRate]                   REAL           NULL,
    [BdgStipendsRcvd]             MONEY          NULL,
    [BdgOthRcpts]                 MONEY          NULL,
    [BdgDocHours]                 REAL           NULL,
    [BdgPAHours]                  REAL           NULL,
    [BdgAvgChgPt]                 MONEY          NULL,
    [BdgMalpractice]              MONEY          NULL,
    [BdgInterest]                 MONEY          NULL,
    [BdgNOR]                      MONEY          NULL,
    [BdgContribCEP]               MONEY          NULL,
    [BdgPITearned]                MONEY          NULL,
    [BdgMDearned]                 MONEY          NULL,
    [BdgRDearned]                 MONEY          NULL,
    [BdgDocEarnedHrly]            MONEY          NULL,
    [BdgSiteNetInc]               MONEY          NULL,
    [BdgPACostPct]                REAL           NULL,
    [BdgPTCostPct]                REAL           NULL,
    [BdgSiteOvrHdPct]             REAL           NULL,
    [BdgLclExpPct]                REAL           NULL,
    [BdgNetPctofNOR]              REAL           NULL,
    [BdgNetRevPerPt]              MONEY          NULL,
    [BdgCollPerPt]                MONEY          NULL,
    [BdgPtsPerHr]                 REAL           NULL,
    [BdgGrossColl]                MONEY          NULL,
    [BdgTotalColl]                MONEY          NULL,
    [BdgSiteOverhead]             MONEY          NULL,
    [BdgPACostHr]                 MONEY          NULL,
    [BdgBlendedHrs]               REAL           NULL,
    [BdgBlendedPtsHr]             REAL           NULL,
    [BdgDateCreate]               DATETIME       NULL,
    [BdgDateEdit]                 DATETIME       NULL,
    [BdgInactiveYN]               BIT            NULL,
    [SttFlagYN]                   BIT            NULL
);

