CREATE TABLE [dbo].[tblTempPR197] (
    [COMPANY-4]           NVARCHAR (50)  NULL,
    [NAME-3]              NVARCHAR (100) NULL,
    [DIST-COMPANY-4]      NVARCHAR (50)  NULL,
    [NameOther]           NVARCHAR (50)  NULL,
    [PAYMENT-DATE-3]      DATETIME       NULL,
    [DIST-COMPANY-5]      NVARCHAR (50)  NULL,
    [ACCT-UNIT-3]         NVARCHAR (50)  NULL,
    [ACCOUNT-3]           NVARCHAR (50)  NULL,
    [SUB-ACCT-3]          NVARCHAR (255) NULL,
    [POSTING-DATE-2]      DATETIME       NULL,
    [DESCRIPTION-3]       NVARCHAR (255) NULL,
    [CONTINUED-2]         NVARCHAR (255) NULL,
    [EMPLOYEE-2]          NVARCHAR (50)  NULL,
    [FULL-NAME-2]         NVARCHAR (255) NULL,
    [DIST-UNITS]          NVARCHAR (50)  NULL,
    [DIST-HOURS]          FLOAT (53)     NULL,
    [DIST-AMT]            FLOAT (53)     NULL,
    [CHECK-NBR]           NVARCHAR (53)  NULL,
    [TEMP-STAR]           NVARCHAR (50)  NULL,
    [GL-DATE-2]           DATETIME       NULL,
    [CHECK-TYPE]          NVARCHAR (50)  NULL,
    [PAY-CODE]            NVARCHAR (50)  NULL,
    [DED-CODE]            NVARCHAR (50)  NULL,
    [JOB-CODE]            NVARCHAR (50)  NULL,
    [DIST-PROC-LEV]       NVARCHAR (50)  NULL,
    [DEPARTMENT-3]        NVARCHAR (50)  NULL,
    [DIST-UNITS-2]        NVARCHAR (50)  NULL,
    [DIST-HOURS-2]        FLOAT (53)     NULL,
    [DIST-AMT-2]          FLOAT (53)     NULL,
    [ACTIVITY]            NVARCHAR (50)  NULL,
    [ACCT-CATEGORY]       NVARCHAR (50)  NULL,
    [POSITION]            NVARCHAR (50)  NULL,
    [DataSetDate]         DATETIME       NULL,
    [FileName]            NVARCHAR (200) NULL,
    [zDescription]        NVARCHAR (255) NULL,
    [zDataSetDescription] VARCHAR (50)   NULL
);

