CREATE TABLE [dbo].[tblTempPay_Ade] (
    [PayID]             INT            NOT NULL,
    [Pay_CtrID]         INT            NULL,
    [Pay_CntID]         INT            NULL,
    [PayMonth]          DATETIME       NOT NULL,
    [PayPaidAmt]        MONEY          NOT NULL,
    [PayHours]          FLOAT (53)     NOT NULL,
    [PayPayType]        CHAR (1)       NULL,
    [PayPayCode]        NVARCHAR (50)  NULL,
    [PayPayCodeSummary] NVARCHAR (50)  NULL,
    [PayJobCode]        NVARCHAR (50)  NULL,
    [PayJobCodeSummary] NVARCHAR (50)  NULL,
    [PaySitelineClass]  NVARCHAR (15)  NULL,
    [PayFullName]       VARCHAR (200)  NULL,
    [PayGLPostDate]     DATETIME       NULL,
    [PayCheckDate]      DATETIME       NULL,
    [PayProcLevel]      NVARCHAR (50)  NULL,
    [PaySource]         NVARCHAR (50)  NULL,
    [PayFileName]       NVARCHAR (200) NULL,
    [PayImportDate]     DATETIME       NOT NULL,
    [PayDistCompany5]   VARCHAR (15)   NULL,
    [PayAccount3]       VARCHAR (15)   NULL,
    [PayAccountUnit]    VARCHAR (15)   NULL,
    [PayLastEditDate]   DATETIME       NULL,
    [PayLastEditName]   VARCHAR (50)   NULL,
    [PayTimeStamp]      ROWVERSION     NOT NULL,
    PRIMARY KEY CLUSTERED ([PayID] ASC)
);

