CREATE TABLE [dbo].[tblTempTblStt] (
    [SttNetAmt]                   MONEY         NULL,
    [CtrSiteOvrHdpct]             FLOAT (53)    NULL,
    [Site]                        VARCHAR (75)  NULL,
    [SttDate]                     SMALLDATETIME NOT NULL,
    [Stt_CtrID]                   INT           NOT NULL,
    [SttKey]                      VARCHAR (100) NULL,
    [SttLink]                     INT           NULL,
    [SttAdmitQty]                 INT           NULL,
    [SttBillFee]                  MONEY         NULL,
    [SttBillRate]                 FLOAT (53)    NULL,
    [SttBillSpec]                 MONEY         NULL,
    [SttBseHour]                  FLOAT (53)    NULL,
    [SttChartQty]                 INT           NULL,
    [SttChartPostQty]             INT           NULL,
    [SttChartMissQty]             INT           NULL,
    [SttChartMiss30Qty]           INT           NULL,
    [SttCashARAmt]                MONEY         NULL,
    [SttCollectibleARAmt]         MONEY         NULL,
    [SttCollectWIP]               MONEY         NULL,
    [SttContribPct]               FLOAT (53)    NULL,
    [SttCurrLoanBal]              MONEY         NULL,
    [SttDiffAmt]                  FLOAT (53)    NULL,
    [SttDiffRate]                 FLOAT (53)    NULL,
    [SttDocHourQty]               FLOAT (53)    NULL,
    [SttDocPaidAdjAmt]            MONEY         NULL,
    [SttDocPaidAmt]               MONEY         NULL,
    [SttIntRate]                  FLOAT (53)    NULL,
    [SttLclExp]                   MONEY         NULL,
    [SttMDPaidAmt]                MONEY         NULL,
    [SttMDpct]                    FLOAT (53)    NULL,
    [SttMPRate]                   FLOAT (53)    NULL,
    [SttNightPct]                 FLOAT (53)    NULL,
    [SttNonCurrAdjAmt]            MONEY         NULL,
    [SttNorAmt]                   MONEY         NULL,
    [SttOffTop]                   MONEY         NULL,
    [SttOtherRcpts]               MONEY         NULL,
    [SttPACost]                   MONEY         NULL,
    [SttPAhoursQty]               FLOAT (53)    NULL,
    [SttPatVisitQty]              INT           NULL,
    [SttPhysTherVisitQty]         FLOAT (53)    NULL,
    [SttPstChgs]                  MONEY         NULL,
    [SttPTCost]                   MONEY         NULL,
    [SttPtsKeyed]                 INT           NULL,
    [SttRDPaidAmt]                MONEY         NULL,
    [SttRDpct]                    FLOAT (53)    NULL,
    [SttRefAR]                    MONEY         NULL,
    [SttSiteOvrHdPct]             FLOAT (53)    NULL,
    [SttSrpAdjAmt]                MONEY         NULL,
    [SttSrpAdjAmtComment]         TEXT          NULL,
    [SttSrpAdjAmtPct]             FLOAT (53)    NULL,
    [SttStatPITpct]               FLOAT (53)    NULL,
    [SttStipRcvd]                 MONEY         NULL,
    [SttTargetRate]               FLOAT (53)    NULL,
    [SttUnspecifiedComment]       TEXT          NULL,
    [SttValuationGainLossComment] TEXT          NULL,
    [SttWIPGainLossComment]       TEXT          NULL,
    [SttDateCreate]               SMALLDATETIME NULL,
    [SttDateEdit]                 SMALLDATETIME NULL,
    [SttInactiveYN]               BIT           NULL,
    [SttGrossCollAmt]             MONEY         NULL,
    [SttValuationGainLossAmt]     MONEY         NULL,
    [SttWIPGainLossAmt]           MONEY         NULL,
    [SttTotalCollAmt]             MONEY         NULL,
    [SttIntAmt]                   MONEY         NULL,
    [SttSiteOverheadAmt]          MONEY         NULL,
    [SttCompPITpct]               FLOAT (53)    NULL,
    [SttPTCostPct]                FLOAT (53)    NULL,
    [SttLclExpPct]                FLOAT (53)    NULL,
    [SttCompMDpct]                FLOAT (53)    NULL,
    [SttCompRDpct]                FLOAT (53)    NULL,
    [SttNonCurrAdjPct]            FLOAT (53)    NULL,
    [SttContribCEPAmt]            MONEY         NULL,
    [SttSiteNetIncAmt]            MONEY         NULL,
    [SttNetPctofNOR]              FLOAT (53)    NULL,
    [SttDocPaidHourAmt]           MONEY         NULL,
    [SttDocEarnedHourAmt]         MONEY         NULL,
    [SttPAPaidHourAmt]            MONEY         NULL,
    [SttPtsPerHr]                 FLOAT (53)    NULL,
    [SttBlendedPtsPerHr]          FLOAT (53)    NULL,
    [SttAvgChgPt]                 MONEY         NULL,
    [SttCollPerPtAmt]             MONEY         NULL,
    [SttTotalCollPerPt]           MONEY         NULL,
    [SttAdjCollWIPAmt]            MONEY         NULL,
    [SttCollFeeAmt]               MONEY         NULL,
    [SttNetChangeinARAmt]         MONEY         NULL,
    [SttCashExpAmt]               MONEY         NULL,
    [SttCashRcptAmt]              MONEY         NULL,
    [SttPACostPct]                FLOAT (53)    NULL,
    [SttEndCollectAR]             MONEY         NULL,
    [SttMlpAmt]                   MONEY         NULL,
    [SttPriorCollectAR]           MONEY         NULL,
    [SttPriorLoanBal]             MONEY         NULL,
    [BdgPatients]                 INT           NOT NULL,
    [BdgPstChgs]                  MONEY         NOT NULL,
    [BdgTargetRate]               FLOAT (53)    NOT NULL,
    [BdgOffTop]                   MONEY         NOT NULL,
    [BdgLclExp]                   MONEY         NOT NULL,
    [BdgPACost]                   MONEY         NOT NULL,
    [BdgPTCost]                   MONEY         NOT NULL,
    [BdgBillFee]                  MONEY         NOT NULL,
    [BdgBillRate]                 FLOAT (53)    NOT NULL,
    [BdgBillSpec]                 MONEY         NOT NULL,
    [BdgPITpct]                   FLOAT (53)    NOT NULL,
    [BdgPITEarnedPct]             FLOAT (53)    NOT NULL,
    [BdgMDpct]                    FLOAT (53)    NOT NULL,
    [BdgRDpct]                    FLOAT (53)    NOT NULL,
    [BdgContribPct]               FLOAT (53)    NOT NULL,
    [BdgInterestRate]             FLOAT (53)    NOT NULL,
    [BdgMPRate]                   FLOAT (53)    NOT NULL,
    [BdgStipendsRcvd]             MONEY         NOT NULL,
    [BdgOthRcpts]                 MONEY         NOT NULL,
    [BdgDocHours]                 FLOAT (53)    NOT NULL,
    [BdgPAHours]                  FLOAT (53)    NOT NULL,
    [BdgAvgChgPt]                 MONEY         NOT NULL,
    [BdgMalpractice]              MONEY         NOT NULL,
    [BdgInterest]                 MONEY         NOT NULL,
    [BdgNOR]                      MONEY         NOT NULL,
    [BdgContribCEP]               MONEY         NOT NULL,
    [BdgPITearned]                MONEY         NOT NULL,
    [BdgMDearned]                 MONEY         NOT NULL,
    [BdgRDearned]                 MONEY         NOT NULL,
    [BdgDocEarnedHrly]            MONEY         NOT NULL,
    [BdgSiteNetInc]               MONEY         NOT NULL,
    [BdgPACostPct]                FLOAT (53)    NOT NULL,
    [BdgPTCostPct]                FLOAT (53)    NOT NULL,
    [BdgSiteOvrHdPct]             FLOAT (53)    NOT NULL,
    [BdgLclExpPct]                FLOAT (53)    NOT NULL,
    [BdgNetPctofNOR]              FLOAT (53)    NOT NULL,
    [BdgNetRevPerPt]              MONEY         NOT NULL,
    [BdgCollPerPt]                MONEY         NOT NULL,
    [BdgPtsPerHr]                 FLOAT (53)    NOT NULL,
    [BdgGrossColl]                MONEY         NOT NULL,
    [BdgTotalColl]                MONEY         NOT NULL,
    [BdgSiteOverhead]             MONEY         NOT NULL,
    [BdgPACostHr]                 MONEY         NOT NULL,
    [BdgBlendedHrs]               FLOAT (53)    NOT NULL,
    [BdgBlendedPtsHr]             FLOAT (53)    NOT NULL,
    [BdgDateCreate]               SMALLDATETIME NULL,
    [BdgDateEdit]                 SMALLDATETIME NULL,
    [BdgInactiveYN]               BIT           CONSTRAINT [DF_tblTempTblStt_BdgInactiveYN] DEFAULT (0) NULL,
    [SttFlagYN]                   BIT           CONSTRAINT [DF_tblTempTblStt_SttFlagYN] DEFAULT (0) NULL
);

