CREATE TABLE [dbo].[tblTempProviderMaster] (
    [ProviderMasterID]            INT           NOT NULL,
    [SSNFormatted]                VARCHAR (11)  NULL,
    [SSNUnformatted]              CHAR (10)     NULL,
    [TaxIDIncorporated]           VARCHAR (11)  NULL,
    [LastName]                    VARCHAR (50)  NULL,
    [FirstName]                   VARCHAR (50)  NULL,
    [MiddleNameOrInitial]         VARCHAR (50)  NULL,
    [PreferredName]               VARCHAR (50)  NULL,
    [IncorporatedName]            VARCHAR (100) NULL,
    [FormerLastName]              VARCHAR (50)  NULL,
    [FormerFirstName]             VARCHAR (50)  NULL,
    [FormerMiddleName]            VARCHAR (50)  NULL,
    [Title]                       VARCHAR (100) NULL,
    [Gender]                      VARCHAR (10)  NULL,
    [RecordType]                  VARCHAR (20)  NULL,
    [RecordStatus]                VARCHAR (20)  NULL,
    [PartnershipLevel]            VARCHAR (100) NULL,
    [EchoPartnershipLevelCode]    CHAR (3)      NULL,
    [PartnershipLevelDate]        DATETIME      NULL,
    [PartnershipLevelCode]        VARCHAR (10)  NULL,
    [DateOfBirth]                 DATETIME      NULL,
    [DateOfHire]                  DATETIME      NULL,
    [MaritalStatusCode]           CHAR (1)      NULL,
    [MaritalStatus]               VARCHAR (50)  NULL,
    [SpouseName]                  VARCHAR (100) NULL,
    [EmailAddress1]               VARCHAR (100) NULL,
    [EmailAddress2]               VARCHAR (100) NULL,
    [CellPhoneNbr]                VARCHAR (50)  NULL,
    [PagerNbr]                    VARCHAR (50)  NULL,
    [WebID]                       INT           NULL,
    [CeridianFlxID]               INT           NULL,
    [CeridianClockNbr]            INT           NULL,
    [CeridianEbPSID]              VARCHAR (8)   NULL,
    [SiteLineCntID]               INT           NULL,
    [Echo_dr_no_ext]              CHAR (12)     NULL,
    [ExchangeDirectoryName]       VARCHAR (50)  NULL,
    [ExchangeContainer]           VARCHAR (100) NULL,
    [ExchangeDirectoryName2]      VARCHAR (50)  NULL,
    [ExchangeContainer2]          VARCHAR (100) NULL,
    [ActiveInactiveFlag]          CHAR (1)      NULL,
    [CurrentlyNotComparedFlag]    CHAR (1)      CONSTRAINT [DF_ProviderMaster_CurrentlyNotComparedFlag] DEFAULT ('N') NULL,
    [DuplicateOfProviderMasterID] INT           NULL,
    [StaffStatus]                 VARCHAR (50)  NULL,
    [CurrentStaffFlag]            CHAR (1)      CONSTRAINT [DF_ProviderMaster_CurrentStaffFlag] DEFAULT ('Y') NULL,
    [CurrentProviderFlag]         CHAR (1)      CONSTRAINT [DF_ProviderMaster_CurrentProviderFlag] DEFAULT ('N') NULL,
    [NeedToFix]                   CHAR (1)      NULL,
    [CurrentlyIncorporatedFlag]   CHAR (1)      NULL,
    [FormerlyIncorporatedFlag]    CHAR (1)      NULL,
    [EMANewJersey]                CHAR (1)      CONSTRAINT [DF_ProviderMaster_EMANewJersey] DEFAULT ('N') NULL,
    [SSNIncorrectFlag]            CHAR (1)      CONSTRAINT [DF_ProviderMaster_SSNIncorrectFlag] DEFAULT ('N') NULL,
    [LoadFlag]                    CHAR (1)      NULL,
    [CREDate]                     DATETIME      CONSTRAINT [DF_ProviderMaster_CREDate] DEFAULT (getdate()) NULL,
    [UPDDate]                     DATETIME      CONSTRAINT [DF_ProviderMaster_UPDDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_tblTempProviderMaster] PRIMARY KEY NONCLUSTERED ([ProviderMasterID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE CLUSTERED INDEX [ProviderMaster_ProviderMasterID_idx]
    ON [dbo].[tblTempProviderMaster]([ProviderMasterID] ASC) WITH (FILLFACTOR = 90);

