CREATE TABLE [dbo].[BSwiftDemographicsMaster_12262013] (
    [GROUP NUMBER]           VARCHAR (10)    NULL,
    [USERID]                 VARCHAR (20)    NULL,
    [EMPLOYEEID]             INT             NULL,
    [RELATION]               VARCHAR (1)     NULL,
    [FIRST NAME]             NVARCHAR (255)  NULL,
    [LAST NAME]              NVARCHAR (255)  NULL,
    [BENEFIT CLASS CODE]     NVARCHAR (255)  NULL,
    [BENEFIT CLASS DATE]     DATETIME        NULL,
    [SALARY]                 DECIMAL (13, 4) NULL,
    [HOURLY RATE]            DECIMAL (13, 4) NULL,
    [HOURS PER WEEK]         INT             NULL,
    [BENEFITS BASE SALARY]   DECIMAL (13, 4) NULL,
    [SOCIAL SECURITY NUMBER] VARCHAR (20)    NULL,
    [DATE OF BIRTH]          DATETIME        NULL,
    [GENDER]                 VARCHAR (1)     NULL,
    [BENEFIT CALC DATE]      DATETIME        NULL,
    [HIRE DATE]              DATETIME        NULL,
    [PAYROLL ID]             INT             NULL,
    [TIME STATUS]            VARCHAR (1)     NULL,
    [PAY FREQUENCY]          VARCHAR (6)     NULL,
    [WORK EMAIL]             NVARCHAR (255)  NULL,
    [USER NAME]              NVARCHAR (255)  NULL,
    [HOME ADDRESS1]          NVARCHAR (255)  NULL,
    [HOME ADDRESS2]          NVARCHAR (255)  NULL,
    [CITY]                   NVARCHAR (255)  NULL,
    [STATE]                  NVARCHAR (255)  NULL,
    [ZIP]                    CHAR (10)       NULL,
    [EMPLOYMENT STATUS]      VARCHAR (1)     NULL,
    [TERMINATIONREASON]      VARCHAR (2)     NULL,
    [TERMINATIONDATE]        DATETIME        NULL,
    [BENEFIT FIELD 2]        CHAR (20)       NULL,
    [BENEFIT FIELD 3]        CHAR (20)       NULL,
    [BENEFIT FIELD 4]        CHAR (20)       NULL,
    [AUTOENROLL]             VARCHAR (1)     NULL,
    [EMPLOYMENT FIELD 1]     VARCHAR (55)    NULL
);

