CREATE TABLE [dbo].[BSwiftDemographicsMaster] (
    [GROUP NUMBER]           VARCHAR (10)    NULL,
    [USERID]                 VARCHAR (20)    NULL,
    [EMPLOYEEID]             INT             NULL,
    [RELATION]               VARCHAR (1)     NULL,
    [FIRST NAME]             NVARCHAR (255)  NULL,
    [LAST NAME]              NVARCHAR (255)  NULL,
    [BENEFIT CLASS CODE]     NVARCHAR (255)  NULL,
    [BENEFIT CLASS DATE]     DATE            NULL,
    [SALARY]                 DECIMAL (13, 4) NULL,
    [HOURLY RATE]            DECIMAL (13, 4) NULL,
    [HOURS PER WEEK]         INT             NULL,
    [BENEFITS BASE SALARY]   DECIMAL (13, 4) NULL,
    [SOCIAL SECURITY NUMBER] VARCHAR (20)    NULL,
    [DATE OF BIRTH]          DATE            NULL,
    [GENDER]                 VARCHAR (1)     NULL,
    [BENEFIT CALC DATE]      DATE            NULL,
    [HIRE DATE]              DATE            NULL,
    [ADJ HIRE DATE]          DATE            NULL,
    [PAYROLL ID]             INT             NULL,
    [TIME STATUS]            VARCHAR (1)     NULL,
    [PAY FREQUENCY]          VARCHAR (6)     NULL,
    [WORK EMAIL]             NVARCHAR (255)  NULL,
    [USER NAME]              NVARCHAR (255)  NULL,
    [HOME ADDRESS1]          NVARCHAR (255)  NULL,
    [HOME ADDRESS2]          NVARCHAR (255)  NULL,
    [CITY]                   NVARCHAR (255)  NULL,
    [STATE]                  NVARCHAR (255)  NULL,
    [ZIP]                    CHAR (10)       NULL,
    [EMPLOYMENT STATUS]      VARCHAR (1)     NULL,
    [TERMINATIONREASON]      VARCHAR (2)     NULL,
    [TERMINATIONDATE]        DATE            NULL,
    [BENEFIT FIELD 2]        CHAR (20)       NULL,
    [BENEFIT FIELD 3]        CHAR (20)       NULL,
    [BENEFIT FIELD 4]        CHAR (20)       NULL,
    [BEN DATE 3]             DATE            NULL,
    [AUTOENROLL]             VARCHAR (1)     NULL,
    [EMPLOYMENT FIELD 1]     VARCHAR (55)    NULL,
    [PA FLAG]                VARCHAR (1)     NULL,
    [EMPLOYEE TYPE]          CHAR (10)       NULL
);

