CREATE TABLE [dbo].[BSwiftDemographics] (
    [GROUP NUMBER]           VARCHAR (10)    NOT NULL,
    [USERID]                 VARCHAR (20)    NULL,
    [EMPLOYEEID]             INT             NOT NULL,
    [RELATION]               VARCHAR (1)     NOT NULL,
    [FIRST NAME]             CHAR (15)       NOT NULL,
    [LAST NAME]              VARCHAR (8000)  NULL,
    [BENEFIT CLASS CODE]     VARCHAR (11)    NOT NULL,
    [BENEFIT CLASS DATE]     DATETIME        NOT NULL,
    [SALARY]                 DECIMAL (13, 4) NOT NULL,
    [HOURLY RATE]            DECIMAL (13, 4) NOT NULL,
    [HOURS PER WEEK]         INT             NOT NULL,
    [BENEFITS BASE SALARY]   DECIMAL (13, 4) NOT NULL,
    [SOCIAL SECURITY NUMBER] VARCHAR (20)    NULL,
    [DATE OF BIRTH]          DATETIME        NOT NULL,
    [GENDER]                 CHAR (1)        NOT NULL,
    [BENEFIT CALC DATE]      DATETIME        NOT NULL,
    [HIRE DATE]              DATETIME        NOT NULL,
    [ADJ HIRE DATE]          DATETIME        NOT NULL,
    [PAYROLL ID]             INT             NOT NULL,
    [TIME STATUS]            VARCHAR (1)     NULL,
    [PAY FREQUENCY]          VARCHAR (6)     NOT NULL,
    [WORK EMAIL]             CHAR (60)       NOT NULL,
    [USER NAME]              VARCHAR (35)    NOT NULL,
    [HOME ADDRESS1]          VARCHAR (8000)  NULL,
    [HOME ADDRESS2]          VARCHAR (8000)  NULL,
    [CITY]                   VARCHAR (8000)  NULL,
    [STATE]                  CHAR (2)        NOT NULL,
    [ZIP]                    CHAR (10)       NOT NULL,
    [EMPLOYMENT STATUS]      VARCHAR (1)     NOT NULL,
    [TERMINATIONREASON]      VARCHAR (1)     NOT NULL,
    [TERMINATIONDATE]        VARCHAR (1)     NOT NULL,
    [BENEFIT FIELD 2]        CHAR (2)        NOT NULL,
    [BENEFIT FIELD 3]        CHAR (12)       NOT NULL,
    [BENEFIT FIELD 4]        CHAR (5)        NOT NULL,
    [BEN DATE 3]             DATETIME        NULL,
    [AUTOENROLL]             VARCHAR (1)     NOT NULL,
    [EMPLOYEE TYPE]          CHAR (10)       NULL,
    [EMPLOYMENT FIELD 1]     VARCHAR (50)    NULL
);

