CREATE TABLE [dbo].[BSwiftDemographicsMasterBackup] (
    [GROUP NUMBER]           NVARCHAR (255) NULL,
    [USERID]                 NVARCHAR (255) NULL,
    [EMPLOYEEID]             FLOAT (53)     NULL,
    [RELATION]               NVARCHAR (255) NULL,
    [FIRST NAME]             NVARCHAR (255) NULL,
    [LAST NAME]              NVARCHAR (255) NULL,
    [BENEFIT CLASS CODE]     NVARCHAR (255) NULL,
    [BENEFIT CLASS DATE]     DATETIME       NULL,
    [SALARY]                 FLOAT (53)     NULL,
    [HOURLY RATE]            FLOAT (53)     NULL,
    [HOURS PER WEEK]         FLOAT (53)     NULL,
    [BENEFITS BASE SALARY]   FLOAT (53)     NULL,
    [SOCIAL SECURITY NUMBER] NVARCHAR (255) NULL,
    [DATE OF BIRTH]          DATETIME       NULL,
    [GENDER]                 NVARCHAR (255) NULL,
    [BENEFIT CALC DATE]      DATETIME       NULL,
    [HIRE DATE]              DATETIME       NULL,
    [PAYROLL ID]             FLOAT (53)     NULL,
    [TIME STATUS]            FLOAT (53)     NULL,
    [PAY FREQUENCY]          FLOAT (53)     NULL,
    [WORK EMAIL]             NVARCHAR (255) NULL,
    [USER NAME]              NVARCHAR (255) NULL,
    [HOME ADDRESS1]          NVARCHAR (255) NULL,
    [HOME ADDRESS2]          NVARCHAR (255) NULL,
    [CITY]                   NVARCHAR (255) NULL,
    [STATE]                  NVARCHAR (255) NULL,
    [ZIP]                    FLOAT (53)     NULL,
    [EMPLOYMENT STATUS]      NVARCHAR (255) NULL,
    [TERMINATIONREASON]      NVARCHAR (255) NULL,
    [TERMINATIONDATE]        NVARCHAR (255) NULL,
    [BENEFIT FIELD 2]        NVARCHAR (255) NULL,
    [BENEFIT FIELD 3]        NVARCHAR (255) NULL,
    [BENEFIT FIELD 4]        FLOAT (53)     NULL,
    [BEN DATE 3]             DATETIME       NULL,
    [AUTOENROLL]             FLOAT (53)     NULL,
    [EMPLOYMENT FIELD 1]     NVARCHAR (255) NULL,
    [EMPLOYEE TYPE]          CHAR (10)      NULL
);

