CREATE TABLE [dbo].[CEPS] (
    [Last Name]       NVARCHAR (255) NULL,
    [First Name]      NVARCHAR (255) NULL,
    [MDBLAST]         VARCHAR (100)  NULL,
    [MDBFIRST]        VARCHAR (50)   NULL,
    [MatchFlag]       CHAR (1)       NULL,
    [Title]           NVARCHAR (255) NULL,
    [Email]           NVARCHAR (255) NULL,
    [Staff Group]     NVARCHAR (255) NULL,
    [Practice Line 1] NVARCHAR (255) NULL,
    [Practice Line 2] NVARCHAR (255) NULL,
    [Practice Line 3] NVARCHAR (255) NULL,
    [Practice Line 4] NVARCHAR (255) NULL,
    [Site 1]          NVARCHAR (255) NULL,
    [Site 2]          NVARCHAR (255) NULL,
    [Site 3]          NVARCHAR (255) NULL,
    [Site 4]          NVARCHAR (255) NULL,
    [Site 5]          NVARCHAR (255) NULL,
    [Site 6]          NVARCHAR (255) NULL,
    [Site 7]          NVARCHAR (255) NULL,
    [Site 8]          NVARCHAR (255) NULL,
    [Site 9]          NVARCHAR (255) NULL,
    [Site 10]         NVARCHAR (255) NULL,
    [Site 11]         NVARCHAR (255) NULL,
    [Site 12]         NVARCHAR (255) NULL,
    [Site 13]         NVARCHAR (255) NULL,
    [Site 14]         NVARCHAR (255) NULL,
    [Work Phone]      NVARCHAR (255) NULL,
    [Extension]       NVARCHAR (255) NULL,
    [Work Address]    NVARCHAR (255) NULL
);

