CREATE TABLE [dbo].[Contractlogix] (
    [ as of 1/30/2015] NVARCHAR (255) NULL,
    [F2]               DATETIME       NULL,
    [F3]               NVARCHAR (255) NULL,
    [F4]               NVARCHAR (255) NULL,
    [F5]               NVARCHAR (255) NULL,
    [F6]               NVARCHAR (255) NULL,
    [F7]               NVARCHAR (255) NULL,
    [F8]               NVARCHAR (255) NULL,
    [F9]               NVARCHAR (255) NULL,
    [F10]              NVARCHAR (255) NULL,
    [F11]              NVARCHAR (255) NULL,
    [F12]              NVARCHAR (255) NULL,
    [F13]              NVARCHAR (255) NULL,
    [F14]              NVARCHAR (255) NULL,
    [F15]              NVARCHAR (255) NULL,
    [F16]              NVARCHAR (255) NULL,
    [F17]              NVARCHAR (255) NULL,
    [F18]              DATETIME       NULL,
    [F19]              DATETIME       NULL,
    [F20]              DATETIME       NULL,
    [F21]              NVARCHAR (255) NULL,
    [F22]              NVARCHAR (255) NULL,
    [F23]              NVARCHAR (255) NULL,
    [F24]              NVARCHAR (255) NULL,
    [F25]              NVARCHAR (255) NULL,
    [F26]              NVARCHAR (255) NULL,
    [F27]              NVARCHAR (255) NULL,
    [F28]              NVARCHAR (255) NULL,
    [F29]              DATETIME       NULL,
    [F30]              DATETIME       NULL,
    [F31]              NVARCHAR (255) NULL,
    [F32]              NVARCHAR (255) NULL,
    [F33]              NVARCHAR (255) NULL,
    [F34]              NVARCHAR (255) NULL,
    [F35]              NVARCHAR (255) NULL,
    [F36]              NVARCHAR (255) NULL,
    [F37]              NVARCHAR (255) NULL,
    [F38]              NVARCHAR (255) NULL
);

