CREATE TABLE [dbo].[Dir_TestFlatData] (
    [EDID]                   INT            NOT NULL,
    [WebID]                  INT            NULL,
    [MPID]                   INT            NULL,
    [FirstName]              VARCHAR (255)  NULL,
    [PreferredFirstName]     VARCHAR (255)  NULL,
    [MiddleName]             VARCHAR (255)  NULL,
    [LastName]               VARCHAR (255)  NULL,
    [SuggestionKeywords]     VARCHAR (1279) NULL,
    [SimpleTitle]            VARCHAR (50)   NULL,
    [Address1]               VARCHAR (255)  NULL,
    [City1]                  VARCHAR (50)   NULL,
    [State1]                 VARCHAR (10)   NULL,
    [Zip1]                   VARCHAR (12)   NULL,
    [Country1]               VARCHAR (100)  NULL,
    [Address2]               VARCHAR (255)  NULL,
    [City2]                  VARCHAR (50)   NULL,
    [State2]                 VARCHAR (10)   NULL,
    [Zip2]                   VARCHAR (12)   NULL,
    [Country2]               VARCHAR (100)  NULL,
    [Phone1]                 VARCHAR (50)   NULL,
    [Phone2]                 VARCHAR (50)   NULL,
    [CellPhone]              VARCHAR (50)   NULL,
    [Email1]                 VARCHAR (50)   NULL,
    [Email2]                 VARCHAR (50)   NULL,
    [Fax1]                   VARCHAR (50)   NULL,
    [Fax2]                   VARCHAR (50)   NULL,
    [SSN]                    CHAR (9)       NULL,
    [HireDate]               SMALLDATETIME  NULL,
    [Photo]                  VARCHAR (1000) NULL,
    [Status]                 VARCHAR (10)   NULL,
    [Birthdate]              SMALLDATETIME  NULL,
    [LastLoaded]             DATETIME       NULL,
    [LevelNumber]            VARCHAR (5)    NULL,
    [MedSchool]              VARCHAR (1000) NULL,
    [SpouseName]             VARCHAR (500)  NULL,
    [InCorporatedTaxID]      VARCHAR (500)  NULL,
    [InCorporatedName]       VARCHAR (500)  NULL,
    [MaritalStatus]          VARCHAR (100)  NULL,
    [TwitterURL]             VARCHAR (1000) NULL,
    [LinkedInURL]            VARCHAR (1000) NULL,
    [SiteCodeList]           VARCHAR (100)  NULL,
    [GroupID]                INT            NULL,
    [DisplayTitle]           VARCHAR (1000) NULL,
    [DisplayAddress_line1]   VARCHAR (500)  NULL,
    [DisplayAddress_line2]   VARCHAR (500)  NULL,
    [DisplayPhone]           VARCHAR (500)  NULL,
    [IsExecOfficer]          BIT            NULL,
    [IsRegionalDirector]     BIT            NULL,
    [IsMedicalDirector]      BIT            NULL,
    [IsAsstMedDirector]      BIT            NULL,
    [IsPhysician]            BIT            NULL,
    [IsPANP]                 BIT            NULL,
    [IsMedAmerica]           BIT            NULL,
    [IsMBSI]                 BIT            NULL,
    [IsEMPhyscian]           BIT            NULL,
    [IsHospitalist]          BIT            NULL,
    [IsACCPhysician]         BIT            NULL,
    [IsBoard]                BIT            NULL,
    [IsCPAC]                 BIT            NULL,
    [IsScribe]               BIT            NULL,
    [IsArizona]              BIT            NULL,
    [IsCalifornia]           BIT            NULL,
    [IsGeorgia]              BIT            NULL,
    [IsIllinois]             BIT            NULL,
    [IsKentucky]             BIT            NULL,
    [IsNorthernDiv]          BIT            NULL,
    [IsCentralDiv]           BIT            NULL,
    [IsSouthernDiv]          BIT            NULL,
    [IsEasternDiv]           BIT            NULL,
    [IsHospitalistDiv]       BIT            NULL,
    [IsACCNReg]              BIT            NULL,
    [IsCentralReg]           BIT            NULL,
    [IsACCSReg]              BIT            NULL,
    [IsCCHReg]               BIT            NULL,
    [IsArizonaReg]           BIT            NULL,
    [IsWashington]           BIT            NULL,
    [IsDirectoryPhoneNumber] BIT            NULL,
    [IsPayrollMailAddress]   BIT            NULL,
    [IsCEPAUC]               BIT            NULL
);

