CREATE TABLE [dbo].[Emeritus] (
    [Title]                    VARCHAR (255) NULL,
    [First Name]               VARCHAR (255) NULL,
    [Middle Name]              VARCHAR (255) NULL,
    [Last Name]                VARCHAR (255) NULL,
    [Suffix]                   VARCHAR (255) NULL,
    [Company]                  VARCHAR (255) NULL,
    [Department]               VARCHAR (255) NULL,
    [Job Title]                VARCHAR (255) NULL,
    [Business Street]          VARCHAR (255) NULL,
    [Business Street 2]        VARCHAR (255) NULL,
    [Business Street 3]        VARCHAR (255) NULL,
    [Business City]            VARCHAR (255) NULL,
    [Business State]           VARCHAR (255) NULL,
    [Business Postal Code]     VARCHAR (255) NULL,
    [Business Country]         VARCHAR (255) NULL,
    [Home Street]              VARCHAR (255) NULL,
    [Home Street 2]            VARCHAR (255) NULL,
    [Home Street 3]            VARCHAR (255) NULL,
    [Home City]                VARCHAR (255) NULL,
    [Home State]               VARCHAR (255) NULL,
    [Home Postal Code]         VARCHAR (255) NULL,
    [Home Country]             VARCHAR (255) NULL,
    [Other Street]             VARCHAR (255) NULL,
    [Other Street 2]           VARCHAR (255) NULL,
    [Other Street 3]           VARCHAR (255) NULL,
    [Other City]               VARCHAR (255) NULL,
    [Other State]              VARCHAR (255) NULL,
    [Other Postal Code]        VARCHAR (255) NULL,
    [Other Country]            VARCHAR (255) NULL,
    [Assistant's Phone]        VARCHAR (255) NULL,
    [Business Fax]             VARCHAR (255) NULL,
    [Business Phone]           VARCHAR (255) NULL,
    [Business Phone 2]         VARCHAR (255) NULL,
    [Callback]                 VARCHAR (255) NULL,
    [Car Phone]                VARCHAR (255) NULL,
    [Company Main Phone]       VARCHAR (255) NULL,
    [Home Fax]                 VARCHAR (255) NULL,
    [Home Phone]               VARCHAR (255) NULL,
    [Home Phone 2]             VARCHAR (255) NULL,
    [ISDN]                     VARCHAR (255) NULL,
    [Mobile Phone]             VARCHAR (255) NULL,
    [Other Fax]                VARCHAR (255) NULL,
    [Other Phone]              VARCHAR (255) NULL,
    [Pager]                    VARCHAR (255) NULL,
    [Primary Phone]            VARCHAR (255) NULL,
    [Radio Phone]              VARCHAR (255) NULL,
    [TTY/TDD Phone]            VARCHAR (255) NULL,
    [Telex]                    VARCHAR (255) NULL,
    [Account]                  VARCHAR (255) NULL,
    [Anniversary]              VARCHAR (255) NULL,
    [Assistant's Name]         VARCHAR (255) NULL,
    [Billing Information]      VARCHAR (255) NULL,
    [Birthday]                 VARCHAR (255) NULL,
    [Categories]               VARCHAR (255) NULL,
    [Children]                 VARCHAR (255) NULL,
    [Directory Server]         VARCHAR (255) NULL,
    [E-mail Address]           VARCHAR (255) NULL,
    [E-mail Type]              VARCHAR (255) NULL,
    [E-mail Display Name]      VARCHAR (255) NULL,
    [E-mail 2 Address]         VARCHAR (255) NULL,
    [E-mail 2 Type]            VARCHAR (255) NULL,
    [E-mail 2 Display Name]    VARCHAR (255) NULL,
    [E-mail 3 Address]         VARCHAR (255) NULL,
    [E-mail 3 Type]            VARCHAR (255) NULL,
    [E-mail 3 Display Name]    VARCHAR (255) NULL,
    [Gender]                   VARCHAR (255) NULL,
    [Government ID Number]     VARCHAR (255) NULL,
    [Hobby]                    VARCHAR (255) NULL,
    [Initials]                 VARCHAR (255) NULL,
    [Internet Free Busy]       VARCHAR (255) NULL,
    [Keywords]                 VARCHAR (255) NULL,
    [Language]                 VARCHAR (255) NULL,
    [Location]                 VARCHAR (255) NULL,
    [Manager's Name]           VARCHAR (255) NULL,
    [Mileage]                  VARCHAR (255) NULL,
    [Notes]                    VARCHAR (255) NULL,
    [Office Location]          VARCHAR (255) NULL,
    [Organizational ID Number] VARCHAR (255) NULL,
    [PO Box]                   VARCHAR (255) NULL,
    [Priority]                 VARCHAR (255) NULL,
    [Private]                  VARCHAR (255) NULL,
    [Profession]               VARCHAR (255) NULL,
    [Referred By]              VARCHAR (255) NULL,
    [Sensitivity]              VARCHAR (255) NULL,
    [Spouse]                   VARCHAR (255) NULL,
    [User 1]                   VARCHAR (255) NULL,
    [User 2]                   VARCHAR (255) NULL,
    [User 3]                   VARCHAR (255) NULL,
    [User 4]                   VARCHAR (255) NULL,
    [Web Page]                 VARCHAR (255) NULL
);

