CREATE TABLE [dbo].[Hospital_region] (
    [ID]                   INT            NULL,
    [SFID]                 CHAR (18)      NULL,
    [Code]                 CHAR (20)      NULL,
    [SFDCName]             VARCHAR (255)  NULL,
    [HospitalName]         VARCHAR (100)  NULL,
    [hospitalNameShort]    VARCHAR (50)   NULL,
    [Site_Dir]             NCHAR (50)     NULL,
    [AssSite_Dir]          NCHAR (50)     NULL,
    [Reimb_Dir]            NCHAR (50)     NULL,
    [PA_liaison]           VARCHAR (50)   NULL,
    [CMO]                  NCHAR (10)     NULL,
    [EMS_dir]              NCHAR (10)     NULL,
    [NP_dir]               NCHAR (10)     NULL,
    [QI_DIR]               NCHAR (50)     NULL,
    [QI_authors]           NVARCHAR (100) NULL,
    [other_admin]          NVARCHAR (50)  NULL,
    [Region]               CHAR (5)       NULL,
    [Description]          NVARCHAR (800) NULL,
    [ContactInfo]          NVARCHAR (200) NULL,
    [division]             CHAR (10)      CONSTRAINT [DF_Hospital_region_division] DEFAULT (' ') NULL,
    [dept]                 CHAR (10)      CONSTRAINT [DF_Hospital_region_dept] DEFAULT (' ') NULL,
    [TCstruct]             VARCHAR (50)   NULL,
    [MDrate]               CHAR (10)      NULL,
    [SiteLocationName]     VARCHAR (100)  NULL,
    [Services]             VARCHAR (100)  NULL,
    [MARSHospitalName]     VARCHAR (100)  NULL,
    [PayrollHospitalName]  VARCHAR (100)  NULL,
    [SiteLineHospitalName] VARCHAR (100)  NULL,
    [EchoHospitalName]     VARCHAR (100)  NULL,
    [ts_start]             DATETIME       NULL,
    [ts_end]               DATETIME       NULL,
    [status]               VARCHAR (4)    NULL,
    [timezone]             VARCHAR (50)   NULL,
    [state]                VARCHAR (50)   NULL,
    [flag]                 INT            NULL
);

