CREATE TABLE [dbo].[Hospital_region_4DR] (
    [ID]                   INT            NOT NULL,
    [SFID]                 VARCHAR (18)   NULL,
    [Code]                 CHAR (20)      NOT NULL,
    [SFDCName]             VARCHAR (255)  NULL,
    [HospitalName]         VARCHAR (100)  NOT NULL,
    [Site_Dir]             NCHAR (50)     NULL,
    [AssSite_Dir]          NCHAR (50)     NULL,
    [Reimb_Dir]            NCHAR (50)     NULL,
    [CMO]                  NCHAR (10)     NULL,
    [EMS_dir]              NCHAR (10)     NULL,
    [NP_dir]               NCHAR (10)     NULL,
    [QI_DIR]               NCHAR (50)     NULL,
    [QI_authors]           NVARCHAR (100) NULL,
    [other_admin]          NVARCHAR (50)  NULL,
    [Region]               CHAR (5)       NULL,
    [Description]          NVARCHAR (800) NULL,
    [ContactInfo]          NVARCHAR (200) NULL,
    [division]             CHAR (10)      NOT NULL,
    [dept]                 CHAR (10)      NOT NULL,
    [TCstruct]             VARCHAR (50)   NULL,
    [MDrate]               CHAR (10)      NULL,
    [SiteLocationName]     VARCHAR (100)  NULL,
    [MARSHospitalName]     VARCHAR (100)  NULL,
    [PayrollHospitalName]  VARCHAR (100)  NULL,
    [SiteLineHospitalName] VARCHAR (100)  NULL,
    [EchoHospitalName]     VARCHAR (100)  NULL,
    [status]               CHAR (10)      NULL,
    [state]                CHAR (10)      NULL,
    [time_zone]            CHAR (10)      NULL,
    [CreDate]              DATETIME       CONSTRAINT [DF_Hospital_region_4DR_CreDate] DEFAULT (getdate()) NULL
);

