CREATE TABLE [dbo].[JOB_REC_Action_4DR] (
    [actionID]          INT            NOT NULL,
    [parentID]          INT            NULL,
    [candidateID]       INT            NOT NULL,
    [recruiterID]       INT            NOT NULL,
    [actionType]        VARCHAR (100)  NULL,
    [actionDescription] VARCHAR (500)  NULL,
    [postedDate]        DATETIME       NOT NULL,
    [attachmentList]    VARCHAR (1000) NULL,
    [notes]             VARCHAR (5000) NULL,
    [eventCode]         VARCHAR (500)  NULL,
    [forSite]           VARCHAR (500)  NULL,
    [associatedDate]    DATETIME       NULL,
    [associatedCost]    VARCHAR (500)  NULL,
    [location]          VARCHAR (500)  NULL,
    [reminderType]      VARCHAR (500)  NULL,
    [reminderNotes]     VARCHAR (5000) NULL,
    [reminderDate]      DATETIME       NULL,
    [autoEmailDate]     DATETIME       NULL,
    [emailTemplateCode] VARCHAR (5000) NULL,
    [flagPriority]      INT            NULL,
    [flagDueOn]         DATETIME       NULL,
    [flagNotifyOn]      DATETIME       NULL,
    [UDF1]              VARCHAR (500)  NULL,
    [UDF2]              VARCHAR (500)  NULL,
    [UDF3]              VARCHAR (500)  NULL,
    [UDF4]              VARCHAR (500)  NULL,
    [CreDate]           DATETIME       CONSTRAINT [DF_JOB_REC_Action_4DR_CreDate] DEFAULT (getdate()) NULL
);

