CREATE TABLE [dbo].[job_inquiry_copy_4DR] (
    [id]            BIGINT          NOT NULL,
    [firstname]     VARCHAR (100)   NULL,
    [lastname]      VARCHAR (100)   NULL,
    [middlename]    VARCHAR (100)   NULL,
    [title]         VARCHAR (100)   NULL,
    [address]       VARCHAR (200)   NULL,
    [city]          VARCHAR (100)   NULL,
    [state]         VARCHAR (100)   NULL,
    [zipcode]       VARCHAR (100)   NULL,
    [homephone]     VARCHAR (100)   NULL,
    [cellphone]     VARCHAR (100)   NULL,
    [email]         VARCHAR (100)   NULL,
    [jobpswrd]      VARCHAR (100)   NULL,
    [medspec]       VARCHAR (100)   NULL,
    [yrsexp]        VARCHAR (100)   NULL,
    [brdcert]       VARCHAR (100)   NULL,
    [brdelig]       VARCHAR (100)   NULL,
    [medschl]       VARCHAR (100)   NULL,
    [medschlcomp]   VARCHAR (100)   NULL,
    [residency]     VARCHAR (100)   NULL,
    [resicomp]      VARCHAR (100)   NULL,
    [panpprog]      VARCHAR (100)   NULL,
    [panpprogcomp]  VARCHAR (100)   NULL,
    [dateavail]     VARCHAR (100)   NULL,
    [alreadyPos]    VARCHAR (100)   NULL,
    [FTPos]         VARCHAR (100)   NULL,
    [PTPos]         VARCHAR (100)   NULL,
    [MDPos]         VARCHAR (100)   NULL,
    [other_states]  VARCHAR (1000)  NULL,
    [comment]       VARCHAR (1000)  NULL,
    [FileList]      NVARCHAR (1000) NULL,
    [tmstmp]        DATETIME        NULL,
    [recruiterIDs]  VARCHAR (100)   NULL,
    [status]        VARCHAR (100)   NOT NULL,
    [source]        VARCHAR (500)   NULL,
    [medspec_other] VARCHAR (500)   NULL,
    [UDF1]          VARCHAR (500)   NULL,
    [UDF2]          VARCHAR (500)   NULL,
    [UDF3]          VARCHAR (500)   NULL,
    [CreDate]       DATETIME        CONSTRAINT [DF_job_inquiry_copy_4DR_CreDate] DEFAULT (getdate()) NULL
);

