CREATE TABLE [dbo].[LawsonNewHireEntry_Scribe3] (
    [ProviderMasterID]     NVARCHAR (255) NULL,
    [LastName]             NVARCHAR (255) NULL,
    [FirstName]            NVARCHAR (255) NULL,
    [MiddleInit]           NVARCHAR (255) NULL,
    [MiddleNameOrInitial]  NVARCHAR (255) NULL,
    [Title]                NVARCHAR (255) NULL,
    [PreferredName]        NVARCHAR (255) NULL,
    [PhoneNbr1]            NVARCHAR (255) NULL,
    [Email]                NVARCHAR (255) NULL,
    [Address1]             NVARCHAR (255) NULL,
    [Address2]             NVARCHAR (255) NULL,
    [City1]                NVARCHAR (255) NULL,
    [State1]               NVARCHAR (255) NULL,
    [ZipCode1]             FLOAT (53)     NULL,
    [Country]              NVARCHAR (255) NULL,
    [Source]               NVARCHAR (255) NULL,
    [Ethnicity]            NVARCHAR (255) NULL,
    [Gender]               NVARCHAR (255) NULL,
    [MaritalStatus]        NVARCHAR (255) NULL,
    [PayRate]              FLOAT (53)     NULL,
    [AutoDeposit]          NVARCHAR (255) NULL,
    [DateOfBirth]          DATETIME       NULL,
    [SSNFormatted]         NVARCHAR (255) NULL,
    [ProcessLevel]         FLOAT (53)     NULL,
    [DateOfHire]           DATETIME       NULL,
    [BenefitDate1]         DATETIME       NULL,
    [BenefitDate2]         DATETIME       NULL,
    [BenefitSalary1]       FLOAT (53)     NULL,
    [BenefitSalary2]       FLOAT (53)     NULL,
    [Pos]                  NVARCHAR (255) NULL,
    [PosPL]                FLOAT (53)     NULL,
    [Status]               NVARCHAR (255) NULL,
    [FTE]                  FLOAT (53)     NULL,
    [Expense Account]      FLOAT (53)     NULL,
    [Schedule]             NVARCHAR (255) NULL,
    [Salary Class]         NVARCHAR (255) NULL,
    [Exempt From Overtime] NVARCHAR (255) NULL,
    [Pay Frequency]        FLOAT (53)     NULL,
    [HEP B]                NVARCHAR (255) NULL,
    [FirstWorkDate]        DATETIME       NULL,
    [EffectiveDate]        DATETIME       NULL,
    [Benefits]             NVARCHAR (255) NULL,
    [AbMgmnt]              NVARCHAR (255) NULL,
    [ReqDeds]              NVARCHAR (255) NULL,
    [PreAssignEmpNo]       NVARCHAR (255) NULL,
    [ApplicantNo]          NVARCHAR (255) NULL,
    [AutoTimeRcd]          NVARCHAR (255) NULL,
    [_f296:_HK]            VARCHAR (200)  NULL
);

