CREATE TABLE [dbo].[LawsonNewHireEntry_Scribe2] (
    [ProviderMasterID]     NVARCHAR (255) NULL,
    [LastName]             NVARCHAR (255) NULL,
    [FirstName]            NVARCHAR (255) NULL,
    [MiddleInit]           NVARCHAR (255) NULL,
    [MiddleNameOrInitial]  NVARCHAR (255) NULL,
    [Title]                NVARCHAR (255) NULL,
    [PreferredName]        NVARCHAR (255) NULL,
    [PhoneNbr1]            NVARCHAR (255) NULL,
    [Email]                NVARCHAR (255) NULL,
    [Address1]             NVARCHAR (255) NULL,
    [City1]                NVARCHAR (255) NULL,
    [State1]               NVARCHAR (255) NULL,
    [ZipCode1]             NVARCHAR (255) NULL,
    [Country]              NVARCHAR (255) NULL,
    [Source]               NVARCHAR (255) NULL,
    [Ethnicity]            NVARCHAR (255) NULL,
    [Gender]               NVARCHAR (255) NULL,
    [MaritalStatus]        NVARCHAR (255) NULL,
    [PayRate]              NVARCHAR (255) NULL,
    [AutoDeposit]          NVARCHAR (255) NULL,
    [DateOfBirth]          NVARCHAR (255) NULL,
    [SSNFormatted]         NVARCHAR (255) NULL,
    [ProcessLevel]         NVARCHAR (255) NULL,
    [DateOfHire]           NVARCHAR (255) NULL,
    [BenefitDate1]         NVARCHAR (255) NULL,
    [BenefitDate2]         NVARCHAR (255) NULL,
    [BenefitSalary1]       NVARCHAR (255) NULL,
    [BenefitSalary2]       NVARCHAR (255) NULL,
    [Pos]                  NVARCHAR (255) NULL,
    [PosPL]                NVARCHAR (255) NULL,
    [Status]               NVARCHAR (255) NULL,
    [FTE]                  NVARCHAR (255) NULL,
    [Expense Account]      NVARCHAR (255) NULL,
    [Schedule]             NVARCHAR (255) NULL,
    [Salary Class]         NVARCHAR (255) NULL,
    [Exempt From Overtime] NVARCHAR (255) NULL,
    [Pay Frequency]        NVARCHAR (255) NULL,
    [HEP B]                NVARCHAR (255) NULL,
    [FirstWorkDate]        NVARCHAR (255) NULL,
    [EffectiveDate]        NVARCHAR (255) NULL,
    [Benefits]             NVARCHAR (255) NULL,
    [AbMgmnt]              NVARCHAR (255) NULL,
    [ReqDeds]              NVARCHAR (255) NULL,
    [PreAssignEmpNo]       NVARCHAR (255) NULL,
    [ApplicantNo]          NVARCHAR (255) NULL,
    [AutoTimeRcd]          NVARCHAR (255) NULL
);

