CREATE TABLE [dbo].[LawsonTest] (
    [ProviderMasterID]    INT           NOT NULL,
    [LastName]            VARCHAR (100) NULL,
    [FirstName]           VARCHAR (100) NULL,
    [MiddleInit]          VARCHAR (10)  NULL,
    [MiddleNameOrInitial] VARCHAR (100) NULL,
    [Title]               CHAR (50)     NULL,
    [PreferredName]       VARCHAR (100) NULL,
    [PhoneNbr1]           VARCHAR (50)  NULL,
    [Email]               VARCHAR (100) NULL,
    [Address1]            VARCHAR (100) NULL,
    [City1]               VARCHAR (50)  NULL,
    [State1]              VARCHAR (50)  NULL,
    [ZipCode1]            VARCHAR (50)  NULL,
    [Country]             VARCHAR (2)   NULL,
    [Ethnicity]           CHAR (50)     NULL,
    [Gender]              VARCHAR (10)  NULL,
    [MaritalStatus]       VARCHAR (50)  NULL,
    [PayRate]             VARCHAR (5)   NULL,
    [AutoDeposit]         CHAR (10)     NULL,
    [DateOfBirth]         DATETIME      NULL,
    [SSNFormatted]        VARCHAR (11)  NULL,
    [ProcessLevel]        FLOAT (53)    NULL,
    [DateOfHire]          VARCHAR (50)  NULL,
    [BenefitDate1]        VARCHAR (50)  NULL,
    [BenefitDate2]        VARCHAR (50)  NULL,
    [BenefitSalary1]      VARCHAR (6)   NULL,
    [BenefitSalary2]      VARCHAR (6)   NULL,
    [Pos]                 VARCHAR (10)  NULL,
    [PosPL]               VARCHAR (50)  NULL,
    [Status]              VARCHAR (50)  NULL,
    [FTE]                 CHAR (10)     NULL,
    [FirstWorkDate]       VARCHAR (50)  NULL,
    [EffectiveDate]       VARCHAR (50)  NULL,
    [Benefits]            CHAR (10)     NULL,
    [AbMgmnt]             CHAR (10)     NULL,
    [ReqDeds]             CHAR (10)     NULL,
    [PreAssignEmpNo]      CHAR (10)     NULL,
    [ApplicantNo]         CHAR (10)     NULL,
    [AutoTimeRcd]         CHAR (5)      NULL,
    [FLD_NBR_01]          SMALLINT      NULL,
    [FLD_NBR_02]          SMALLINT      NULL,
    [FLD_NBR_03]          SMALLINT      NULL,
    [FLD_NBR_04]          SMALLINT      NULL,
    [FLD_NBR_05]          SMALLINT      NULL,
    [FLD_NBR_06]          SMALLINT      NULL,
    [FLD_NBR_07]          SMALLINT      NULL,
    [FLD_NBR_08]          SMALLINT      NULL,
    [FLD_NBR_09]          SMALLINT      NULL,
    [FLD_NBR_10]          SMALLINT      NULL,
    [FLD_NBR_11]          SMALLINT      NULL,
    [FLD_NBR_12]          SMALLINT      NULL,
    [FLD_NBR_13]          SMALLINT      NULL,
    [FLD_NBR_14]          SMALLINT      NULL,
    [FLD_NBR_15]          SMALLINT      NULL,
    [FLD_NBR_16]          SMALLINT      NULL,
    [FLD_NBR_17]          SMALLINT      NULL,
    [FLD_NBR_18]          SMALLINT      NULL,
    [FLD_NBR_19]          SMALLINT      NULL,
    [FLD_NBR_20]          SMALLINT      NULL,
    [FLD_NBR_21]          SMALLINT      NULL,
    [FLD_NBR_22]          SMALLINT      NULL,
    [FLD_NBR_23]          SMALLINT      NULL,
    [FLD_NBR_24]          SMALLINT      NULL,
    [FLD_NBR_25]          SMALLINT      NULL,
    [FLD_NBR_26]          SMALLINT      NULL,
    [FLD_NBR_27]          SMALLINT      NULL,
    [FLD_NBR_28]          SMALLINT      NULL,
    [FLD_NBR_29]          SMALLINT      NULL,
    [FLD_NBR_30]          SMALLINT      NULL,
    [FLD_NBR_31]          SMALLINT      NULL,
    [FLD_NBR_32]          SMALLINT      NULL,
    [FLD_NBR_33]          SMALLINT      NULL,
    [FLD_NBR_34]          SMALLINT      NULL,
    [FLD_NBR_35]          SMALLINT      NULL,
    [FLD_NBR_36]          SMALLINT      NULL,
    [_f296:_HK]           VARCHAR (200) NULL
);

