CREATE TABLE [dbo].[LMSJobs] (
    [JOB_CODE]   VARCHAR (100) NULL,
    [JOB_NAME]   VARCHAR (255) NULL,
    [JOB_NUMBER] INT           IDENTITY (1, 1) NOT NULL,
    [JOB_DOMAIN] VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([JOB_NUMBER] ASC)
);

