CREATE TABLE [dbo].[MANonExemptTimecard] (
    [id]            INT            NOT NULL,
    [LastName]      VARCHAR (100)  NULL,
    [FirstName]     VARCHAR (100)  NULL,
    [TCID]          CHAR (9)       NULL,
    [TCDate]        DATETIME       NOT NULL,
    [Tin_A]         CHAR (5)       NOT NULL,
    [Tout_A]        CHAR (5)       NOT NULL,
    [Tin_P]         CHAR (5)       NOT NULL,
    [Tout_P]        CHAR (5)       NOT NULL,
    [min_wkd_A]     CHAR (6)       NOT NULL,
    [min_wkd_P]     CHAR (6)       NOT NULL,
    [HoursWorked]   CHAR (6)       NOT NULL,
    [SickHours]     CHAR (6)       NOT NULL,
    [VacationHours] CHAR (6)       NOT NULL,
    [HolidayHours]  CHAR (6)       NOT NULL,
    [OtherHours]    CHAR (6)       NOT NULL,
    [MakeupHours]   CHAR (6)       NOT NULL,
    [TotalHours]    CHAR (6)       NOT NULL,
    [STTHours]      CHAR (6)       NOT NULL,
    [OTHours]       CHAR (6)       NOT NULL,
    [DTHours]       CHAR (6)       NOT NULL,
    [Type]          CHAR (10)      NULL,
    [isLocked]      CHAR (1)       NOT NULL,
    [isApproved]    CHAR (1)       NOT NULL,
    [TimeStmp]      DATETIME       NOT NULL,
    [AdminName]     VARCHAR (50)   NOT NULL,
    [Comment]       VARCHAR (1000) NOT NULL,
    [flag]          CHAR (1)       NOT NULL
);

