CREATE TABLE [dbo].[ProviderMasterStaging] (
    [SFID]               CHAR (18)     NOT NULL,
    [LastName]           VARCHAR (50)  NOT NULL,
    [FirstName]          VARCHAR (50)  NULL,
    [PreferredName]      VARCHAR (50)  NULL,
    [MiddleName]         VARCHAR (50)  NULL,
    [Title]              VARCHAR (100) NULL,
    [Email]              VARCHAR (100) NULL,
    [Gender]             CHAR (10)     NULL,
    [SSNFormatted]       VARCHAR (11)  NULL,
    [SSNUnformatted]     VARCHAR (10)  NULL,
    [OtherLastName]      VARCHAR (500) NULL,
    [OtherFirstName]     VARCHAR (50)  NULL,
    [OtherMiddleName]    VARCHAR (50)  NULL,
    [BatchNbr]           INT           NOT NULL,
    [MaritalStatus]      VARCHAR (50)  NULL,
    [MaritalCode]        VARCHAR (1)   NULL,
    [SpouseName]         VARCHAR (100) NULL,
    [SiteName]           VARCHAR (100) NULL,
    [MobilePhone]        VARCHAR (50)  NULL,
    [DateOfBirth]        DATETIME      NULL,
    [TaxIDIncorp]        VARCHAR (100) NULL,
    [NationalID]         VARCHAR (30)  NULL,
    [WebID]              INT           NULL,
    [ProviderMasterID]   INT           NULL,
    [MultiClientFlag]    CHAR (1)      NULL,
    [CompleteRecordFlag] CHAR (1)      NULL,
    [ActiveFlag]         CHAR (1)      NULL
);

