CREATE TABLE [dbo].[ReportProviderWeeklyChanges] (
    [StaffGroup]         VARCHAR (10)  NOT NULL,
    [CreDate]            DATETIME      NULL,
    [FirstName]          VARCHAR (50)  NULL,
    [PreferredName]      VARCHAR (51)  NULL,
    [LastName]           VARCHAR (50)  NULL,
    [PriorName]          VARCHAR (101) NULL,
    [MaritalStatus]      VARCHAR (50)  NULL,
    [PriorMaritalStatus] VARCHAR (50)  NULL,
    [Title]              VARCHAR (100) NULL,
    [Email]              VARCHAR (100) NULL,
    [Cell]               VARCHAR (50)  NULL,
    [Pager]              VARCHAR (50)  NULL,
    [Address1]           VARCHAR (100) NULL,
    [CityStateZip1]      VARCHAR (153) NULL,
    [PhoneNbr1]          VARCHAR (50)  NULL,
    [FaxNbr1]            VARCHAR (50)  NULL,
    [Addresstype2]       VARCHAR (20)  NULL,
    [PhoneNbr2]          VARCHAR (50)  NULL,
    [FaxNbr2]            VARCHAR (50)  NULL,
    [AddSites1]          VARCHAR (100) NULL,
    [AddSitesDate1]      VARCHAR (50)  NULL,
    [AddSites2]          VARCHAR (100) NULL,
    [AddSitesDate2]      VARCHAR (50)  NULL,
    [AddSites3]          VARCHAR (100) NULL,
    [AddSitesDate3]      VARCHAR (50)  NULL,
    [AddSites4]          VARCHAR (100) NULL,
    [AddSitesDate4]      VARCHAR (50)  NULL,
    [DropSites1]         VARCHAR (100) NULL,
    [DropSitesDate1]     VARCHAR (50)  NULL,
    [DropSites2]         VARCHAR (100) NULL,
    [DropSitesDate2]     VARCHAR (50)  NULL,
    [DropSites3]         VARCHAR (100) NULL,
    [DropSitesDate3]     VARCHAR (50)  NULL,
    [DropSites4]         VARCHAR (100) NULL,
    [DropSitesDate4]     VARCHAR (50)  NULL,
    [Separated]          VARCHAR (9)   NULL,
    [DateSeparated]      VARCHAR (50)  NULL,
    [Providermasterid]   INT           NULL,
    [Author]             VARCHAR (60)  NULL,
    [ArchiveCreDate]     DATETIME      NULL
);

