CREATE TABLE [dbo].[Siteline_TblCtr] (
    [CtrID]                        INT           NOT NULL,
    [CtrSite_CmpID]                INT           NULL,
    [CtrSys_CmpID]                 INT           NULL,
    [CtrTranscript_CmpID]          INT           NULL,
    [CtrBillAgt_CmpID]             INT           NULL,
    [CtrPhyGrp_CmpID]              INT           NULL,
    [CtrMlp_CmpID]                 INT           NULL,
    [CtrBillCmpIDNum]              VARCHAR (20)  NULL,
    [CtrMedDir_CntID]              INT           NULL,
    [CtrCamAssigned_CntID]         INT           NULL,
    [Ctr_CtrTypID]                 VARCHAR (10)  NULL,
    [Ctr_RgnID]                    INT           NULL,
    [Ctr_MlpRgnID]                 VARCHAR (30)  NULL,
    [CtrKey]                       VARCHAR (100) NULL,
    [CtrHPID]                      VARCHAR (4)   NULL,
    [CtrPlatinumID]                INT           NULL,
    [CtrDateStart]                 DATETIME      NULL,
    [CtrDateEffect]                DATETIME      NULL,
    [CtrDateRenew]                 DATETIME      NULL,
    [CtrDateEnd]                   DATETIME      NULL,
    [CtrYrQty]                     INT           NULL,
    [CtrSysCtrYN]                  BIT           NULL,
    [CtrAutoRenewYN]               BIT           NULL,
    [CtrEndNoCseYN]                BIT           NULL,
    [CtrNoCseDayQty]               INT           NULL,
    [CtrEndCseYN]                  BIT           NULL,
    [CtrCseDayQty]                 INT           NULL,
    [CtrRemDayQty]                 INT           NULL,
    [CtrPriorAdjCollWIPAmtDefault] MONEY         NOT NULL,
    [CtrPriorCollectARDefault]     MONEY         NOT NULL,
    [CtrPriorCollFeeAmtDefault]    MONEY         NOT NULL,
    [CtrPriorLoanBalDefault]       MONEY         NOT NULL,
    [CtrStipAmt]                   MONEY         NULL,
    [CtrStipDesc]                  VARCHAR (50)  NULL,
    [CtrOtherPayAmt]               MONEY         NULL,
    [CtrOtherPayDesc]              VARCHAR (50)  NULL,
    [CtrEmpPhysPaid]               INT           NULL,
    [CtrWrkCompPaidYN]             BIT           NULL,
    [CtrCompeteClauseYN]           BIT           NULL,
    [CtrBillRecDayQty]             INT           NULL,
    [CtrBillAgtDateStart]          DATETIME      NULL,
    [CtrMlpDateEffect]             DATETIME      NULL,
    [CtrTrmCtrYN]                  BIT           NULL,
    [CtrPrmBseYN]                  BIT           NULL,
    [CtrRsdAff]                    VARCHAR (50)  NULL,
    [CtrElecLogYN]                 BIT           NULL,
    [CtrNrsInitProtoYN]            BIT           NULL,
    [CtrTriageProtoYN]             BIT           NULL,
    [CtrClnPthwyYN]                BIT           NULL,
    [CtrPrcGdeYN]                  BIT           NULL,
    [CtrComputeAfcYN]              BIT           NULL,
    [CtrElecMedRcdYN]              BIT           NULL,
    [CtrObsvUnitYN]                BIT           NULL,
    [CtrChstPnYN]                  BIT           NULL,
    [CtrFastTrkYn]                 BIT           NULL,
    [CtrOccMedYN]                  BIT           NULL,
    [CtrHspYN]                     BIT           NULL,
    [CtrSameStoreYN]               BIT           NULL,
    [CtrGoodMethodYN]              BIT           NULL,
    [CtrChestPainYN]               BIT           NULL,
    [CtrElectronicTrackYN]         BIT           NULL,
    [CtrPainMgmt]                  VARCHAR (50)  NULL,
    [CtrAllowNursesYN]             BIT           NULL,
    [CtrPhySpecificDataYN]         BIT           NULL,
    [CtrComplaintMgtPrgYN]         BIT           NULL,
    [CtrSatisfactionTool]          VARCHAR (50)  NULL,
    [CtrSatisfactionTeamYN]        BIT           NULL,
    [CtrEDVolume]                  INT           NULL,
    [CtrAdmissionPct]              FLOAT (53)    NULL,
    [CtrTransferPct]               FLOAT (53)    NULL,
    [CtrStatPITpct]                FLOAT (53)    NULL,
    [CtrStatRDpct]                 FLOAT (53)    NULL,
    [CtrStatMDpct]                 FLOAT (53)    NULL,
    [CtrStatContribpct]            FLOAT (53)    NULL,
    [CtrBseHour]                   FLOAT (53)    NULL,
    [CtrBillRate]                  MONEY         NULL,
    [CtrIncExpComment]             TEXT          NULL,
    [CtrSiteOvrHdpct]              FLOAT (53)    NULL,
    [CtrIntRate]                   FLOAT (53)    NULL,
    [CtrMlpFlatFee]                MONEY         NOT NULL,
    [CtrMplSecondRate]             FLOAT (53)    NOT NULL,
    [CtrLclPct]                    FLOAT (53)    NOT NULL,
    [CtrLclFixedAmt]               MONEY         NOT NULL,
    [CtrMDIncentivePct]            FLOAT (53)    NOT NULL,
    [CtrRDIncentivePct]            FLOAT (53)    NOT NULL,
    [CtrSurplusReservePct]         FLOAT (53)    NOT NULL,
    [zCtrMPRate]                   FLOAT (53)    NULL,
    [CtrDateFeeInc]                DATETIME      NULL,
    [CtrPctInc]                    FLOAT (53)    NULL,
    [CtrNightPct]                  FLOAT (53)    NULL,
    [CtrDiffRate]                  FLOAT (53)    NULL,
    [CtrDiffAmt]                   MONEY         NULL,
    [CtrDayRate]                   MONEY         NULL,
    [CtrNightRate]                 MONEY         NULL,
    [CtrBedQty]                    INT           NULL,
    [CtrFastTrackBedQty]           INT           NULL,
    [CtrOtherBedQty]               INT           NULL,
    [CtrCriticalCareBedQty]        INT           NULL,
    [CtrObservationBedQty]         INT           NULL,
    [CtrEmail]                     VARCHAR (50)  NULL,
    [CtrDateCreate]                DATETIME      NULL,
    [CtrDateEdit]                  DATETIME      NULL,
    [CtrInactiveYn]                BIT           NULL,
    [CtrTraumaDesignation]         VARCHAR (50)  NULL,
    [CtrFlagYn]                    BIT           NULL,
    [CtrComment]                   TEXT          NULL,
    [CtrRequireMailYN]             BIT           NULL,
    [CtrCEPSurchargePct]           FLOAT (53)    NOT NULL,
    [CtrMngCarBatchYN]             BIT           NOT NULL,
    [CtrMisc1YN]                   BIT           NULL,
    [CtrMisc2YN]                   BIT           NULL,
    [CtrMisc3YN]                   BIT           NULL,
    [CtrMisc4YN]                   BIT           NULL,
    [CtrMisc5YN]                   BIT           NULL,
    [CtrPASupportCostPct]          FLOAT (53)    NULL,
    [CtrTin]                       INT           NULL,
    [CtrDivision]                  VARCHAR (100) NULL
);

