CREATE TABLE [dbo].[Siteline_tblCnt] (
    [CntKey]             VARCHAR (100) NULL,
    [CntID]              INT           NOT NULL,
    [Cnt_CmpID]          INT           NULL,
    [Cnt_HonID]          VARCHAR (10)  NULL,
    [CntLbrFlxIDEb]      INT           NULL,
    [CntTitle]           VARCHAR (100) NULL,
    [CntNameFirst]       VARCHAR (30)  NULL,
    [CntNameMiddle]      VARCHAR (20)  NULL,
    [CntNameLast]        VARCHAR (30)  NULL,
    [CntNameSuffix]      VARCHAR (10)  NULL,
    [CntAddress1]        VARCHAR (50)  NULL,
    [CntAddress2]        VARCHAR (50)  NULL,
    [CntCity]            VARCHAR (30)  NULL,
    [CntState]           CHAR (2)      NULL,
    [CntZip]             VARCHAR (10)  NULL,
    [CntCountry]         VARCHAR (25)  NULL,
    [CntEmail]           VARCHAR (100) NULL,
    [CntPhonePref]       VARCHAR (20)  NULL,
    [CntPhonePrefSelect] SMALLINT      NULL,
    [CntPhoneHome]       VARCHAR (20)  NULL,
    [CntPhoneWork]       VARCHAR (20)  NULL,
    [CntPhoneExt]        VARCHAR (10)  NULL,
    [CntPhoneCell]       VARCHAR (20)  NULL,
    [CntPhoneAlt]        VARCHAR (20)  NULL,
    [CntPager]           VARCHAR (20)  NULL,
    [CntFaxHome]         VARCHAR (20)  NULL,
    [CntFaxWork]         VARCHAR (20)  NULL,
    [CntPhoneVoicemail]  VARCHAR (20)  NULL,
    [CntCALicNo]         VARCHAR (50)  NULL,
    [CntDocNo]           VARCHAR (50)  NULL,
    [CntSSN]             INT           NULL,
    [CntDOB]             SMALLDATETIME NULL,
    [CntDateCreate]      SMALLDATETIME NULL,
    [CntDateEdit]        SMALLDATETIME NULL,
    [CntDateInactive]    SMALLDATETIME NULL,
    [CntInactiveYN]      BIT           NULL,
    [CntFlagYN]          BIT           NULL,
    [CntComment]         TEXT          NULL,
    [CntDocYN]           BIT           NOT NULL,
    [CntPAYN]            BIT           NOT NULL,
    [CntCAMYN]           BIT           NOT NULL,
    [CntRegDirYN]        BIT           NOT NULL,
    [CntRegAssYN]        BIT           NOT NULL,
    [CntRegAssDirYN]     BIT           NOT NULL,
    [CntMedDirYN]        BIT           NOT NULL,
    [CntNurseMgrYN]      BIT           NOT NULL,
    [CntQIDirYN]         BIT           NOT NULL,
    [CntAdminYN]         BIT           NOT NULL,
    [CntDirEd]           BIT           NOT NULL,
    [CntMAMarketingYN]   BIT           NOT NULL,
    [CntLoginName]       VARCHAR (50)  NULL,
    [CntCorpName]        VARCHAR (100) NULL,
    [CntCorpTaxID]       INT           NULL,
    [CntCorpLbrFlxIDEb]  INT           NULL,
    [zMCID]              INT           NULL,
    [zCntSSN]            VARCHAR (11)  NULL,
    [CntLawsonNumber]    VARCHAR (15)  NULL
);

