CREATE TABLE [dbo].[VoterList] (
    [last]     NVARCHAR (255) NULL,
    [first]    NVARCHAR (255) NULL,
    [title]    NVARCHAR (255) NULL,
    [doh]      DATETIME       NULL,
    [level]    NVARCHAR (255) NULL,
    [last adv] DATETIME       NULL,
    [mpid]     FLOAT (53)     NULL,
    [lawson]   FLOAT (53)     NULL,
    [ssn]      NVARCHAR (255) NULL,
    [site1]    NVARCHAR (255) NULL,
    [site 2]   NVARCHAR (255) NULL,
    [site 3]   NVARCHAR (255) NULL,
    [Jun-11]   FLOAT (53)     NULL,
    [Jul-11]   FLOAT (53)     NULL,
    [Aug-11]   FLOAT (53)     NULL,
    [Sep-11]   FLOAT (53)     NULL,
    [Oct-11]   FLOAT (53)     NULL,
    [Nov-11]   FLOAT (53)     NULL,
    [Dec-11]   FLOAT (53)     NULL,
    [Jan-12]   FLOAT (53)     NULL,
    [Feb-12]   FLOAT (53)     NULL,
    [Mar-12]   FLOAT (53)     NULL,
    [Apr-12]   FLOAT (53)     NULL,
    [May-12]   FLOAT (53)     NULL,
    [Jun-12]   FLOAT (53)     NULL,
    [NOTES]    NVARCHAR (255) NULL,
    [email]    NVARCHAR (255) NULL,
    [address]  NVARCHAR (255) NULL,
    [city]     NVARCHAR (255) NULL,
    [state]    NVARCHAR (255) NULL,
    [zip]      FLOAT (53)     NULL,
    [STATE1]   NVARCHAR (255) NULL
);

