CREATE TABLE [dbo].[WebTimeCardMidLevel_Test] (
    [flag]                   CHAR (1)        NULL,
    [Type]                   VARCHAR (6)     NOT NULL,
    [LawsonID]               INT             NULL,
    [WebCode]                CHAR (20)       NULL,
    [id]                     INT             NOT NULL,
    [TCID]                   CHAR (10)       NULL,
    [dat]                    SMALLDATETIME   NULL,
    [Month]                  CHAR (6)        NULL,
    [site]                   CHAR (10)       NULL,
    [SiteLocationName]       VARCHAR (100)   NULL,
    [LastName]               VARCHAR (50)    NULL,
    [FirstName]              VARCHAR (50)    NULL,
    [Initial]                VARCHAR (50)    NULL,
    [ProviderMasterID]       INT             NULL,
    [HoursDay]               DECIMAL (10, 4) NULL,
    [HoursNight]             DECIMAL (10, 4) NULL,
    [HoursWeekened]          DECIMAL (10, 4) NULL,
    [HoursBreak]             DECIMAL (10, 4) NULL,
    [HoursAdmin]             DECIMAL (10, 4) NULL,
    [HoursMeeting]           DECIMAL (10, 4) NULL,
    [HoursOther]             DECIMAL (10, 4) NULL,
    [HoursPTO]               DECIMAL (10, 4) NULL,
    [HoursSicks]             DECIMAL (10, 4) NULL,
    [Comments]               VARCHAR (200)   NULL,
    [HoursTotal]             DECIMAL (10, 4) NULL,
    [HoursStraight]          DECIMAL (10, 4) NULL,
    [HoursDayStraight]       DECIMAL (10, 4) NULL,
    [HoursNightStraight]     DECIMAL (10, 4) NULL,
    [HoursWeekendStraight]   DECIMAL (10, 4) NULL,
    [HoursOverTime]          DECIMAL (10, 4) NULL,
    [HoursDayOverTime]       DECIMAL (10, 4) NULL,
    [HoursNightOverTime]     DECIMAL (10, 4) NULL,
    [HoursWeekendOverTime]   DECIMAL (10, 4) NULL,
    [HoursDoubleTime]        DECIMAL (10, 4) NULL,
    [HoursDayDoubleTime]     DECIMAL (10, 4) NULL,
    [HoursNightDoubleTime]   DECIMAL (10, 4) NULL,
    [HoursWeekendDoubleTime] DECIMAL (10, 4) NULL,
    [TimeStart]              FLOAT (53)      NULL,
    [TimeEnd]                FLOAT (53)      NULL,
    [TotalHours]             FLOAT (53)      NULL,
    [PAFlag]                 VARCHAR (1)     NOT NULL,
    [ShiftFlag]              CHAR (1)        NULL,
    [IsFTK]                  CHAR (1)        NULL
);

