CREATE TABLE [dbo].[YTDEarningsStatementArchiveMD_AdminPay] (
    [CsuFlxID]                 INT             NULL,
    [CsuFlxIDeb]               INT             NULL,
    [CseFlxIDCsu]              INT             NULL,
    [CsdFlxIDCsu]              INT             NULL,
    [CstFlxIDCsu]              INT             NULL,
    [CsdFlxID]                 INT             NULL,
    [ProviderMasterID]         INT             NULL,
    [CheckDate]                DATETIME        NULL,
    [PeriodEnding]             DATETIME        NULL,
    [PayPeriod]                VARCHAR (10)    NULL,
    [CsuPSID]                  VARCHAR (10)    NULL,
    [CheckNo]                  VARCHAR (20)    NULL,
    [ClockNo]                  VARCHAR (6)     NULL,
    [LastName]                 VARCHAR (50)    NULL,
    [FirstName]                VARCHAR (30)    NULL,
    [MiddleName]               VARCHAR (30)    NULL,
    [FullName]                 VARCHAR (100)   NULL,
    [CheckAmt]                 DECIMAL (13, 2) NULL,
    [CurrentGrossPay]          DECIMAL (13, 2) NULL,
    [CurrentNetPay]            DECIMAL (13, 2) NULL,
    [YTDHours]                 DECIMAL (13, 2) NULL,
    [CurrentHours]             DECIMAL (10, 2) NULL,
    [SumOfYTDHours]            DECIMAL (13, 2) NULL,
    [SumOfCurrentHours]        DECIMAL (10, 2) NULL,
    [YTDNetPay]                DECIMAL (13, 2) NULL,
    [YTDGrossPay]              DECIMAL (13, 2) NULL,
    [LbrFlxIDeb]               INT             NULL,
    [LbrPayPeriod]             VARCHAR (10)    NULL,
    [PayCode]                  VARCHAR (5)     NULL,
    [PayCodeDescr]             VARCHAR (30)    NULL,
    [TotalHoursbyPayCode]      DECIMAL (10, 2) NULL,
    [TotalEarnings]            DECIMAL (10, 2) NULL,
    [HourlyRate]               DECIMAL (13, 4) NULL,
    [Dept]                     VARCHAR (6)     NULL,
    [DeptDescr]                VARCHAR (50)    NULL,
    [LbrPSID]                  VARCHAR (10)    NULL,
    [SumOfTotalHours]          DECIMAL (10, 2) NULL,
    [SumOfTotalEarnings]       DECIMAL (10, 2) NULL,
    [DeductDescr]              VARCHAR (13)    NULL,
    [CurrDeductAmt]            DECIMAL (13, 2) NULL,
    [YTDDeductAmt]             DECIMAL (13, 2) NULL,
    [BankAcctNo]               VARCHAR (17)    NULL,
    [ABARoutingNo]             INT             NULL,
    [EFTAmount]                DECIMAL (13, 2) NULL,
    [AccountType]              VARCHAR (1)     NULL,
    [ActivityIn]               VARCHAR (8)     NULL,
    [EarningsStatmentCategory] VARCHAR (50)    NULL,
    [CategoryFlag]             VARCHAR (5)     NULL,
    [CalendarYear]             VARCHAR (4)     NULL
);

