USE [master]
GO
/****** Object:  Database [MngCarDB]    Script Date: 09/08/2016 10:06:56 ******/
CREATE DATABASE [MngCarDB] ON  PRIMARY 
( NAME = N'MngCarDB_Data', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\MngCarDB.mdf' , SIZE = 37568KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'MngCarDB_Log', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\MngCarDB_log.ldf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [MngCarDB] SET COMPATIBILITY_LEVEL = 80
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MngCarDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [MngCarDB] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [MngCarDB] SET ANSI_NULLS OFF
GO
ALTER DATABASE [MngCarDB] SET ANSI_PADDING OFF
GO
ALTER DATABASE [MngCarDB] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [MngCarDB] SET ARITHABORT OFF
GO
ALTER DATABASE [MngCarDB] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [MngCarDB] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [MngCarDB] SET AUTO_SHRINK ON
GO
ALTER DATABASE [MngCarDB] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [MngCarDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [MngCarDB] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [MngCarDB] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [MngCarDB] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [MngCarDB] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [MngCarDB] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [MngCarDB] SET  DISABLE_BROKER
GO
ALTER DATABASE [MngCarDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [MngCarDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [MngCarDB] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [MngCarDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [MngCarDB] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [MngCarDB] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [MngCarDB] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [MngCarDB] SET  READ_WRITE
GO
ALTER DATABASE [MngCarDB] SET RECOVERY SIMPLE
GO
ALTER DATABASE [MngCarDB] SET  MULTI_USER
GO
ALTER DATABASE [MngCarDB] SET PAGE_VERIFY TORN_PAGE_DETECTION
GO
ALTER DATABASE [MngCarDB] SET DB_CHAINING OFF
GO
