USE [MngCarDB]
GO
/****** Object:  Table [dbo].[tlkpMcCtrTyp]    Script Date: 09/08/2016 10:07:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tlkpMcCtrTyp](
	[McCtrTypID] [int] IDENTITY(1,1) NOT NULL,
	[McCtrTypName] [varchar](50) NOT NULL,
	[McCtrTypComment] [text] NULL,
 CONSTRAINT [PK_tlkpMcCtrTyp] PRIMARY KEY NONCLUSTERED 
(
	[McCtrTypID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
