USE [MngCarDB]
GO
/****** Object:  Table [dbo].[tblErr]    Script Date: 09/08/2016 10:07:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblErr](
	[ErrID] [int] IDENTITY(1,1) NOT NULL,
	[ErrDescription] [nvarchar](50) NULL,
	[ErrTest] [char](10) NULL,
 CONSTRAINT [PK_tblErr] PRIMARY KEY CLUSTERED 
(
	[ErrID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
