USE [MngCarDB]
GO
/****** Object:  Table [dbo].[tblRgn]    Script Date: 09/08/2016 10:07:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblRgn](
	[RgnID] [int] IDENTITY(1,1) NOT NULL,
	[RgnDir_CntID] [int] NULL,
	[RgnDirAss_CntID] [int] NULL,
	[RgnAss_CntID] [int] NULL,
	[RgnName] [varchar](50) NULL,
	[RgnTimeStamp] [timestamp] NULL,
 CONSTRAINT [PK_tblRgn] PRIMARY KEY NONCLUSTERED 
(
	[RgnID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [RgnDir_CntID] ON [dbo].[tblRgn] 
(
	[RgnDir_CntID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RgnDirAss_CntID] ON [dbo].[tblRgn] 
(
	[RgnDirAss_CntID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblRgn]  WITH NOCHECK ADD  CONSTRAINT [FK_tblRgn_tblCnt] FOREIGN KEY([RgnDir_CntID])
REFERENCES [dbo].[tblCnt] ([CntID])
GO
ALTER TABLE [dbo].[tblRgn] CHECK CONSTRAINT [FK_tblRgn_tblCnt]
GO
ALTER TABLE [dbo].[tblRgn]  WITH NOCHECK ADD  CONSTRAINT [FK_tblRgn_tblCnt1] FOREIGN KEY([RgnDirAss_CntID])
REFERENCES [dbo].[tblCnt] ([CntID])
GO
ALTER TABLE [dbo].[tblRgn] CHECK CONSTRAINT [FK_tblRgn_tblCnt1]
GO
ALTER TABLE [dbo].[tblRgn]  WITH NOCHECK ADD  CONSTRAINT [FK_tblRgn_tblCnt2] FOREIGN KEY([RgnAss_CntID])
REFERENCES [dbo].[tblCnt] ([CntID])
GO
ALTER TABLE [dbo].[tblRgn] CHECK CONSTRAINT [FK_tblRgn_tblCnt2]
GO
