USE [MngCarDB]
GO
/****** Object:  Table [dbo].[ztblCtr_120821]    Script Date: 09/08/2016 10:07:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ztblCtr_120821](
	[CtrID] [int] NOT NULL,
	[CtrSite_CmpID] [int] NULL,
	[CtrBillCmpIDNum] [varchar](20) NULL,
	[Ctr_CtrTypID] [varchar](10) NULL,
	[Ctr_RgnID] [int] NULL,
	[Ctr_MlpRgnID] [varchar](30) NULL,
	[Ctr_BllCmpID] [int] NULL,
	[CtrKey] [varchar](100) NULL,
	[CtrHPID] [varchar](4) NULL,
	[CtrPlatinumID] [int] NULL,
	[CtrDateStart] [datetime] NULL,
	[CtrDateEffect] [datetime] NULL,
	[CtrDateRenew] [datetime] NULL,
	[CtrDateEnd] [datetime] NULL,
	[CtrYrQty] [int] NULL,
	[CtrSysCtrYN] [bit] NULL,
	[CtrAutoRenewYN] [bit] NULL,
	[CtrEndNoCseYN] [bit] NULL,
	[CtrNoCseDayQty] [int] NULL,
	[CtrEndCseYN] [bit] NULL,
	[CtrCseDayQty] [int] NULL,
	[CtrRemDayQty] [int] NULL,
	[CtrPriorAdjCollWIPAmtDefault] [money] NOT NULL,
	[CtrPriorCollectARDefault] [money] NOT NULL,
	[CtrPriorCollFeeAmtDefault] [money] NOT NULL,
	[CtrPriorLoanBalDefault] [money] NOT NULL,
	[CtrStipAmt] [money] NOT NULL,
	[CtrStipDesc] [varchar](50) NULL,
	[CtrOtherPayAmt] [money] NOT NULL,
	[CtrOtherPayDesc] [varchar](50) NULL,
	[CtrEmpPhysPaid] [int] NULL,
	[CtrWrkCompPaidYN] [bit] NULL,
	[CtrCompeteClauseYN] [bit] NULL,
	[CtrBillRecDayQty] [int] NULL,
	[CtrBillAgtDateStart] [datetime] NULL,
	[CtrMlpDateEffect] [datetime] NULL,
	[CtrTrmCtrYN] [bit] NULL,
	[CtrPrmBseYN] [bit] NULL,
	[CtrRsdAff] [varchar](50) NULL,
	[CtrElecLogYN] [bit] NULL,
	[CtrNrsInitProtoYN] [bit] NULL,
	[CtrTriageProtoYN] [bit] NULL,
	[CtrClnPthwyYN] [bit] NULL,
	[CtrPrcGdeYN] [bit] NULL,
	[CtrComputeAfcYN] [bit] NULL,
	[CtrElecMedRcdYN] [bit] NULL,
	[CtrObsvUnitYN] [bit] NULL,
	[CtrChstPnYN] [bit] NULL,
	[CtrFastTrkYn] [bit] NULL,
	[CtrOccMedYN] [bit] NULL,
	[CtrHspYN] [bit] NULL,
	[CtrSameStoreYN] [bit] NULL,
	[CtrGoodMethodYN] [bit] NULL,
	[CtrChestPainYN] [bit] NULL,
	[CtrElectronicTrackYN] [bit] NULL,
	[CtrPainMgmt] [varchar](50) NULL,
	[CtrAllowNursesYN] [bit] NULL,
	[CtrPhySpecificDataYN] [bit] NULL,
	[CtrComplaintMgtPrgYN] [bit] NULL,
	[CtrSatisfactionTool] [varchar](50) NULL,
	[CtrSatisfactionTeamYN] [bit] NULL,
	[CtrEDVolume] [int] NOT NULL,
	[CtrAdmissionPct] [float] NOT NULL,
	[CtrTransferPct] [float] NOT NULL,
	[CtrStatPITpct] [float] NOT NULL,
	[CtrStatRDpct] [float] NOT NULL,
	[CtrStatMDpct] [float] NOT NULL,
	[CtrStatContribpct] [float] NOT NULL,
	[CtrBseHour] [float] NOT NULL,
	[CtrBillRate] [float] NOT NULL,
	[CtrIncExpComment] [text] NULL,
	[CtrSiteOvrHdpct] [float] NOT NULL,
	[CtrIntRate] [float] NOT NULL,
	[CtrMlpFlatFee] [money] NOT NULL,
	[CtrMplSecondRate] [float] NOT NULL,
	[CtrLclPct] [float] NOT NULL,
	[CtrLclFixedAmt] [money] NOT NULL,
	[CtrMDIncentivePct] [float] NOT NULL,
	[CtrRDIncentivePct] [float] NOT NULL,
	[CtrSurplusReservePct] [float] NOT NULL,
	[zCtrMPRate] [float] NULL,
	[CtrDateFeeInc] [datetime] NULL,
	[CtrPctInc] [float] NOT NULL,
	[CtrNightPct] [float] NOT NULL,
	[CtrDiffRate] [float] NOT NULL,
	[CtrDiffAmt] [money] NOT NULL,
	[CtrDayRate] [money] NOT NULL,
	[CtrNightRate] [money] NOT NULL,
	[CtrBedQty] [int] NOT NULL,
	[CtrFastTrackBedQty] [int] NULL,
	[CtrOtherBedQty] [int] NULL,
	[CtrCriticalCareBedQty] [int] NULL,
	[CtrObservationBedQty] [int] NULL,
	[CtrEmail] [varchar](50) NULL,
	[CtrDateCreate] [datetime] NULL,
	[CtrDateEdit] [datetime] NULL,
	[CtrInactiveYn] [bit] NULL,
	[CtrTraumaDesignation] [varchar](50) NULL,
	[CtrFlagYn] [bit] NULL,
	[CtrComment] [text] NULL,
	[CtrRequireMailYN] [bit] NULL,
	[CtrCEPSurchargePct] [float] NOT NULL,
	[CtrMngCarBatchYN] [bit] NOT NULL,
	[CtrMisc1YN] [bit] NULL,
	[CtrMisc2YN] [bit] NULL,
	[CtrMisc3YN] [bit] NULL,
	[CtrMisc4YN] [bit] NULL,
	[CtrMisc5YN] [bit] NULL,
	[CtrPASupportCostPct] [float] NOT NULL,
	[CtrTIN] [nvarchar](15) NULL,
	[CtrDivision] [varchar](15) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
