USE [MngCarDB]
GO
/****** Object:  Table [dbo].[tlkpFeeSchYr]    Script Date: 09/08/2016 10:07:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tlkpFeeSchYr](
	[FeeSchYrID] [int] IDENTITY(1,1) NOT NULL,
	[FeeSchYrName] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FeeSchYrID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
