USE [MngCarDB]
GO
/****** Object:  Table [dbo].[tlkpFeeSchRgn]    Script Date: 09/08/2016 10:07:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tlkpFeeSchRgn](
	[FeeSchRgnID] [int] IDENTITY(1,1) NOT NULL,
	[FeeSchRgnName] [varchar](25) NOT NULL,
 CONSTRAINT [PK__tlkpFeeSchRgn__7AC1C32E] PRIMARY KEY NONCLUSTERED 
(
	[FeeSchRgnID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE UNIQUE CLUSTERED INDEX [IX_tlkpFeeSchRgn] ON [dbo].[tlkpFeeSchRgn] 
(
	[FeeSchRgnName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
