USE [MngCarDB]
GO
/****** Object:  Table [dbo].[tblCmpCnt]    Script Date: 09/08/2016 10:07:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblCmpCnt](
	[CmpCntID] [int] IDENTITY(1,1) NOT NULL,
	[CmpCnt_CmpID] [int] NOT NULL,
	[CmpCnt_CntID] [int] NOT NULL,
	[CmpCntRole] [varchar](50) NULL,
 CONSTRAINT [PK_tblCmpCnt] PRIMARY KEY CLUSTERED 
(
	[CmpCnt_CmpID] ASC,
	[CmpCnt_CntID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_CmpCntID] ON [dbo].[tblCmpCnt] 
(
	[CmpCntID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CmpCntRole] ON [dbo].[tblCmpCnt] 
(
	[CmpCntRole] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblCmpCnt]  WITH NOCHECK ADD  CONSTRAINT [FK_tblCmpCnt_tblCmp] FOREIGN KEY([CmpCnt_CmpID])
REFERENCES [dbo].[tblCmp] ([CmpID])
GO
ALTER TABLE [dbo].[tblCmpCnt] CHECK CONSTRAINT [FK_tblCmpCnt_tblCmp]
GO
ALTER TABLE [dbo].[tblCmpCnt]  WITH NOCHECK ADD  CONSTRAINT [FK_tblCmpCnt_tblCnt] FOREIGN KEY([CmpCnt_CntID])
REFERENCES [dbo].[tblCnt] ([CntID])
GO
ALTER TABLE [dbo].[tblCmpCnt] CHECK CONSTRAINT [FK_tblCmpCnt_tblCnt]
GO
