CREATE PROCEDURE [dbo].[stpAppendStandard_Anes_SiteLine_Report]
(@sttDate datetime)
-- [stpAppendStandard_Anes_SiteLine_Report]  '2015-08-01 00:00:00'
-- [stpTestAppendSiteLineReportTables_Anes]  --For Testing
-- select * from  [tblStandard_Anes_SiteLine_Report] where reportdate = 'Dec 2015'
--stpAppendStandard_Anes_SiteLine_Report 'Apr  1 2015 12:00AM'
AS 
Begin
Set NoCount on

--REMOVE AFTER TESTING
--truncate table tblStandard_Anes_SiteLine_Report

--Insert int table
INSERT INTO [tblStandard_Anes_SiteLine_Report]
		(Site, 
		ReportDate, 
		SttPstChgs, 
		calcBdgPstChgs, 
		ytdSttPstChgs, 
		ytdBdgPstChgs, 
		SttTargetRate, 
		BdgTargetRate, 
		ytdSttTargetRate, 
		ytdBdgTargetRate, 
		SttGrossCollAmt, 
		calcBdgGrossColl, 
		ytdGrossColl, 
		ytdBdgGrossColl, 
		SttStipRcvd, 
		calcBdgStipendsRcvd,
		ytdStipendsRcvd, 
		ytdBdgStipendsRcvd, 
		SttOtherRcpts, 
		calcBdgOthRcpts, 
		ytdOtherRcpts, 
		ytdBdgOthRcpts, 
		SttWIPGainLossAmt, 
		ytdWIPGainLoss, 
        SttValuationGainLossAmt, 
        ytdValuationGainLoss, 
        SttTotalCollAmt, 
        calcBdgTotalColl, 
        ytdTotalColl, 
        ytdBdgTotalColl, 
        SttMPRate, 
        SttMlpAmt, 
        calcBdgMalpractice, 
        ytdMalpractice, 
        ytdBdgMalpractice, 
        SttBillFee, 
        calcBdgBillFee, 
        ytdSttBillFee, 
        ytdBdgBillFee, 
        calcSttCollFeeChgAmt, 
        calcYtdSttCollFeeChgAmt, 
        SttIntAmt, 
        calcBdgInterest, 
        ytdInterest, 
        ytdbdgInterest,
        --SttSiteOvrHdPct, 
        --calcSttSiteOverheadAmt, 
        --calcBdgSiteOverhead, 
        --calcytdSiteOverhead, 
        --ytdBdgSiteOverhead,  
        calcSttOffTop, 
        calcBdgOffTop, 
        calcytdSttOffTop, 
        calcytdBdgOffTop, 
        calcSttBillSpec, 
        calcBdgBillSpec, 
        calcYtdBillSpec, 
        ytdBdgBillSpec, 
        SttNorAmt, 
        calcSttNorAmt, 
        calcBdgNOR, 
        calcNOR, 
        ytdNOR, 
        ytdBdgNOR, 
        SttDocPaidAmt, 
        SttCompPITpct, 
        BdgPITearned, 
        BdgPITEarnedPct, 
        caclytdSttDocPaidAmt, 
        ytdPITpct, 
        ytdBdgPITEarned, 
        ytdBdgPITPct,  
        SttStatPITpct,  --start
        calcSttPTOTotalCost, 
        SttPACostPct, 
        calcBdgPACostPct, 
        BdgPACostPct, 
        calcytdSttPTOTotalCost, 
        ytdSttPACostPct, 
        calcytdBdgPACost, 
        ytdBdgPACostPct, 
        SttPTCost, 
        SttPTCostPct,                      
        calcBdgPTCost, 
        BdgPTCostPct, 
        ytdSttPTCost, 
        ytdSttPTCostPct, 
        ytdBdgPTCost, 
        ytdBdgPTCostPct, --end                       
        calcSttLclExp, 
        SttLclExpPct, 
        calcBdgLclExp, 
        BdgLclExpPct, 
        calcytdSttLclExp, 
        ytdSttLclExpPct, 
        ytdBdgLclExp, 
        ytdBdgLclExpPct, 
        calcSttNonCurrAdjAmt, 
        calcSttNonCurrAdjAmtNor, 
        calcytdSttNonCurrAdjAmt, 
        calcytdSttNonCurrAdjAmtNor, 
        SttMDpct, 
        SttMDPaidAmt, 
        SttCompMDpct, 
        calcBdgMDearned, 
        BdgMDpct, 
        ytdSttMDPaidAmt, 
        ytdMDpct, 
        ytdBdgMDearned, 
        ytdBdgMDpct, 
        SttRDpct, 
        calcSttRDEarnedAmt, 
        SttCompRDpct, 
        calcBdgRDearned, 
        BdgRDpct, 
        calcYtdSttRDEarnedAmt, 
        ytdRDpct, 
        ytdBdgRDearned, 
        ytdBdgRDpct, 
        SttContribPct, 
        SttContribCEPAmt, 
        calcSttNorAmtIf, 
        calcBdgContribCEP, 
        BdgContribPct, 
        ytdContribCEP, 
        ytdStatContribPct, 
        ytdBdgContribCEP, 
        ytdBdgContribPct, 
        SttSiteNetIncAmt, 
        SttNetPctofNOR, 
        calcBdgSiteNetInc, 
        BdgNetPctofNOR, 
        ytdSiteNetInc, 
        ytdNetPctofNOR, 
        ytdBdgSiteNetInc, 
        ytdBdgNetPctofNOR, 
        SttPatVisitQty, 
        calcBdgPatients, 
        ytdSttPatVisitQty, 
        ytdBdgPatients, 
        SttPtsKeyed, 
        ytdSttPtsKeyed, 
        SttPatVisitUCQty,  --Start
        BdgPatVisitUCQty,  
        ytdSttPatVisitUCQty,  
        ytdBdgPatVisitUCQty,                        
        SttPhysTherVisitQty, 
        BdgPhysTherVisitQty, 
        ytdSttPhysTherVisitQty,  
        ytdBdgPhysTherVisitQty  ,                      
        SttDocPaidHourAmt,  
        calcSttDocPaidHourAmt, 
        ytdSttDocPaidAmtHrly, 
        calcytdSttDocPaidAmtHrly,                       
        SttDocEarnedHourAmt, 
        BdgDocEarnedHrly, 
        ytdDocEarnedHrly,    
        ytdBdgDocEarnedHrly,                      
        SttDocHourQty,  
        calcBdgDocHours, 
        ytdDocHours,   
        ytdBdgDocHours,
        SttPAhoursQty,  
        calcBdgPAHours, 
        ytdPAHours,  
        ytdBdgPAHours,                        
        SttPACostHr,  
        BdgPACostHr,  
        ytdPACostHr, 
        ytdBdgPAPaidHrly ,         
        SttAvgChgBilledUnit, 
        bdgAvgChgBilledUnit, 
        YTDSttAvgChgBilledUnit, 
        ytdbdgAvgChgBilledUnit, --end 
        SttAvgChgPt, 
        BdgAvgChgPt, 
        ytdAvgChgPt, 
        ytdbdgAvgChgPt, 
        SttCollPerPtAmt, 
        BdgCollPerPt,
        ytdCollPerPt, 
        ytdBdgCollPerPt, 
        SttTotalCollPerPt, 
        calcbdgtotalColl2, 
        ytdTotalCollPerPt,
        calcYtdBdgTotalColl, 
        SttPriorCollectAR, 
        SttGrossCollAmt2, 
        SttWIPGainLossAmt2, 
        SttValuationGainLossAmt2,
		SttCollFeeChgAmt, 
		calcSttCashARAmt, 
		SttRefAR, 
		SttNetChangeinARAmt, 
		SttEndCollectAR, 
		SttPriorLoanBal, 
        SttCashExpAmt, 
        SttCashARAmt, 
        calcSttRefAR, 
        SttStipRcvd2, 
        SttOtherRcpts2,
		SttCashRcptAmt, 
		SttCurrLoanBal, 
		calcSttPriorLoanBal, 
		calcSttNetChangeinARAmt, 
		calcSttEndCollectAR, 
        MandatoryReserve, 
        SttSurplusReserveNote, 
        calcSttSurplusReservePctIf, 
        calcAdditionalSurplusReservebyPct,  
        calcEndMonthSurplus, 
        MedicalDirector, 
		SttAccExpenseAmt, 
		YtdSttACCExpenseAmt, 
        SttSiteOverheadAmt, 
        YtdSiteOverhead, 
        calcSttSiteOverheadAmt2,
		calcYtdSttACCExpenseAmt,  
		SttDonationAmt, 
		YtdSttDonationAmt, 
		SttOffTop, 
		YtdSttOffTop, 
		SttCEPSurchargeAmt, 
        YtdSttCEPSurchargeAmt, 
        calcSttOffTop2, 
        calcytdSttOffTop2,
		SttBillSpec, 
		YtdBillSpec, 
		SttBillSpecMBSIAmt, 
		YtdSttBillSpecMBSIAmt, 
		SttBillSpecScribesAmt, 
		YTDSttBillSpecScribesAmt, 
        SttBillSpecScribesAdjAmt, 
        YTDSttBillSpecScribesAdjAmt, 
        SttBillSpecSitePersonnelAmt, 
        YTDSttBillSpecSitePersonnelAmt, 
        SttBillSpecSitePersonnelAdjAmt, 
        YTDSttBillSpecSitePersonnelAdjAmt, 
        calcSttBillSpec2, 
        calcYtdBillSpec2,
		SttPACost, 
		YtdSttPACost, 
		SttPTOTotalCost, 
		YTDSttPTOTotalCost, 
        calcSttPASupportCostAmt, 
        calcYtdSttPASupportCostAmt, 
        calcSttPTOTotalCost3, 
        calcytdSttPTOTotalCost2,        
		SttPTCost2,  /*start*/
		YtdSttPTCost2,
		SttPTAdjAmt, 
		YtdSttPTAdjAmt, 
		calcSttPTAdjAmt, 
		calcYtdSttPTAdjAmt,  /*end*/		
		SttLclExp,
		YtdSttLclExp, 
        SttFixedLocalAmt, 
        YtdSttFixedLocalAmt, 
        calcSttLclExp2, 
        calcYTDSttLclExp2, 
        SttNonCurrAdjAmt, 
        YtdSttNonCurrAdjAmt, 
        SttSurplusPayout, 
        YtdSttSurplusPayout,
        SttNonCurrMDAmt, 
        YtdSttNonCurrMDAmt, 
        SttNonCurrRDAmt, 
        YtdSttNonCurrRDAmt, 
        SttSrpAdjAmt, 
        YtdSttSrpAdjAmt, 
        calcSttSrpAdjAmt, 
        calcYtdSttSrpAdjAmt, 
        calcValuationGainLossComment, 
        calcSrpAdjAmtComment, 
        calcWIPGainLossComment, 
        calcUnspecifiedComment, 
        calcCommentOther, 
        calcExpComment, 
        SiteLineSiteID, 
        ProcessLevel, 
        calcSttPTOTotalCost4, 
        calcytdSttPTOTotalCost3
		 )
Select Site, 
CONVERT(CHAR(4), ReportDate, 100) + convert(varchar(4),year(ReportDate))  , 
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttPstChgs,0)))), 
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgPstChgs]/[MthYearDays]*[MthDays],0)))), 
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdSttPstChgs,0)))), 
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgPstChgs,0)))), 
convert (varchar(50),round(convert(decimal(9,2),SttTargetRate*100),2))+'%', 
convert (varchar(50),round(convert(decimal(9,2),BdgTargetRate*100),2))+'%', 
convert (varchar(50),round(convert(decimal(9,2),ytdSttTargetRate*100),2))+'%', 
convert (varchar(50),round(convert(decimal(9,2),ytdBdgTargetRate*100),2))+'%', 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttGrossCollAmt,0)))), 
case when [MthYearDays]*[MthDays] = 0 then '0' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgGrossColl]/[MthYearDays]*[MthDays],0))) end as calcBdgGrossColl,  
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdGrossColl,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgGrossColl,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttStipRcvd,0)))), 
case when [MthYearDays]*[MthDays] = 0 then '0' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgStipendsRcvd]/[MthYearDays]*[MthDays],0))) end as calcBdgStipendsRcvd, 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdStipendsRcvd,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgStipendsRcvd,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttOtherRcpts,0)))), 
case when [MthYearDays]*[MthDays] = 0 then '0' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgOthRcpts]/[MthYearDays]*[MthDays],0))) end as calcBdgOthRcpts, 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdOtherRcpts,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgOthRcpts,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttWIPGainLossAmt,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdWIPGainLoss,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttValuationGainLossAmt,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdValuationGainLoss,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttTotalCollAmt,0)))), 
case when [MthYearDays]*[MthDays] = 0 then '0' else dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgTotalColl]/[MthYearDays]*[MthDays],0)))) end as calcBdgTotalColl, 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdTotalColl,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgTotalColl,0)))), 
dbo.fn_removeMinusSign('$'+convert (varchar(50),Cast(SttMPRate as money))),  
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttMlpAmt,0)))), 
case when [MthYearDays]*[MthDays] = 0 then '0' else dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgMalpractice]/[MthYearDays]*[MthDays],0)))) end as calcBdgMalpractice, 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdMalpractice,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgMalpractice,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttBillFee,0)))), 
case when [MthYearDays]*[MthDays] = 0 then '0' else dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgBillFee]/[MthYearDays]*[MthDays],0)))) end  as calcBdgBillFee,  
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdSttBillFee,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgBillFee,0)))), 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,-([SttCollFeeChgAmt]),0)))) as calcSttCollFeeChgAmt, 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,-([YtdSttCollFeeChgAmt]),0)))) as calcYtdSttCollFeeChgAmt, 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttIntAmt,0)))), 
case when [MthYearDays]*[MthDays] = 0 then '0' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgInterest]/[MthYearDays]*[MthDays],0))) end as calcBdgInterest, 
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdInterest,0))), 
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdbdgInterest,0))),
--dbo.fn_removeMinusSign(convert (varchar(50),round(SttSiteOvrHdPct*100,1))),
--dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttSiteOverheadAmt]+[SttAccExpenseAmt],0))) as calcSttSiteOverheadAmt,
--case when [MthYearDays]*[MthDays] = 0 then '0' else  dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgSiteOverhead]/[MthYearDays]*[MthDays],0))) end as calcBdgSiteOverhead,
--dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[ytdSiteOverhead]+[YtdSttAccExpenseAmt],0))) as calcytdSiteOverhead,
--dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgSiteOverhead,0))),
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttOffTop]+[SttDonationAmt]+[SttCEPSurchargeAmt],0))) as calcSttOffTop,
case when [MthYearDays]*[MthDays] = 0 then '0' else  dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,([BdgOffTop]+[BdgCEPRetentionAmt]+[BdgDonations])/[MthYearDays]*[MthDays],0))) end as calcBdgOffTop,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[ytdSttOffTop]+[YtdSttDonationAmt]+[YtdSttCepSurchargeAmt],0))) as calcytdSttOffTop,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[ytdBdgOffTop]+[YtdBdgCEPRetentionAmt]+[YtdBdgDonations],0))) as calcytdBdgOffTop,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttBillSpec]+[SttBillSpecMBSIAmt]+[SttBillSpecScribesAmt]+[SttBillSpecSitePersonnelAmt]+[SttBillSpecScribesAdjAmt]+[SttBillSpecSitePersonnelAdjAmt],0))) as calcSttBillSpec,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgBillSpec]/[MthYearDays]*[MthDays],0))) as calcBdgBillSpec,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[YtdBillSpec]+[YtdSttBillSpecMBSIAmt]+[YTDSttBillSpecScribesAmt]+[YTDSttBillSpecSitePersonnelAmt]+[YTDSttBillSpecScribesAdjAmt]+[YTDSttBillSpecSitePersonnelAdjAmt],0))) as calcYtdBillSpec,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgBillSpec,0))),
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttNorAmt,0)))),
case when SttNorAmt = 0 then '0' else  convert (varchar(50),convert(decimal(9,1),(SttNorAmt/SttNorAmt)*100))+'%' end as calcSttNorAmt, 
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgNOR]/[MthYearDays]*[MthDays],0))) as calcBdgNOR,
case when SttNorAmt = 0 then '0' else  convert (varchar(50),convert(decimal(9,1),(SttNorAmt/SttNorAmt)*100))+'%' end as calcNOR, 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdNOR,0)))),
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgNOR,0)))),
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttDocPaidAmt]+[SttDocPaidAdjAmt],0)))) as SttDocPaidAmt,
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),SttCompPITpct*100))+'%'),
case when [MthYearDays]*[MthDays] = 0 then '0' else dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgPITearned]/[MthYearDays]*[MthDays],0)))) end as BdgPITearned,
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),BdgPITEarnedPct*100)))+'%',
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[ytdSttDocPaidAmt]+[ytdSttDocPaidAmtAdj],0))) as caclytdSttDocPaidAmt,
convert (varchar(50),convert(decimal(9,1),ytdPITpct*100))+'%',
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgPITEarned,0)))),
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),ytdBdgPITPct*100)))+'%',
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),SttStatPITpct*100)))+'%' as SttStatPITpct,   --start
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttPTCost,0))),
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),SttPTCostPct*100)))+'%' ,
case when [MthYearDays]*[MthDays] = 0 then '0.' else dbo.fn_FormatWithCommas(convert(varchar(50),convert(int,([BdgPTCost]/[MthYearDays]*[MthDays])))) end ,
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),BdgPTCostPct*100)))+'%' ,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdSttPTCost,0))),
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),ytdSttPTCostPct*100)))+'%' ,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgPTCost,0))),
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),ytdBdgPTCostPct*100)))+'%' ,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int, [SttPTOTotalCost]+[SttPACost]-[SttPASupportCostAmt],0))),
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),SttPACostPct*100)))+'%' ,
case when [MthYearDays]*[MthDays] = 0 then '0.' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,(([BdgPACost]-[BdgPASupportCostAmt])/[MthYearDays]*[MthDays])))) end ,
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),BdgPACostPct*100)))+'%' ,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[ytdSttPTOTotalCost]+[YtdSttPACost]-([YtdSttPASupportCostAmt]),0))),
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),ytdSttPACostPct*100)))+'%' ,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[ytdBdgPACost]-[YtdBdgPASupportCostAmt],0))) ,
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),ytdBdgPACostPct*100)))+'%' ,  --end
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,([SttLclExp]+[SttFixedLocalAmt]+[SttLclVarAmt]),0))) as calcSttLclExp,
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),round(SttLclExpPct*100,1)))+'%'),
case when [MthYearDays]*[MthDays] = 0 then '0' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgLclExp]/[MthYearDays]*[MthDays],0))) end  as calcBdgLclExp,
convert (varchar(50),convert(decimal(9,1),round(BdgLclExpPct*100,1)))+'%',
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[ytdSttLclExp]+[YtdSttFixedLocalAmt]+[YtdSttLclVarAmt],0))) as calcytdSttLclExp,
convert (varchar(50),convert(decimal(9,1),round(ytdSttLclExpPct*100,1)))+'%',
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgLclExp,0))),
convert (varchar(50),convert(decimal(9,1),round(ytdBdgLclExpPct*100,1)))+'%',
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttNonCurrAdjAmt]+[SttSrpAdjAmt]+[SttMDIncentiveAmt]+[SttRDIncentiveAmt]+[SttSurplusPayout]+[SttNonCurrMDAmt]+[SttNonCurrRDAmt],0)))) as calcSttNonCurrAdjAmt,
case when [SttNorAmt] = 0 then '0.0%' else dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),([SttNonCurrAdjAmt]+[SttSrpAdjAmt]+[SttMDIncentiveAmt]+[SttRDIncentiveAmt]+[SttSurplusPayout]+[SttNonCurrMDAmt]+[SttNonCurrRDAmt])/[SttNorAmt])))+'%') end as calcSttNonCurrAdjAmtNor,
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[ytdSttNonCurrAdjAmt]+[ytdSttSrpAdjAmt]+[YtdSttSurplusPayout]+[YtdSttNonCurrMDAmt]+[YtdSttNonCurrRDAmt]+[YtdSttMDIncentiveAmt]+[YtdSttRDIncentiveAmt],0)))) as calcytdSttNonCurrAdjAmt,
case when [YtdNOR] = 0 then '0.0%' else dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),(([ytdSttNonCurrAdjAmt]+[ytdSttSrpAdjAmt]+[YtdSttSurplusPayout]+[YtdSttNonCurrMDAmt]+[YtdSttNonCurrRDAmt]+[YtdSttMDIncentiveAmt]+[YtdSttRDIncentiveAmt])/[YtdNOR]) * 100)))+'%') end as calcytdSttNonCurrAdjAmtNor,
convert (varchar(50),cast(SttMDpct*100 as money))+'%',
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttMDPaidAmt,0))),
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),SttCompMDpct*100))+'%'),
case when [MthYearDays]*[MthDays] = 0 then '0' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgMDearned]/[MthYearDays]*[MthDays],0))) end as calcBdgMDearned,
convert (varchar(50),convert(decimal(9,1),round(BdgMDpct,3)*100))+'%',
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdSttMDPaidAmt,0))),
convert (varchar(50),convert(decimal(9,1),ytdMDpct*100))+'%',
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgMDearned,0))),
convert (varchar(50),convert(decimal(9,1),ytdBdgMDpct*100))+'%',
convert (varchar(50),convert(decimal(9,2),SttRDpct*100))+'%',
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttRDEarnedAmt]-[SttRDLclAmt],0)))) as calcSttRDEarnedAmt,
convert (varchar(50),convert(decimal(9,1),SttRDpct*100))+'%',
case when [MthYearDays]*[MthDays] = 0 then '0' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgRDearned]/[MthYearDays]*[MthDays],0))) end as calcBdgRDearned,
convert (varchar(50),convert(decimal(9,1),BdgRDpct*100))+'%',
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,([YtdSttRDEarnedAmt]-[YtdSttRDLclAmt]),0)))) as calcYtdSttRDEarnedAmt,
convert (varchar(50),convert(decimal(9,1),ytdRDpct * 100))+'%',
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgRDearned,0))),
convert (varchar(50),convert(decimal(9,1),ytdBdgRDpct*100))+'%',
convert (varchar(50),cast(SttContribPct*100 as money))+'%',
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttContribCEPAmt,0)))),
case when [SttNorAmt]=0 then '0.0%'	else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),([SttContribCEPAmt]/[SttNorAmt])*100))) +'%' end as calcSttNorAmtIf,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgContribCEP]/[MthYearDays]*[MthDays],0))) as calcBdgContribCEP,
convert (varchar(50),convert(decimal(9,1),BdgContribPct*100))+'%',
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdContribCEP,0)))),
convert (varchar(50),convert(decimal(9,1),ytdStatContribPct*100))+'%',
dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgContribCEP,0))),
convert (varchar(50),convert(decimal(9,1),ytdBdgContribPct*100))+'%',
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttSiteNetIncAmt,0)))),
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),SttNetPctofNOR*100))+'%'),
case when [MthYearDays]*[MthDays] = 0 then '0' else '$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[BdgSiteNetInc]/[MthYearDays]*[MthDays],0))) end  as calcBdgSiteNetInc,
convert (varchar(50),round(convert(decimal(9,1),BdgNetPctofNOR*100),1))+'%',
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdSiteNetInc,0)))),
dbo.fn_removeMinusSign(convert (varchar(50),convert(decimal(9,1),ytdNetPctofNOR*100))+'%'),
'$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdBdgSiteNetInc,0))),
convert (varchar(50),round(convert(decimal(9,1),ytdBdgNetPctofNOR*100),1))+'%',
dbo.fn_FormatWithCommas(SttPatVisitQty),
case when [MthYearDays]*[MthDays] = 0 then '0'  else dbo.fn_FormatWithCommas(convert(int,round(convert(float,[BdgPatients])/convert(float,[MthYearDays])*convert(float,[MthDays]),0))) end  as calcBdgPatients,
dbo.fn_FormatWithCommas(ytdSttPatVisitQty),
dbo.fn_FormatWithCommas(convert(float,round(ytdBdgPatients,0),0)),
dbo.fn_FormatWithCommas(SttPtsKeyed),
dbo.fn_FormatWithCommas(ytdSttPtsKeyed),
dbo.fn_FormatWithCommas(SttAdmitQty),  --Start
case when [MthYearDays]*[MthDays] = 0 then '0.0%' else dbo.fn_FormatWithCommas([BdgEncounters]/[MthYearDays]*[MthDays]) end as BilledUnits,
dbo.fn_FormatWithCommas(YtdSttAdmitQty),
dbo.fn_FormatWithCommas(YTDBdgEncounters),
case when dbo.fn_CalculateDaysInMonth(SttDate) = 0 then '0' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),[SttAdmitQty]/  dbo.fn_CalculateDaysInMonth(SttDate)))) end ,
dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),[BdgEncounters]/365))) ,
case when dbo.fn_CalculateDaysInMonth(SttDate) = 0 then '0' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),YtdSttBilledUnitQty/ dbo.fn_CalculateDaysYTD(SttDate)))) end ,
case when dbo.fn_CalculateDaysYTD(SttDate) = 0 then '0' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),[YTDBdgEncounters]/dbo.fn_CalculateDaysYTD(SttDate))))  end ,
case when '$'+SttDocPaidHourAmt = 0 then '$0.00' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),SttDocPaidHourAmt))) end    ,
case when [SttDocEarnedHourAmt] = 0 then '0.0%' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),[SttDocPaidHourAmt]/[SttDocEarnedHourAmt]*100))+'%') end   ,
case when '$'+ytdSttDocPaidAmtHrly = 0 then '$0.00' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),ytdSttDocPaidAmtHrly))) end    ,
case when [ytdDocEarnedHrly] = 0 then '0.0%' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),[ytdSttDocPaidAmtHrly]/[ytdDocEarnedHrly]*100))+'%') end   ,
case when '$'+SttDocEarnedHourAmt = 0 then '$0.00' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),SttDocEarnedHourAmt))) end  as SttDocEarnedHourAmt,
case when '$'+BdgDocEarnedHrly = 0 then '$0.00' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),BdgDocEarnedHrly))) end as  BdgDocEarnedHrly,
case when '$'+ytdDocEarnedHrly = 0 then '$0.00' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),ytdDocEarnedHrly))) end  as ytdDocEarnedHrly,
case when '$'+ytdBdgDocEarnedHrly = 0 then '$0.00' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),ytdBdgDocEarnedHrly))) end as  ytdBdgDocEarnedHrly,
case when SttDocHourQty = 0 then '0.0' else   dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),SttDocHourQty))) end  as SttDocHourQty,
case when  [MthYearDays]*[MthDays] = 0 then '0.0' else   dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),[BdgDocHours]/[MthYearDays]*[MthDays]))) end , 
case when ytdDocHours = 0 then '0.0' else   dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),ytdDocHours))) end  as ytdDocHours,
case when ytdBdgDocHours = 0 then '0.0' else   dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),ytdBdgDocHours))) end  as ytdBdgDocHours,
case when SttDocHourQty = 0 then '0.0' else   dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),SttPAhoursQty))) end  as  SttPAhoursQty,
case when [MthYearDays]*[MthDays] = 0 then '0.0' else   dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),[BdgPAHours]/[MthYearDays]*[MthDays]))) end    ,
case when ytdPAHours = 0 then '0.0' else   dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),ytdPAHours))) end  as ytdPAHours,
case when ytdBdgPAHours = 0 then '0.0' else   dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,1),ytdBdgPAHours))) end  as ytdBdgPAHours,
case when [SttPAhoursQty] = 0 then '$0.00' else '$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),([SttPTOTotalCost]+[SttPACost]-[SttPASupportCostAmt])/([SttPAhoursQty])))) end  ,
case when '$'+BdgPACostHr = 0 then '$0.00' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),BdgPACostHr))) end  as BdgPACostHr,
case when [ytdPAHours] = 0 then '$0.00' else '$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),([ytdSttPTOTotalCost]+[YtdSttPACost]-([YtdSttPASupportCostAmt]))/([ytdPAHours])))) end  ,
case when '$'+ytdBdgPAPaidHrly = 0 then '$0.00' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),ytdBdgPAPaidHrly))) end  as ytdBdgPAPaidHrly  , 
dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),SttAvgChgBilledUnit))) , 
dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),BdgDocEarnedHrly)))  , 
dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),YTDSttAvgChgBilledUnit))) , 
case when [YTDBdgEncounters] = 0 then '0.00' else dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),[YtdBdgPstChgs]/[YTDBdgEncounters]))) end as  ytdbdgAvgChgBilledUnit  ,  --end 
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert(varchar(50),cast(round(SttAvgChgPt,2) as money))) ),
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert(varchar(50),cast(round(BdgAvgChgPt,2) as money))) ),
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert(varchar(50),cast(round(ytdAvgChgPt,2) as money)) )),
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert(varchar(50),cast(round(ytdbdgAvgChgPt,2) as money))) ),
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert(varchar(50),cast(round(SttCollPerPtAmt,2) as money))) ),
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert(varchar(50),cast(round(BdgCollPerPt,2) as money))) ),
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert(varchar(50),cast(round(ytdCollPerPt,2) as money)) )),
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert(varchar(50),cast(round(ytdBdgCollPerPt,2) as money))) ),
dbo.fn_removeMinusSign(dbo.fn_FormatWithCommas(convert(varchar(50),cast(round(SttTotalCollPerPt,2) as money))) ),
case when [BdgPatients] = 0 then '$0.00' else '$'+dbo.fn_FormatWithCommas(convert(varchar(50),cast(round([bdgtotalColl]/[BdgPatients],2) as money)) ) end  as calcbdgtotalColl2,
'$'+convert(varchar(50),cast(round(ytdTotalCollPerPt,2) as money) ),
case when [YtdBdgPatients] = 0 then '$0.00' else '$'+dbo.fn_FormatWithCommas(convert(varchar(50),cast(round([YtdBdgTotalColl]/[YtdBdgPatients],2) as money)) ) end as calcYtdBdgTotalColl,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttPriorCollectAR,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttGrossCollAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttWIPGainLossAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttValuationGainLossAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttCollFeeChgAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttCashARAmt]*-1,0)))) as calcSttCashARAmt,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttRefAR,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttNetChangeinARAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttEndCollectAR,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttPriorLoanBal,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttCashExpAmt,0)))),
'$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttCashARAmt,0))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttRefAR]*-1,0)))) as calcSttRefAR,
'$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttStipRcvd,0))),
'$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttOtherRcpts,0))), 
'$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttCashRcptAmt,0))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttCurrLoanBal,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttPriorLoanBal]+[SttPriorCollectAR],0)))) as calcSttPriorLoanBal,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,([SttNetChangeinARAmt]+[SttCashExpAmt]+[SttCashRcptAmt]),0)))) as calcSttNetChangeinARAmt,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttEndCollectAR]+[SttCurrLoanBal],0)))) as calcSttEndCollectAR,
'$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,round([SttEndCollectAR]*0.05,0),0))) as MandatoryReserve,
SttSurplusReserveNote,
'' as calcSttSurplusReservePctIf,--case when [SttSurplusReservePct]=0 then '0' else dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttSurplusReservePct],0)))) end  as calcSttSurplusReservePctIf,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,([SttSurplusReservePct]*[SttEndCollectAR]) + [SttSurplusReserveAmt],0)))) as calcAdditionalSurplusReservebyPct,
 dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,0),([SttEndCollectAR]+[SttCurrLoanBal])-([SttEndCollectAR]*0.05) - ([SttSurplusReservePct]*[SttEndCollectAR]+[SttSurplusReserveAmt])-([SttSurplusReservePct]*[SttEndCollectAR]+[SttSurplusReserveAmt] -(([SttSurplusReservePct]*[SttEndCollectAR]) + [SttSurplusReserveAmt])),0)))) as calcEndMonthSurplus, 
MedicalDirector,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttAccExpenseAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttACCExpenseAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttSiteOverheadAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSiteOverhead,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttSiteOverheadAmt]+[SttAccExpenseAmt],0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[YtdSttACCExpenseAmt]+[YtdSiteOverhead],0)))) as calcYtdSttACCExpenseAmt,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttDonationAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttDonationAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttOffTop,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttOffTop,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttCEPSurchargeAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttCEPSurchargeAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttOffTop]+[SttDonationAmt]+[SttCEPSurchargeAmt],0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[ytdSttOffTop]+[YtdSttDonationAmt]+[YtdSttCepSurchargeAmt],0)))), 
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttBillSpec,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdBillSpec,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttBillSpecMBSIAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttBillSpecMBSIAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttBillSpecScribesAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YTDSttBillSpecScribesAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttBillSpecScribesAdjAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YTDSttBillSpecScribesAdjAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttBillSpecSitePersonnelAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YTDSttBillSpecSitePersonnelAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttBillSpecSitePersonnelAdjAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YTDSttBillSpecSitePersonnelAdjAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttBillSpec]+[SttBillSpecMBSIAmt]+[SttBillSpecScribesAmt]+[SttBillSpecSitePersonnelAmt]+[SttBillSpecScribesAdjAmt]+[SttBillSpecSitePersonnelAdjAmt],0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[YtdBillSpec]+[YtdSttBillSpecMBSIAmt]+[YTDSttBillSpecScribesAmt]+[YTDSttBillSpecSitePersonnelAmt]+[YTDSttBillSpecScribesAdjAmt]+[YTDSttBillSpecSitePersonnelAdjAmt],0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttPACost,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttPACost,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttPTOTotalCost,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YTDSttPTOTotalCost,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,([SttPASupportCostAmt]),0)))) as calcSttPASupportCostAmt,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,([YtdSttPASupportCostAmt]),0)))) as calcYtdSttPASupportCostAmt,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttPTOTotalCost]+[SttPACost]-([SttPASupportCostAmt]),0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[ytdSttPTOTotalCost]+[YtdSttPACost]-([YtdSttPASupportCostAmt]),0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttPTCost,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,ytdSttPTCost,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttPTAdjAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttPTAdjAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttPTAdjAmt]+[SttPTCost],0)))) as calcSttPTAdjAmt,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[YtdSttPTAdjAmt]+[YtdSttPTCost],0))))as calcYtdSttPTAdjAmt,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttLclExp,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttLclExp,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttFixedLocalAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttFixedLocalAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttLclExp]+[SttFixedLocalAmt],0)))) as calcSttLclExp2,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[YTDSttLclExp]+[YTDSttFixedLocalAmt],0)))) as calcYTDSttLclExp2,
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttNonCurrAdjAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttNonCurrAdjAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttSurplusPayout,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttSurplusPayout,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttNonCurrMDAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttNonCurrMDAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttNonCurrRDAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttNonCurrRDAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,SttSrpAdjAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,YtdSttSrpAdjAmt,0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[SttSrpAdjAmt]+[SttNonCurrAdjAmt]+[SttSurplusPayout]+[SttMDIncentiveAmt]+[SttRDIncentiveAmt]+[SttNonCurrMDAmt]+[SttNonCurrRDAmt],0)))),
dbo.fn_removeMinusSign('$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(int,[YtdSttSrpAdjAmt]+[YtdSttNonCurrAdjAmt]+[YtdSttSurplusPayout]+[YtdSttMDIncentiveAmt]+[YtdSttRDIncentiveAmt]+[YtdSttNonCurrMDAmt]+[YtdSttNonCurrRDAmt],0)))),
case when [SttValuationGainLossComment] is null then '' else 'Valuation Gain (Loss): "'+  cast([SttValuationGainLossComment] as varchar(255)) end as calcValuationGainLossComment,
case when [SttSrpAdjAmtComment] is null then '' else 'Surplus Adjustments: '+ cast([SttSrpAdjAmtComment]as varchar(255)) end as calcSrpAdjAmtComment,
case when [SttWIPGainLossComment] is null then '' else 'WIP Change: '+ cast([SttWIPGainLossComment]as varchar(255)) end as calcWIPGainLossComment,
case when [SttUnspecifiedComment] is null then '' else 'Other Receipts: '+ cast([SttUnspecifiedComment]as varchar(255)) end as calcUnspecifiedComment,
case when [SttCommentOther] is null then '' else 'Other Notes: '+ cast([SttCommentOther]as varchar(255)) end as calcCommentOther,
case when [CtrIncExpComment] is null then '' else 'Recuring Site Notes: '+ cast([CtrIncExpComment]as varchar(255)) end as  calcExpComment,
CtrID,
CtrTIN,
case when [SttPAhoursQty] = 0 then '$0.00' else '$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),(([SttPTOTotalCost]+[SttPACost]-[SttPASupportCostAmt])/[SttPAhoursQty])))) end ,
case when [ytdPAHours] = 0 then '$0.00' else '$'+dbo.fn_FormatWithCommas(convert (varchar(50),convert(decimal(9,2),([ytdSttPTOTotalCost]+[YtdSttPACost]-[YtdSttPASupportCostAmt])/[ytdPAHours]))) end/* */
from dbo.vwSttBdg 
where sttdate = @sttDate
	and Ctr_CtrTypID= 'ANES' 	
	and SttPublishYN = 1 --Exclude Records not ready for publishing

Set NoCount off

End
 
















