

CREATE PROCEDURE [dbo].[LoapStipendPayReport]
AS
BEGIN
SET NOCOUNT ON;

/*Revision : For Anesthesia Group
	*/

	TRUNCATE TABLE StipendPay

	
	INSERT INTO StipendPay	
	SELECT E.EMPLOYEE, ProviderMasterID, LAST_NAME, FIRST_NAME,
	PG.PAY_SUM_GRP, PG.DESCRIPTION ,WAGE_AMOUNT, TR_DATE, PT.CHECK_ID, 
	PM.CHECK_DATE, E.PROCESS_LEVEL, PM.CHECK_NBR
	FROM PRTIME PT
	JOIN EMPLOYEE E
		ON E.EMPLOYEE = PT.EMPLOYEE
	JOIN LawsonIDMatchSFDC MP ON E.EMPLOYEE = MP.LawsonEmpNo
	JOIN PAYSUMGRP PG
		ON PG.PAY_SUM_GRP = PT.PAY_SUM_GRP
	JOIN PAYMASTR PM ON PM.CHECK_ID = PT.CHECK_ID
					AND PM.EMPLOYEE = PT.EMPLOYEE
	WHERE PG.PAY_SUM_GRP in ('PA2', 'PA3', 'PA4', 'PA5' , 'PA6')
	ORDER BY E.EMPLOYEE, TR_DATE



--select * from StipendPay


		
END



